/** Central route builders for Crow Ecosystem areas */

export const routes = {
  auth: {
    login: "/login",
    signOut: "/auth/signout",
    callback: "/auth/callback",
  },
  portal: {
    home: "/portal",
    requests: "/portal/requests",
    request: (id: string) => `/portal/requests/${id}`,
  },
  /** I3 — authenticated Client Portal skeleton (parallel to legacy /portal). */
  client: {
    home: "/client",
    profile: "/client/profile",
    company: "/client/company",
    requests: "/client/requests",
    request: (id: string) => `/client/requests/${id}`,
    proposals: "/client/proposals",
    proposal: (id: string) => `/client/proposals/${id}`,
    blueprint: (id: string) => `/client/blueprints/${id}`,
    blueprintByRequest: (requestId: string) => `/client/blueprints?request=${requestId}`,
    onboarding: "/client/onboarding",
    settings: "/client/settings",
  },
  public: {
    home: "/",
    modules: "/modules",
    loyalty: "/loyalty-programs",
    security: "/security",
    pricing: "/pricing",
    request: "/request",
    proposal: (token: string) => `/proposal/${token}`,
  },
  admin: {
    overview: "/admin/overview",
    /** J3 — full derived operator queue (read-only, admin-protected). */
    queue: "/admin/queue",
    /** J6 — deployment go/no-go readiness center (advisory, admin-protected). */
    goNoGo: "/admin/go-no-go",
    requests: "/admin/requests",
    request: (id: string) => `/admin/requests/${id}`,
    discovery: "/admin/discovery",
    blueprints: "/admin/blueprints",
    tenants: "/admin/tenants",
    tenant: (id: string) => `/admin/tenants/${id}`,
    domains: "/admin/domains",
    integrations: "/admin/integrations",
    subscriptions: "/admin/subscriptions",
    securityBaselines: "/admin/security-baselines",
    audit: "/admin/audit",
    notifications: "/admin/notifications",
  },
  discovery: (requestId: string) => ({
    base: `/discovery/${requestId}`,
    organization: `/discovery/${requestId}/organization`,
    departments: `/discovery/${requestId}/departments`,
    branches: `/discovery/${requestId}/branches`,
    roles: `/discovery/${requestId}/roles`,
    workflows: `/discovery/${requestId}/workflows`,
    modules: `/discovery/${requestId}/modules`,
    security: `/discovery/${requestId}/security`,
    identity: `/discovery/${requestId}/identity`,
    integrations: `/discovery/${requestId}/integrations`,
    experience: `/discovery/${requestId}/experience`,
    organizationModel: `/discovery/${requestId}/organization-model`,
    summary: `/discovery/${requestId}/summary`,
  }),
  blueprint: (blueprintId: string) => ({
    overview: `/blueprints/${blueprintId}/overview`,
    pricing: `/blueprints/${blueprintId}/pricing`,
    cem: `/blueprints/${blueprintId}/cem`,
    cybercrow: `/blueprints/${blueprintId}/cybercrow`,
    sarea: `/blueprints/${blueprintId}/sarea`,
    identity: `/blueprints/${blueprintId}/identity`,
    integrations: `/blueprints/${blueprintId}/integrations`,
    goLive: `/blueprints/${blueprintId}/go-live`,
    readiness: `/blueprints/${blueprintId}/readiness`,
  }),
  tenant: (slug: string) => ({
    dashboard: `/${slug}/dashboard`,
    workflows: `/${slug}/workflows`,
    tasks: `/${slug}/tasks`,
    users: `/${slug}/users`,
    roles: `/${slug}/roles`,
    departments: `/${slug}/departments`,
    branches: `/${slug}/branches`,
    modules: `/${slug}/modules`,
    reports: `/${slug}/reports`,
    settings: `/${slug}/settings`,
    settingsPlan: `/${slug}/settings/plan`,
    hr: `/${slug}/hr`,
    crm: `/${slug}/crm`,
    sales: `/${slug}/sales`,
    inventory: `/${slug}/inventory`,
    warehouse: `/${slug}/warehouse`,
    logistics: `/${slug}/logistics`,
    finance: `/${slug}/finance`,
    procurement: `/${slug}/procurement`,
    cybercrow: {
      dashboard: `/${slug}/cybercrow/dashboard`,
      auditLogs: `/${slug}/cybercrow/audit-logs`,
      securityEvents: `/${slug}/cybercrow/security-events`,
      risk: `/${slug}/cybercrow/risk`,
      incidents: `/${slug}/cybercrow/incidents`,
      compliance: `/${slug}/cybercrow/compliance`,
      identity: `/${slug}/cybercrow/identity`,
      sessions: `/${slug}/cybercrow/sessions`,
      grc: `/${slug}/cybercrow/grc`,
      evidence: `/${slug}/cybercrow/evidence`,
    },
  }),
  sarea: {
    overview: "/sarea/overview",
    profiles: "/sarea/profiles",
    layouts: "/sarea/layouts",
    roleMapping: "/sarea/role-mapping",
    rules: "/sarea/rules",
    widgets: "/sarea/widgets",
    navigation: "/sarea/navigation",
    deviceRules: "/sarea/device-rules",
    preview: "/sarea/preview",
  },
} as const;
