import type { MessageCatalog } from "./messages";

export const ar: MessageCatalog = {
  productName: "غوراڤيا",
  skipToContent: "تخطَّ إلى المحتوى",
  localOnlyBanner: "بناء محلي اصطناعي فقط — المعاينة والإنتاج معطّلان",
  languageSwitchToEn: "English",
  languageSwitchToAr: "العربية",
  sessionCreate: "إنشاء جلسة محلية اصطناعية",
  sessionExpired: "انتهت الجلسة المحلية. ابدأ جلسة جديدة للمتابعة.",
  sessionUnauthorized: "لا توجد جلسة صالحة. أنشئ جلسة محلية أولاً.",
  loading: "جارٍ التحميل…",
  submitting: "جارٍ الإرسال…",
  retry: "إعادة المحاولة",
  refreshState: "تحديث الحالة من الخادم",
  errorSummary: "هناك خطأ يحتاج انتباهك",
  correlationId: "معرّف الارتباط",
  progressTitle: "تقدّم التفعيل",
  gateEmail: "التحقق من البريد",
  gateTerms: "قبول الشروط",
  gateRisk: "قبول مخاطر الحساب",
  gateComplete: "اكتمل التفعيل",
  mobileOptionalLabel: "التحقق من الجوال اختياري — ليس جزءاً من معادلة التفعيل",
  nextAction: "الإجراء التالي",
  act003Title: "التحقق من البريد معلّق",
  act003Body:
    "التحقق من البريد مطلوب قبل الشروط ومخاطر الحساب. التسليم وحده ليس تحققاً.",
  act003Request: "طلب رسالة التحقق",
  act003Resend: "إعادة إرسال التحقق",
  act003DeliveryAccepted: "قُبلت عملية التسليم محلياً — التحقق لم يكتمل بعد",
  act003NotVerifiedYet: "البريد غير موثَّق بعد",
  act003OpenMailboxDev: "فتح صندوق البريد المحلي (أداة مطوّر)",
  act011Title: "نتيجة التحقق من البريد",
  act011Confirm: "تأكيد رمز التحقق",
  act011TokenLabel: "رمز التحقق",
  act011SuccessNext: "تم التحقق. البوابة التالية المطلوبة: قبول الشروط.",
  act005Title: "قبول الشروط الإلزامية",
  act005Disclaimer:
    "نص الشروط للاختبار المحلي فقط — ليس موافقة قانونية ولا ادّعاء امتثال.",
  act005Checkbox: "أقر بأنني قرأت وأقبل عمداً نسخة الشروط المعروضة",
  act005Accept: "قبول الشروط",
  act005VersionLabel: "نسخة الشروط",
  act013Title: "قبول مخاطر الحساب",
  act013Disclaimer:
    "نص الإفصاح للاختبار المحلي فقط — ليس موافقة قانونية ولا تقييماً مالياً أو تنظيمياً.",
  act013Body:
    "أكّد قبول إفصاح مخاطر الحساب المطلوب في معادلة التفعيل. لا تُعرض درجات المخاطر الداخلية أبداً.",
  act013Checkbox: "أقبل عمداً نسخة إفصاح مخاطر الحساب المعروضة",
  act013Accept: "قبول إفصاح المخاطر",
  act013VersionLabel: "نسخة الإفصاح",
  act012Title: "استعادة التفعيل",
  act012Body:
    "الاستعادة تستأنف الخطوة الإلزامية التالية دون تجاوز بوابات البريد أو الشروط أو المخاطر.",
  act012Recover: "بدء الاستعادة",
  act012Resend: "طلب تحقق بديل",
  act006Title: "الحساب الأساسي مفعّل",
  act006Success: "اكتملت جميع بوابات التفعيل المطلوبة على الخادم.",
  act006Continue: "المتابعة إلى التحقق الاختياري من الجوال",
  act006MobileOptionalNote:
    "التحقق من الجوال اختياري ولا يمنع دخول مسار الإعداد.",
  act007Title: "التحقق من الجوال (اختياري)",
  act007Body:
    "يمكنك المتابعة دون التحقق من الجوال. التعلم العادي لا يُعاقَب عند التأجيل.",
  act007Skip: "لاحقاً / تخطي — إلى دخول الإعداد",
  act007VerifyDeferred:
    "التحقق الفوري عبر الرسائل (ACT-008) مؤجَّل — استخدم التخطي للمتابعة في هذا البناء.",
  onb001Title: "أنشئ حضور غرابك",
  onb001Body:
    "مرحباً. اختر كيف تخصّص غرابك — الهوية البصرية ليست معرفة أو مهارة.",
  onb001LocalNotice: "البناء محلي واصطناعي. تقييم العش بوابة لاحقة.",
  onb001VisualIdentity: "الهوية البصرية ≠ المعرفة",
  onb001Guided: "بدء التخصيص الموجَّه",
  onb001QuickStart: "بدء سريع بالقيم الافتراضية",
  onb001WhyCrow: "لماذا غراب؟",
  onb001WhyCrowBody:
    "غرابك رفيق بصري للحضور والاستمرارية. المظهر لا يمنح خبرة أو إتقاناً أو رتبة أو مكانة أو ثقة.",
  onb001TimeHint:
    "الإعداد الموجَّه عادةً يستغرق دقائق هادئة — خذ الوتيرة التي تناسبك.",
  onboardingProgressTitle: "تقدّم الإعداد",
  idn001Title: "تخصيص الغراب",
  idn001Body: "اختر شكل الغراب واللون والأسلوب وإضافة اختيارية.",
  idn001CrowLegend: "شكل الغراب",
  idn001ColorLegend: "اللون",
  idn001StyleLegend: "الأسلوب",
  idn001AccessoryLegend: "الإضافة",
  idn001ContrastAck:
    "أقرّ بأنني قد أعدّل التباين لاحقاً لإمكانية الوصول — المظهر لا يغيّر المهارة.",
  idn001ContinueHabitat: "المتابعة إلى الموطن",
  idn001LockedAccessory: "إضافة مقفلة (معاينة)",
  idn001LockedExplain:
    "تُفتح هذه الإضافة لاحقاً. معاينة فقط — غير مطلوبة للمتابعة.",
  idn001ReviewTitle: "مراجعة التخصيص",
  idn001PrivacyAck:
    "أفهم معاينة الخصوصية لاختياراتي البصرية. المظهر يبقى محلياً لحضوري.",
  idn001SaveReview: "حفظ المراجعة والمتابعة إلى الأصل",
  idn002Title: "اختر موطناً",
  idn002Body: "اختر موطناً غير مقفل. الخيارات المقفلة للمعاينة فقط.",
  idn002Continue: "المتابعة إلى الشخصية",
  idn002LockedHabitat: "موطن مقفل (معاينة)",
  idn002LockedExplain:
    "يُفتح هذا الموطن لاحقاً. معاينة فقط — غير مطلوب للمتابعة.",
  idn003Title: "اختر شخصية",
  idn003Body: "اختر نموذجاً غير مقفل. الخيارات المقفلة للمعاينة فقط.",
  idn003Continue: "المتابعة إلى المراجعة",
  idn003LockedCharacter: "شخصية مقفلة (معاينة)",
  idn003LockedExplain:
    "تُفتح هذه الشخصية لاحقاً. معاينة فقط — غير مطلوبة للمتابعة.",
  onb002Title: "حدّد أصلك",
  onb002Body:
    "الأصل يساعد لاحقاً في اقتراح الآفاق — تبقى أنت المتحكّم. الأصل ليس ثقة ولا جاهزية.",
  onb002RegionLegend: "المنطقة",
  onb002ExperienceLegend: "سياق الخبرة",
  onb002GoalsLegend: "الأهداف (حتى 3)",
  onb002GoalsHint: "اختر ثلاثة أهداف من الكتالوج كحد أقصى.",
  onb002SaveDraft: "حفظ المسودة",
  onb002ReviewLater: "المراجعة لاحقاً",
  onb002Complete: "إكمال الأصل والمتابعة إلى مقدّمة العش",
  onb002BackCrow: "العودة إلى مراجعة الغراب",
  onb003Title: "العش — أسس رقمية",
  onb003Body:
    "العش حيث تعيش نطاقات الجاهزية والممارسة التأسيسية. التقييم هو البوابة التالية.",
  onb003NestExplain:
    "فحوصات جاهزية العش منفصلة عن الرتبة والمكانة. هذه الشاشة تسليم فقط.",
  onb003StartDeferred: "بدء العش (مؤجَّل)",
  onb003ReviewDeferred: "مراجعة العش (مؤجَّل)",
  onb003TestDeferred: "اختبر جاهزيتك (مؤجَّل)",
  onb003DeferredNote:
    "تقييم العش (ONB-004) مؤجَّل إلى البوابة التالية — تبقى هذه الإجراءات معطّلة هنا.",
  onb003BackOrigin: "العودة إلى الأصل",
  onb003AckHandoff: "إقرار تسليم مقدّمة العش",
  optCrowClassic: "غراب كلاسيكي",
  optCrowRounded: "غراب مستدير",
  optColorInkSand: "حبر رملي",
  optColorDuskTeal: "فيروزي الغسق",
  optColorEmberSlate: "أردواز الجمر",
  optStyleCalm: "هادئ",
  optStyleAlert: "يقظ",
  optStylePlayful: "مرح",
  optAccessoryNone: "بدون إضافة",
  optAccessoryPattern: "نمط ناعم",
  optAccessoryLocked: "إضافة لاحقاً",
  optHabitatCoastal: "رف ساحلي",
  optHabitatMountain: "عش جبلي",
  optHabitatCity: "هوائي المدينة",
  optHabitatDesert: "وادي صحراوي",
  optHabitatLocked: "موطن لاحقاً",
  optCharacterCurious: "كشّاف فضولي",
  optCharacterSteady: "بانٍ ثابت",
  optCharacterCareful: "حارس حريص",
  optCharacterLocked: "شخصية لاحقاً",
  optRegionGulf: "الخليج",
  optRegionLevant: "بلاد الشام",
  optRegionNorthAfrica: "شمال أفريقيا",
  optRegionWiderMena: "الشرق الأوسط وشمال أفريقيا الأوسع",
  optRegionGlobal: "عالمي / أخرى",
  optRegionPreferNot: "أفضل عدم الإفصاح",
  optExpExploring: "أستكشف",
  optExpEarlyCareer: "بداية المسار",
  optExpSwitching: "أغيّر المسار",
  optExpBuilding: "أبني شيئاً",
  optExpPreferNot: "أفضل عدم الإفصاح",
  optGoalFoundations: "تعزيز الأسس",
  optGoalConfidence: "بناء الثقة",
  optGoalExplore: "استكشاف الآفاق",
  optGoalCommunity: "الارتباط بالمجتمع",
  optGoalPreferNot: "أفضل عدم الإفصاح",
  lockEmailTitle: "البريد غير موثَّق",
  lockEmailBody: "أكمل التحقق من البريد قبل الشروط.",
  lockTermsTitle: "الشروط غير مقبولة",
  lockTermsBody: "اقبل نسخة الشروط الحالية للمتابعة.",
  lockRiskTitle: "مخاطر الحساب غير مقبولة",
  lockRiskBody: "اقبل إفصاح مخاطر الحساب الحالي لإكمال التفعيل.",
  lockRecoveryTitle: "الاستعادة مطلوبة",
  lockRecoveryBody: "استخدم مسار الاستعادة للعودة إلى الخطوة الصحيحة.",
  lockReviewTitle: "مراجعة مطلوبة",
  lockReviewBody: "يلزم تدخل مشغّل — لا يمكن تجاوز ذلك من الواجهة.",
  lockSuspendedTitle: "الحساب معلّق",
  lockSuspendedBody: "لا يمكن متابعة التفعيل أثناء التعليق.",
  lockClosedTitle: "الحساب مغلق",
  lockClosedBody: "لا يمكن متابعة التفعيل لحساب مغلق.",
  errValidation: "تحقق من المدخلات وحاول مرة أخرى.",
  errUnauthorized: "الجلسة غير مصرح بها.",
  errForbidden: "هذا الإجراء غير مسموح.",
  errNotFound: "المورد غير موجود.",
  errConflict: "تعارض في الحالة. حدّث ثم أعد الإرسال عمداً.",
  errIdempotencyConflict: "تعارض في إعادة الإرسال. لا تُعاد العملية تلقائياً.",
  errInvalidTransition: "هذا الانتقال غير صالح للحالة الحالية.",
  errChallengeExpired: "انتهت صلاحية تحدي التحقق. اطلب واحداً جديداً.",
  errActivationLocked: "التفعيل مقفل. راجع الأقفال القابلة للتفسير.",
  errProviderUnavailable: "مزوّد المحاكاة غير متاح مؤقتاً.",
  errInternal: "حدث خطأ داخلي. أعد المحاولة بأمان.",
  errStaleVersion:
    "تغيّرت حالة الخادم. حدّث ثم كرّر الإجراء عمداً إن كان لا يزال منطبقاً.",
  errLocalRuntime: "هذا المسار متاح في الوضع المحلي/الاختبار فقط.",
  errCatalogueVersionConflict:
    "تعارض نسخة الكتالوج. حدّث واستخدم الكتالوج الحالي.",
  errOriginSchemaConflict:
    "اختيار الأصل غير صالح للمخطط الحالي. اختر خيارات الكتالوج فقط.",
  devToolsTitle: "أدوات المطوّر المحلية",
  devToolsWarning: "اصطناعي فقط — غير متاح في الإنتاج",
};
