import type { MessageCatalog } from "./messages";

export const en: MessageCatalog = {
  productName: "GHURAVIA",
  skipToContent: "Skip to content",
  localOnlyBanner:
    "Local synthetic build only — Preview and Production disabled",
  languageSwitchToEn: "English",
  languageSwitchToAr: "العربية",
  sessionCreate: "Create local synthetic session",
  sessionExpired: "Local session expired. Start a new session to continue.",
  sessionUnauthorized: "No valid session. Create a local session first.",
  loading: "Loading…",
  submitting: "Submitting…",
  retry: "Retry",
  refreshState: "Refresh state from server",
  errorSummary: "There is an error that needs your attention",
  correlationId: "Correlation ID",
  progressTitle: "Activation progress",
  gateEmail: "Email verification",
  gateTerms: "Terms acceptance",
  gateRisk: "Account-risk acceptance",
  gateComplete: "Activation complete",
  mobileOptionalLabel:
    "Mobile verification is optional — not part of the activation formula",
  nextAction: "Next action",
  act003Title: "Email verification pending",
  act003Body:
    "Email verification is required before terms and account-risk. Delivery alone is not verification.",
  act003Request: "Request verification email",
  act003Resend: "Resend verification",
  act003DeliveryAccepted:
    "Delivery accepted locally — verification is not complete yet",
  act003NotVerifiedYet: "Email is not verified yet",
  act003OpenMailboxDev: "Open local mailbox (developer tool)",
  act011Title: "Email verification result",
  act011Confirm: "Confirm verification token",
  act011TokenLabel: "Verification token",
  act011SuccessNext: "Verified. Next required gate: terms acceptance.",
  act005Title: "Accept mandatory terms",
  act005Disclaimer:
    "Terms content is local test only — not legally approved and not a compliance claim.",
  act005Checkbox:
    "I confirm I have read and deliberately accept the displayed terms version",
  act005Accept: "Accept terms",
  act005VersionLabel: "Terms version",
  act013Title: "Accept account risk",
  act013Disclaimer:
    "Disclosure text is local test only — not legally approved and not financial or regulatory scoring.",
  act013Body:
    "Confirm acceptance of the account-risk disclosure required by the activation formula. Internal risk scores are never shown.",
  act013Checkbox:
    "I deliberately accept the displayed account-risk disclosure version",
  act013Accept: "Accept risk disclosure",
  act013VersionLabel: "Disclosure version",
  act012Title: "Activation recovery",
  act012Body:
    "Recovery resumes the next mandatory step without bypassing email, terms, or account-risk gates.",
  act012Recover: "Begin recovery",
  act012Resend: "Request replacement verification",
  act006Title: "Basic account activated",
  act006Success: "All required activation gates are complete on the server.",
  act006Continue: "Continue to optional mobile verification",
  act006MobileOptionalNote:
    "Mobile verification is optional and does not block onboarding entry.",
  act007Title: "Mobile verification (optional)",
  act007Body:
    "You may continue without mobile verification. Ordinary learning is not punished when deferred.",
  act007Skip: "Later / Skip — continue to onboarding entry",
  act007VerifyDeferred:
    "Immediate SMS verification (ACT-008) is deferred — use Skip to continue in this build.",
  onb001Title: "Create your Crow presence",
  onb001Body:
    "Welcome. Choose how you want to personalize your Crow — visual identity is not knowledge or skill.",
  onb001LocalNotice:
    "This build remains local and synthetic. Nest assessment is a later Gate.",
  onb001VisualIdentity: "Visual Identity ≠ Knowledge",
  onb001Guided: "Start guided personalization",
  onb001QuickStart: "Quick start with defaults",
  onb001WhyCrow: "Why a Crow?",
  onb001WhyCrowBody:
    "Your Crow is a visual companion for presence and continuity. Cosmetics never grant XP, Mastery, Rank, Prestige, or Trust.",
  onb001TimeHint:
    "Guided setup usually takes a few calm minutes — take the pace that fits you.",
  onboardingProgressTitle: "Onboarding progress",
  idn001Title: "Crow personalize",
  idn001Body: "Choose crow shape, color, style, and an optional accessory.",
  idn001CrowLegend: "Crow shape",
  idn001ColorLegend: "Color",
  idn001StyleLegend: "Style",
  idn001AccessoryLegend: "Accessory",
  idn001ContrastAck:
    "I acknowledge I may adjust contrast later for accessibility — cosmetics do not change skill.",
  idn001ContinueHabitat: "Continue to habitat",
  idn001LockedAccessory: "Locked accessory (preview)",
  idn001LockedExplain:
    "This accessory unlocks later. Preview only — not required to continue.",
  idn001ReviewTitle: "Personalization review",
  idn001PrivacyAck:
    "I understand this privacy preview of my visual choices. Cosmetics stay local to my presence.",
  idn001SaveReview: "Save review and continue to Origin",
  idn002Title: "Choose a habitat",
  idn002Body:
    "Select an unlocked habitat backdrop. Locked options are preview only.",
  idn002Continue: "Continue to character",
  idn002LockedHabitat: "Locked habitat (preview)",
  idn002LockedExplain:
    "This habitat unlocks later. Preview only — not required to continue.",
  idn003Title: "Choose a character",
  idn003Body:
    "Select an unlocked character archetype. Locked options are preview only.",
  idn003Continue: "Continue to review",
  idn003LockedCharacter: "Locked character (preview)",
  idn003LockedExplain:
    "This character unlocks later. Preview only — not required to continue.",
  onb002Title: "Set your Origin",
  onb002Body:
    "Origin helps recommend Horizons later — you remain in control. Origin is not Trust or Readiness.",
  onb002RegionLegend: "Region",
  onb002ExperienceLegend: "Experience context",
  onb002GoalsLegend: "Goals (up to 3)",
  onb002GoalsHint: "Select at most three catalogue goals.",
  onb002SaveDraft: "Save draft",
  onb002ReviewLater: "Review later",
  onb002Complete: "Complete Origin and continue to Nest intro",
  onb002BackCrow: "Back to Crow review",
  onb003Title: "The Nest — digital foundations",
  onb003Body:
    "The Nest builds digital foundations before Horizons. You can take a readiness check, start Nest learning, or review what Nest covers.",
  onb003NestExplain:
    "Nest readiness is orientation only — not Lineage, Mastery, Trust, Rank, or Prestige.",
  onb003StartDeferred: "Start with The Nest",
  onb003ReviewDeferred: "Review what Nest covers",
  onb003TestDeferred: "Take readiness check",
  onb003DeferredNote:
    "Local/test fixture catalogue only — not production assessment validity.",
  onb003CoversBody:
    "Nest covers safe device habits, permissions, phishing cues, collaboration basics, and related foundation skills. Missions curriculum ships later.",
  onb003BackOrigin: "Back to Origin",
  onb003AckHandoff: "Acknowledge Nest intro handoff",
  onb004Title: "Nest readiness check",
  onb004Body:
    "Answer each item. Progress saves as you go. Scoring is server-side after you submit all ten.",
  onb004Progress: "Question {n} of {total}",
  onb004Previous: "Previous",
  onb004SaveNext: "Save and continue",
  onb004Submit: "Submit readiness check",
  onb005Title: "Nest readiness result",
  onb005Body: "Your readiness band is orientation guidance — not a credential.",
  onb005ScoreLabel: "Score",
  onb005BandReady: "Ready to Fly",
  onb005BandGuided: "Guided Skip",
  onb005BandNest: "Nest Recommended",
  onb005BandExplain:
    "Bands guide next steps only. They do not award identity or progression.",
  onb005Disclaimer:
    "This result is not Lineage, Mastery, Trust, Rank, or Prestige.",
  onb005AckResult: "Acknowledge result",
  onb005ChooseNest: "Start with The Nest",
  onb005ContinueHorizon: "Continue to Horizon choice",
  onb005HorizonBlocked:
    "Nest Recommended keeps Horizon choice locked — start Nest learning instead.",
  onb006Title: "Nest learning path",
  onb006Body:
    "Nest missions curriculum is not implemented in this slice. This is a handoff screen only.",
  onb006HandoffNote:
    "You can return later when Nest missions ship. No missions, XP, or Mastery are awarded here.",
  onb007Title: "Choose Horizon",
  onb007Body:
    "Horizon selection is not implemented in this slice. This is a handoff screen only.",
  onb007HandoffNote:
    "Ready to Fly and Guided Skip unlock this handoff. Nest Recommended does not.",
  onb007ReturnNest: "Return to Nest learning path",
  optCrowClassic: "Classic Crow",
  optCrowRounded: "Rounded Crow",
  optColorInkSand: "Ink sand",
  optColorDuskTeal: "Dusk teal",
  optColorEmberSlate: "Ember slate",
  optStyleCalm: "Calm",
  optStyleAlert: "Alert",
  optStylePlayful: "Playful",
  optAccessoryNone: "No accessory",
  optAccessoryPattern: "Soft pattern",
  optAccessoryLocked: "Later accessory",
  optHabitatCoastal: "Coastal shelf",
  optHabitatMountain: "Mountain roost",
  optHabitatCity: "City antenna",
  optHabitatDesert: "Desert wadi",
  optHabitatLocked: "Later habitat",
  optCharacterCurious: "Curious scout",
  optCharacterSteady: "Steady builder",
  optCharacterCareful: "Careful guardian",
  optCharacterLocked: "Later character",
  optRegionGulf: "Gulf",
  optRegionLevant: "Levant",
  optRegionNorthAfrica: "North Africa",
  optRegionWiderMena: "Wider MENA",
  optRegionGlobal: "Global / other",
  optRegionPreferNot: "Prefer not to say",
  optExpExploring: "Exploring",
  optExpEarlyCareer: "Early career",
  optExpSwitching: "Switching paths",
  optExpBuilding: "Building something",
  optExpPreferNot: "Prefer not to say",
  optGoalFoundations: "Strengthen foundations",
  optGoalConfidence: "Build confidence",
  optGoalExplore: "Explore horizons",
  optGoalCommunity: "Community connection",
  optGoalPreferNot: "Prefer not to say",
  lockEmailTitle: "Email not verified",
  lockEmailBody: "Complete email verification before terms.",
  lockTermsTitle: "Terms not accepted",
  lockTermsBody: "Accept the current terms version to continue.",
  lockRiskTitle: "Account risk not accepted",
  lockRiskBody:
    "Accept the current account-risk disclosure to finish activation.",
  lockRecoveryTitle: "Recovery required",
  lockRecoveryBody: "Use recovery to return to the correct step.",
  lockReviewTitle: "Operator review required",
  lockReviewBody: "Operator action is required — the UI cannot bypass this.",
  lockSuspendedTitle: "Account suspended",
  lockSuspendedBody: "Activation cannot continue while suspended.",
  lockClosedTitle: "Account closed",
  lockClosedBody: "Activation cannot continue for a closed account.",
  errValidation: "Check your inputs and try again.",
  errUnauthorized: "Session is not authorized.",
  errForbidden: "This action is not allowed.",
  errNotFound: "Resource not found.",
  errConflict: "State conflict. Refresh, then resubmit deliberately.",
  errIdempotencyConflict:
    "Idempotency conflict. Do not automatically retry the operation.",
  errInvalidTransition: "That transition is invalid for the current state.",
  errChallengeExpired: "The verification challenge expired. Request a new one.",
  errActivationLocked: "Activation is locked. Review Explainable Locks.",
  errProviderUnavailable: "The mock provider is temporarily unavailable.",
  errInternal: "An internal error occurred. Retry safely.",
  errStaleVersion:
    "Server state changed. Refresh, then deliberately repeat the action if still applicable.",
  errLocalRuntime: "This path is available in local/test mode only.",
  errCatalogueVersionConflict:
    "Catalogue version conflict. Refresh and use the current catalogue.",
  errOriginSchemaConflict:
    "Origin selection is not valid for the current schema. Choose catalogue options only.",
  devToolsTitle: "Local developer tools",
  devToolsWarning: "Synthetic only — not available in Production",
};
