import type { WorkflowTemplate, WorkflowTopology } from "../types";

const tpl = (
  key: string,
  displayName: string,
  purpose: string,
  topology: WorkflowTopology = "LINEAR",
): WorkflowTemplate => ({
  key,
  displayName,
  description: purpose,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  purpose,
  topology,
  trigger: "manual_request",
  states: ["draft", "active", "review", "closed"],
  transitions: ["submit", "review", "complete", "close"],
  workflowPositions: ["REQUESTER", "COORDINATOR", "REVIEWER", "APPROVER"],
  conditions: [],
  approvalSteps: [],
  exceptionPaths: [],
  escalationPoints: [],
  evidenceRequirementKeys: [],
  auditEventKeys: ["workflow.state_changed"],
  kpiKeys: [],
  cyberCrowCheckKeys: ["baseline_identity_trust"],
  sareaPresentationHints: ["manager_work_queue"],
  primitiveKeys: ["submit", "approve", "complete"],
  scaleVariantHints: ["SOLO", "ENTERPRISE"],
});

/** MODEL.2 field-specific reference workflows — advisory templates only. */
export const WORKFLOW_TEMPLATE_EXTENDED_CATALOG: readonly WorkflowTemplate[] = [
  tpl("bookkeeping_month_close", "Bookkeeping month close", "Month-end bookkeeping coordination — not audit certification."),
  tpl("insurance_client_onboarding", "Insurance client onboarding", "Brokerage client onboarding — not underwriting."),
  tpl("translation_project_delivery", "Translation project delivery", "Localization project delivery workflow."),
  tpl("travel_booking_case", "Travel booking case", "Travel booking case handling.", "CASE_BASED"),
  tpl("photography_project_delivery", "Photography project delivery", "Studio shoot and delivery.", "PROJECT_BASED"),
  tpl("print_job_production", "Print job production", "Print production workflow.", "ITERATIVE"),
  tpl("talent_casting_and_engagement", "Talent casting and engagement", "Casting and talent coordination."),
  tpl("sports_program_enrollment", "Sports program enrollment", "Sports program enrollment.", "LINEAR"),
  tpl("esports_tournament_operations", "Esports tournament operations", "Tournament operations.", "PARALLEL"),
  tpl("consulting_engagement_delivery", "Consulting engagement delivery", "Consulting engagement lifecycle.", "PROJECT_BASED"),
  tpl("nursery_enrollment", "Nursery enrollment", "Childcare enrollment coordination."),
  tpl("veterinary_visit_administration", "Veterinary visit administration", "Practice visit admin — not diagnosis."),
  tpl("clinic_appointment_administration", "Clinic appointment administration", "Clinic scheduling admin."),
  tpl("pharmacy_stock_control", "Pharmacy stock control", "Inventory and approval admin — not prescribing."),
  tpl("vehicle_sales_handover", "Vehicle sales handover", "Vehicle sales handover."),
  tpl("vehicle_rental_turnaround", "Vehicle rental turnaround", "Fleet rental turnaround.", "RECURRING"),
  tpl("home_service_dispatch", "Home service dispatch", "Home service dispatch.", "EVENT_DRIVEN"),
  tpl("pest_control_service", "Pest control service", "Route-based pest control.", "RECURRING"),
  tpl("landscaping_maintenance_cycle", "Landscaping maintenance cycle", "Landscaping maintenance.", "RECURRING"),
  tpl("commercial_cleaning_contract", "Commercial cleaning contract", "Commercial cleaning quality cycle."),
  tpl("catering_order_delivery", "Catering order delivery", "Catering fulfillment.", "EVENT_DRIVEN"),
  tpl("wholesale_order_fulfillment", "Wholesale order fulfillment", "Wholesale fulfillment."),
  tpl("import_export_document_review", "Import export document review", "Trade document review.", "CONDITIONAL"),
  tpl("customs_submission_coordination", "Customs submission coordination", "Customs case coordination.", "CASE_BASED"),
  tpl("warehouse_fulfillment_cycle", "Warehouse fulfillment cycle", "Warehouse pick-pack-ship."),
  tpl("property_fitout_project", "Property fitout project", "Interior fit-out project.", "PROJECT_BASED"),
  tpl("wedding_event_delivery", "Wedding event delivery", "Wedding production delivery.", "MISSION_BASED"),
  tpl("nonprofit_program_case", "Nonprofit program case", "Program case management.", "CASE_BASED"),
  tpl("dispatch_and_delivery", "Dispatch and delivery", "Dispatch resources and complete delivery.", "EVENT_DRIVEN"),
  tpl("work_order_execution", "Work order execution", "Execute field work orders.", "LINEAR"),
  tpl("request_and_approval", "Request and approval", "Generic request approval path.", "LINEAR"),
  tpl("hire_to_onboard", "Hire to onboard", "Recruitment through onboarding.", "LINEAR"),
  tpl("contract_review_and_approval", "Contract review and approval", "Contract review gate.", "CONDITIONAL"),
  tpl("customer_onboarding", "Customer onboarding", "Onboard new customers.", "LINEAR"),
  tpl("booking_to_service_completion", "Booking to service completion", "Booking through service completion.", "EVENT_DRIVEN"),
] as const;
