import type { WorkflowTemplate, WorkflowTopology } from "../types";

const tpl = (
  key: string,
  displayName: string,
  purpose: string,
  topology: WorkflowTopology,
): WorkflowTemplate => ({
  key,
  displayName,
  description: purpose,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  purpose,
  topology,
  trigger: "manual_request",
  states: ["draft", "active", "closed"],
  transitions: ["submit", "complete", "close"],
  workflowPositions: ["REQUESTER", "COORDINATOR", "APPROVER"],
  conditions: [],
  approvalSteps: [],
  exceptionPaths: [],
  escalationPoints: [],
  evidenceRequirementKeys: [],
  auditEventKeys: ["workflow.state_changed"],
  kpiKeys: [],
  cyberCrowCheckKeys: ["baseline_identity_trust"],
  sareaPresentationHints: ["manager_work_queue"],
  primitiveKeys: ["submit", "approve", "complete"],
  scaleVariantHints: ["SOLO", "ENTERPRISE"],
});

export const WORKFLOW_TEMPLATE_CATALOG: readonly WorkflowTemplate[] = [
  {
    ...tpl("client_intake_and_qualification", "Client intake and qualification", "Qualify new clients before engagement.", "LINEAR"),
    states: ["intake", "qualification", "approved", "rejected", "closed"],
    transitions: ["submit", "review", "approve", "reject", "close"],
    workflowPositions: ["REQUESTER", "COORDINATOR", "REVIEWER", "APPROVER"],
    kpiKeys: ["qualification_cycle_time"],
    primitiveKeys: ["submit", "review", "approve", "reject"],
  },
  {
    ...tpl("matter_intake_and_conflict_check", "Matter intake and conflict check", "Legal matter intake — not legal advice.", "CONDITIONAL"),
    states: ["intake", "conflict_check", "cleared", "blocked", "assigned"],
    workflowPositions: ["REQUESTER", "COORDINATOR", "REVIEWER", "APPROVER"],
    evidenceRequirementKeys: ["conflict_check_record"],
    cyberCrowCheckKeys: ["audit_and_evidence", "sensitive_hr_data"],
  },
  {
    ...tpl("creative_asset_production", "Creative asset production", "Produce and review creative assets.", "ITERATIVE"),
    topology: "ITERATIVE",
    states: ["brief", "production", "review", "revision", "approved"],
    workflowPositions: ["OWNER", "CONTRIBUTOR", "REVIEWER", "FINAL_SIGNATORY"],
    evidenceRequirementKeys: ["asset_version_history"],
    kpiKeys: ["revision_count", "cycle_time"],
    sareaPresentationHints: ["project_workspace", "specialist_workspace"],
  },
  {
    ...tpl("release_readiness", "Release readiness", "Coordinate release go/no-go.", "PARALLEL"),
    topology: "PARALLEL",
    states: ["planning", "checks", "sign_off", "released", "rolled_back"],
    workflowPositions: ["COORDINATOR", "REVIEWER", "FINAL_SIGNATORY", "OBSERVER"],
    escalationPoints: ["failed_critical_check"],
    kpiKeys: ["release_success_rate"],
    cyberCrowCheckKeys: ["high_risk_workflow_approval"],
  },
  {
    ...tpl("rights_clearance", "Rights clearance", "Clear rights for assets and distribution.", "CONDITIONAL"),
    states: ["requested", "review", "cleared", "denied"],
    workflowPositions: ["REQUESTER", "COORDINATOR", "REVIEWER", "APPROVER"],
    evidenceRequirementKeys: ["rights_documentation"],
  },
  {
    ...tpl("crew_onboarding", "Crew onboarding", "Onboard production or field crews.", "LINEAR"),
    states: ["invited", "compliance", "trained", "active"],
    workflowPositions: ["COORDINATOR", "CONTRIBUTOR", "REVIEWER"],
    cyberCrowCheckKeys: ["contractor_access", "sensitive_hr_data"],
  },
  {
    ...tpl("equipment_booking_and_return", "Equipment booking and return", "Book and return equipment assets.", "RECURRING"),
    topology: "RECURRING",
    states: ["requested", "booked", "in_use", "returned", "inspected"],
    workflowPositions: ["REQUESTER", "COORDINATOR", "EXECUTOR", "INSPECTOR"],
    primitiveKeys: ["submit", "schedule", "complete", "inspect"],
  },
  {
    ...tpl("site_mobilization", "Site mobilization", "Mobilize people and assets to site.", "MISSION_BASED"),
    topology: "MISSION_BASED",
    states: ["planned", "mobilizing", "on_site", "demobilized"],
    workflowPositions: ["OWNER", "COORDINATOR", "EXECUTOR"],
    cyberCrowCheckKeys: ["field_device_trust"],
  },
  {
    ...tpl("case_resolution", "Case resolution", "Resolve service cases end-to-end.", "CASE_BASED"),
    topology: "CASE_BASED",
    states: ["open", "assigned", "in_progress", "resolved", "closed"],
    workflowPositions: ["REQUESTER", "OWNER", "CONTRIBUTOR", "ESCALATION_OWNER"],
    kpiKeys: ["case_resolution_time", "sla_breach_rate"],
    primitiveKeys: ["submit", "assign", "escalate", "complete"],
  },
  {
    ...tpl("incident_command", "Incident command", "Command incident response.", "EMERGENCY"),
    topology: "EMERGENCY",
    states: ["detected", "triaged", "responding", "contained", "closed"],
    workflowPositions: ["OWNER", "ESCALATION_OWNER", "CONTRIBUTOR", "OBSERVER"],
    escalationPoints: ["severity_upgrade"],
    evidenceRequirementKeys: ["incident_timeline"],
    cyberCrowCheckKeys: ["incident_escalation", "audit_and_evidence"],
    sareaPresentationHints: ["security_posture_console"],
  },
  {
    ...tpl("vendor_qualification", "Vendor qualification", "Qualify vendors before engagement.", "LINEAR"),
    states: ["application", "review", "qualified", "rejected"],
    workflowPositions: ["REQUESTER", "REVIEWER", "APPROVER", "EVIDENCE_CUSTODIAN"],
    cyberCrowCheckKeys: ["vendor_access"],
  },
  {
    ...tpl("project_change_control", "Project change control", "Control project scope changes.", "PROJECT_BASED"),
    topology: "PROJECT_BASED",
    states: ["proposed", "impact_analysis", "approved", "implemented", "closed"],
    workflowPositions: ["REQUESTER", "REVIEWER", "APPROVER", "OWNER"],
    approvalSteps: ["impact_review", "sponsor_approval"],
  },
  {
    ...tpl("inspection_and_corrective_action", "Inspection and corrective action", "Inspect and remediate findings.", "ITERATIVE"),
    states: ["scheduled", "inspected", "action_required", "remediated", "verified"],
    workflowPositions: ["INSPECTOR", "OWNER", "EXECUTOR", "REVIEWER"],
    evidenceRequirementKeys: ["inspection_report", "corrective_proof"],
    primitiveKeys: ["inspect", "assign", "complete", "verify"],
  },
  {
    ...tpl("service_booking_and_completion", "Service booking and completion", "Book and complete services.", "EVENT_DRIVEN"),
    topology: "EVENT_DRIVEN",
    states: ["booked", "confirmed", "in_service", "completed"],
    workflowPositions: ["REQUESTER", "COORDINATOR", "EXECUTOR"],
    kpiKeys: ["service_completion_rate"],
  },
  {
    ...tpl("member_enrollment", "Member enrollment", "Enroll members into programs.", "LINEAR"),
    states: ["applied", "verified", "active"],
    workflowPositions: ["REQUESTER", "COORDINATOR", "REVIEWER"],
    sareaPresentationHints: ["guided_onboarding", "member_portal"],
  },
  {
    ...tpl("research_review_and_evidence", "Research review and evidence", "Review research with evidence custody.", "COLLABORATIVE"),
    topology: "COLLABORATIVE",
    states: ["submitted", "peer_review", "revision", "accepted"],
    workflowPositions: ["CONTRIBUTOR", "REVIEWER", "EVIDENCE_CUSTODIAN"],
    evidenceRequirementKeys: ["lab_notebook", "peer_review_record"],
    cyberCrowCheckKeys: ["audit_and_evidence", "data_export_control"],
  },
  {
    ...tpl("content_review_and_publication", "Content review and publication", "Editorial review and publish.", "PARALLEL"),
    states: ["draft", "editorial", "legal_review", "approved", "published"],
    workflowPositions: ["CONTRIBUTOR", "REVIEWER", "APPROVER", "FINAL_SIGNATORY"],
    approvalSteps: ["editorial", "optional_legal"],
  },
  {
    ...tpl("customer_recovery", "Customer recovery", "Recover at-risk customer relationships.", "CASE_BASED"),
    topology: "CASE_BASED",
    states: ["at_risk", "plan", "executing", "recovered", "churned"],
    workflowPositions: ["OWNER", "COORDINATOR", "CONTRIBUTOR"],
    kpiKeys: ["recovery_rate"],
  },
  {
    ...tpl("branch_launch", "Branch launch", "Launch new operating branch.", "CROSS_BRANCH"),
    topology: "CROSS_BRANCH",
    states: ["planning", "readiness", "soft_launch", "operational"],
    workflowPositions: ["OWNER", "COORDINATOR", "APPROVER", "FINAL_SIGNATORY"],
    cyberCrowCheckKeys: ["branch_access_control"],
  },
  {
    ...tpl("high_risk_supplier_onboarding", "High risk supplier onboarding", "Enhanced supplier onboarding for high risk.", "CONDITIONAL"),
    states: ["intake", "risk_assessment", "compliance", "approved", "rejected"],
    workflowPositions: ["REQUESTER", "REVIEWER", "APPROVER", "EVIDENCE_CUSTODIAN"],
    approvalSteps: ["risk", "compliance", "executive"],
    cyberCrowCheckKeys: ["vendor_access", "high_risk_workflow_approval", "audit_and_evidence"],
  },
] as const;
