/**
 * CROW.DISCOVERY.7 — Stage 4–7 adaptive field definitions (local-first).
 * Controlled catalog depth — not the full 23-category question model.
 */

import {
  DISCOVERY_MVP_D3_FIELD_VERSION,
  type DiscoveryMvpFieldDefinition,
} from "@/lib/discovery/discovery-mvp-d3-types";

const V = DISCOVERY_MVP_D3_FIELD_VERSION;

const EVIDENCE_TYPE_OPTIONS = [
  { value: "policy", label: "Policy / standard" },
  { value: "process_doc", label: "Process document" },
  { value: "system_inventory", label: "System inventory" },
  { value: "org_chart", label: "Org chart / structure" },
  { value: "audit_report", label: "Audit / assessment report" },
  { value: "other_reference", label: "Other reference" },
] as const;

const EVIDENCE_AVAILABILITY_OPTIONS = [
  { value: "available", label: "Available (reference ready)" },
  { value: "partial", label: "Partial / incomplete reference" },
  { value: "not_available_yet", label: "Not available yet" },
] as const;

const RISK_PRIORITY_OPTIONS = [
  { value: "low", label: "Low" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
] as const;

const LAUNCH_MODEL_OPTIONS = [
  { value: "phased", label: "Phased launch" },
  { value: "pilot_then_expand", label: "Pilot then expand" },
  { value: "big_bang", label: "Single go-live window" },
  { value: "undecided", label: "Undecided" },
] as const;

const MODELING_SELF_CHECK_OPTIONS = [
  { value: "not_ready", label: "Not ready for modeling review" },
  { value: "needs_info", label: "Needs more information" },
  { value: "ready_for_review", label: "Ready for ProCrow modeling review" },
] as const;

/**
 * Stage 4–7 depth fields. Merged into the MVP catalog by getDiscoveryMvpD3Catalog().
 */
export const DISCOVERY_MVP_D7_STAGE_FIELDS: readonly DiscoveryMvpFieldDefinition[] = [
  // —— Stage 4 Trust and risk ——
  {
    fieldKey: "sensitive_data_types",
    label: "Sensitive data types",
    helperText: "Categories of sensitive data in scope (PII, financial, health, etc.) — no sample values.",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["trust", "data", "risks"],
    mapsToBlueprintSection: "cybercrow",
    riskSensitivity: "high",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "identity_access_concerns",
    label: "Identity / access concerns",
    helperText: "Who needs access, known IdP constraints, privileged-access worries.",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["trust", "identity"],
    mapsToBlueprintSection: "identity",
    riskSensitivity: "high",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "approval_risk_areas",
    label: "Approval-risk areas",
    helperText: "Where weak or missing approvals create material risk.",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["decisions", "approvals", "risks"],
    mapsToBlueprintSection: "cem",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "audit_requirements",
    label: "Audit requirements",
    helperText: "Internal or external audit expectations that Discovery must respect.",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 2000 },
    mapsToOperatingModel: ["trust", "compliance"],
    mapsToBlueprintSection: "cybercrow",
    riskSensitivity: "medium",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "compliance_regulation_notes",
    label: "Compliance / regulation notes",
    helperText: "Regimes or policies in play (names only — not legal advice).",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "if_org_EXISTING_ORGANIZATION",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 2000 },
    mapsToOperatingModel: ["trust", "compliance"],
    mapsToBlueprintSection: "cybercrow",
    riskSensitivity: "high",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "segregation_of_duties_concerns",
    label: "Segregation-of-duties concerns",
    helperText: "Roles that must not combine (e.g. request + approve + pay).",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["decisions", "trust", "risks"],
    mapsToBlueprintSection: "cem",
    riskSensitivity: "high",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "operational_risk_areas",
    label: "Operational risk areas",
    helperText: "Day-to-day operational risks that should shape the Operating Model.",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 2000 },
    mapsToOperatingModel: ["risks", "operations"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "security_priorities",
    label: "Security priorities",
    helperText: "Top security outcomes for this Discovery (priority ranking in text).",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["trust", "security"],
    mapsToBlueprintSection: "cybercrow",
    riskSensitivity: "high",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "trust_constraints",
    label: "Trust constraints",
    helperText: "Hard constraints (data residency, vendor bans, air-gapped zones, etc.).",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 2000 },
    mapsToOperatingModel: ["trust", "constraints"],
    mapsToBlueprintSection: "cybercrow",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "trust_risk_priority",
    label: "Overall trust / risk priority",
    helperText: "How urgent is trust-and-risk modeling for ProCrow.",
    fieldType: "single_select",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { enum: RISK_PRIORITY_OPTIONS.map((o) => o.value) },
    mapsToOperatingModel: ["trust", "risks"],
    mapsToBlueprintSection: "cybercrow",
    riskSensitivity: "medium",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
    options: RISK_PRIORITY_OPTIONS,
  },
  {
    fieldKey: "new_business_foundation_risks",
    label: "New-business foundation risks",
    helperText: "Risks unique to standing up a new business (brand, capital, licensing).",
    fieldType: "long_text",
    stageId: 4,
    version: V,
    layer: "L6",
    category: "trust_and_risk",
    requiredCondition: "if_org_NEW_BUSINESS",
    journeyApplicability: "BOTH",
    organizationContextApplicability: ["NEW_BUSINESS"],
    visibilityCondition: "if_org_NEW_BUSINESS",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["trust", "risks", "context"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },

  // —— Stage 5 Build / Transform intent ——
  {
    fieldKey: "target_launch_model",
    label: "Target launch model",
    helperText: "How you expect to go live for a new build.",
    fieldType: "single_select",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_NEW",
    journeyApplicability: "NEW",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_NEW",
    validation: { enum: LAUNCH_MODEL_OPTIONS.map((o) => o.value) },
    mapsToOperatingModel: ["target_state", "transition"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
    options: LAUNCH_MODEL_OPTIONS,
  },
  {
    fieldKey: "initial_operating_capabilities",
    label: "Initial operating capabilities",
    helperText: "Capabilities that must work on day one of the new build.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_NEW",
    journeyApplicability: "NEW",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_NEW",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["target_state", "capabilities"],
    mapsToBlueprintSection: "cem",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "first_teams_to_activate",
    label: "First teams to activate",
    helperText: "Which teams go live first in the new operating model.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_NEW",
    journeyApplicability: "NEW",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_NEW",
    validation: { minLength: 5, maxLength: 2000 },
    mapsToOperatingModel: ["people", "target_state"],
    mapsToBlueprintSection: "organization",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "required_go_live_readiness",
    label: "Required go-live readiness",
    helperText: "Checklist themes that must be true before go-live (training, data, approvals).",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_NEW",
    journeyApplicability: "NEW",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_NEW",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["transition", "readiness"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "expected_constraints_new",
    label: "Expected constraints (new build)",
    helperText: "Budget, time, vendor, or regulatory constraints for the new build.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "never",
    journeyApplicability: "NEW",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_NEW",
    validation: { maxLength: 2000 },
    mapsToOperatingModel: ["constraints", "target_state"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },
  {
    fieldKey: "current_state_problems",
    label: "Current-state problems",
    helperText: "What is broken or costly in the current operating model.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { minLength: 20, maxLength: 2000 },
    mapsToOperatingModel: ["current_state", "risks"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "legacy_system_constraints",
    label: "Legacy system constraints",
    helperText: "Hard limits from legacy systems during transformation.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["systems", "constraints", "transition"],
    mapsToBlueprintSection: "integrations",
    riskSensitivity: "medium",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "process_change_goals",
    label: "Process-change goals",
    helperText: "Which processes must change and what “better” looks like.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["workflows", "target_state"],
    mapsToBlueprintSection: "workflows",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "migration_concerns",
    label: "Migration concerns",
    helperText: "Data, cutover, dual-run, or rollback concerns.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["transition", "risks"],
    mapsToBlueprintSection: "integrations",
    riskSensitivity: "high",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "change_readiness_notes",
    label: "Change-readiness notes",
    helperText: "People and culture readiness for the transformation.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "never",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { maxLength: 2000 },
    mapsToOperatingModel: ["people", "transition"],
    mapsToBlueprintSection: "organization",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },
  {
    fieldKey: "target_state_improvements",
    label: "Target-state improvements",
    helperText: "Concrete improvements expected after transformation.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["target_state"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "modernization_program_notes",
    label: "Modernization program notes",
    helperText: "Program waves, sponsors, and modernization-specific intent.",
    fieldType: "long_text",
    stageId: 5,
    version: V,
    layer: "L8",
    category: "build_transform_intent",
    requiredCondition: "if_org_MODERNIZATION",
    journeyApplicability: "BOTH",
    organizationContextApplicability: ["MODERNIZATION"],
    visibilityCondition: "if_org_MODERNIZATION",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["transition", "target_state"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },

  // —— Stage 6 Evidence references (refs-only) ——
  {
    fieldKey: "evidence_title",
    label: "Evidence title",
    helperText: "Short title for the primary evidence reference (not a file upload).",
    fieldType: "short_text",
    stageId: 6,
    version: V,
    layer: "L9",
    category: "evidence_refs",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 2, maxLength: 160, refsOnly: true },
    mapsToOperatingModel: ["evidence"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "evidence_type",
    label: "Evidence type",
    helperText: "What kind of reference this is — still references only.",
    fieldType: "single_select",
    stageId: 6,
    version: V,
    layer: "L9",
    category: "evidence_refs",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { enum: EVIDENCE_TYPE_OPTIONS.map((o) => o.value), refsOnly: true },
    mapsToOperatingModel: ["evidence"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
    options: EVIDENCE_TYPE_OPTIONS,
  },
  {
    fieldKey: "evidence_reference_description",
    label: "Reference description",
    helperText: "Describe where the evidence lives (URL, share name, owner) — no uploads.",
    fieldType: "long_text",
    stageId: 6,
    version: V,
    layer: "L9",
    category: "evidence_refs",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 5, maxLength: 2000, refsOnly: true },
    mapsToOperatingModel: ["evidence"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "evidence_related_question_keys",
    label: "Related question keys",
    helperText: "Comma-separated Discovery field keys this evidence supports (e.g. main_workflows).",
    fieldType: "short_text",
    stageId: 6,
    version: V,
    layer: "L9",
    category: "evidence_refs",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 500, refsOnly: true },
    mapsToOperatingModel: ["evidence"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },
  {
    fieldKey: "evidence_availability_status",
    label: "Availability status",
    helperText: "Whether the reference is available now, partial, or not yet. Recommended for ProCrow.",
    fieldType: "single_select",
    stageId: 6,
    version: V,
    layer: "L9",
    category: "evidence_refs",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: {
      enum: EVIDENCE_AVAILABILITY_OPTIONS.map((o) => o.value),
      refsOnly: true,
    },
    mapsToOperatingModel: ["evidence"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
    options: EVIDENCE_AVAILABILITY_OPTIONS,
  },
  {
    fieldKey: "evidence_not_available_reason",
    label: "Not-available-yet reason",
    helperText: "Required when status is “Not available yet”. Still references-only — no uploads.",
    fieldType: "long_text",
    stageId: 6,
    version: V,
    layer: "L9",
    category: "evidence_refs",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 2000, refsOnly: true },
    mapsToOperatingModel: ["evidence", "assumptions"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "evidence_local_metadata_note",
    label: "Local-only metadata",
    helperText: "Browser-local note for operators — never written to hosted storage from this form.",
    fieldType: "long_text",
    stageId: 6,
    version: V,
    layer: "L9",
    category: "evidence_refs",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 2000, refsOnly: true },
    mapsToOperatingModel: ["evidence"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: false,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },

  // —— Stage 7 ProCrow review summary (preparation — not Blueprint approval) ——
  {
    fieldKey: "stage7_missing_information_notes",
    label: "Missing information (by stage)",
    helperText: "Local notes on what is still missing across Stages 1–6. Not final approval.",
    fieldType: "long_text",
    stageId: 7,
    version: V,
    layer: "L10",
    category: "procrow_review_summary",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 4000 },
    mapsToOperatingModel: ["assumptions", "missing"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "stage7_critical_blockers_notes",
    label: "Critical blockers",
    helperText: "Local list of blockers before modeling — does not approve Blueprint.",
    fieldType: "long_text",
    stageId: 7,
    version: V,
    layer: "L10",
    category: "procrow_review_summary",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 4000 },
    mapsToOperatingModel: ["risks", "missing"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "medium",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "stage7_clarification_questions_local",
    label: "Clarification questions",
    helperText: "Questions ProCrow should ask next. Local draft only.",
    fieldType: "long_text",
    stageId: 7,
    version: V,
    layer: "L10",
    category: "procrow_review_summary",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 4000 },
    mapsToOperatingModel: ["clarifications"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "stage7_trust_risk_flags_notes",
    label: "Trust / risk flags",
    helperText: "Flags from Stage 4 that ProCrow must not ignore.",
    fieldType: "long_text",
    stageId: 7,
    version: V,
    layer: "L10",
    category: "procrow_review_summary",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 4000 },
    mapsToOperatingModel: ["trust", "risks"],
    mapsToBlueprintSection: "cybercrow",
    riskSensitivity: "high",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "stage7_evidence_gaps_notes",
    label: "Evidence gaps",
    helperText: "Gaps from Stage 6 references — still no file upload path.",
    fieldType: "long_text",
    stageId: 7,
    version: V,
    layer: "L10",
    category: "procrow_review_summary",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 4000, refsOnly: true },
    mapsToOperatingModel: ["evidence", "missing"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "stage7_modeling_readiness_self_check",
    label: "Modeling readiness (self-check)",
    helperText: "Local self-assessment only — never sets readyForBlueprintDraft or generation allowed.",
    fieldType: "single_select",
    stageId: 7,
    version: V,
    layer: "L10",
    category: "procrow_review_summary",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { enum: MODELING_SELF_CHECK_OPTIONS.map((o) => o.value) },
    mapsToOperatingModel: ["readiness"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
    options: MODELING_SELF_CHECK_OPTIONS,
  },
  {
    fieldKey: "stage7_handoff_readiness_notes",
    label: "Handoff readiness notes",
    helperText: "Notes for a future Blueprint handoff package — generation remains blocked.",
    fieldType: "long_text",
    stageId: 7,
    version: V,
    layer: "L10",
    category: "procrow_review_summary",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 4000 },
    mapsToOperatingModel: ["handoff", "assumptions"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },
  {
    fieldKey: "stage7_operator_notes_local",
    label: "Operator notes (local-only)",
    helperText: "Operator-only local notes — not hosted business data.",
    fieldType: "long_text",
    stageId: 7,
    version: V,
    layer: "L10",
    category: "procrow_review_summary",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 4000 },
    mapsToOperatingModel: ["notes"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: false,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },
] as const;
