/**
 * CROW.DISCOVERY.3 — Stage 1–3 MVP adaptive field catalog (local-first).
 * Stages 4–7 remain planned placeholders in the workspace shell.
 */

import type { DiscoveryMvpFieldDefinition } from "@/lib/discovery/discovery-mvp-d3-types";
import { DISCOVERY_MVP_D3_FIELD_VERSION } from "@/lib/discovery/discovery-mvp-d3-types";

const V = DISCOVERY_MVP_D3_FIELD_VERSION;

const SIZE_OPTIONS = [
  { value: "SOLO_1", label: "Solo / 1" },
  { value: "TEAM_2_5", label: "2–5 people" },
  { value: "TEAM_6_20", label: "6–20 people" },
  { value: "TEAM_21_50", label: "21–50 people" },
  { value: "TEAM_51_200", label: "51–200 people" },
  { value: "TEAM_200_PLUS", label: "200+ people" },
] as const;

const LOCATION_OPTIONS = [
  { value: "SINGLE_SITE", label: "Single site / HQ" },
  { value: "MULTI_BRANCH", label: "Multi-branch" },
  { value: "MULTI_COUNTRY", label: "Multi-country" },
  { value: "HYBRID_REMOTE", label: "Hybrid / remote-first" },
  { value: "FRANCHISE", label: "Franchise / network" },
] as const;

/** MVP catalog — Stages 1–3 only. */
export const DISCOVERY_MVP_D3_CATALOG: readonly DiscoveryMvpFieldDefinition[] = [
  // —— Stage 1 Context ——
  {
    fieldKey: "organization_display_name",
    label: "Organization display name",
    helperText: "How Crow should refer to this organization during Discovery.",
    fieldType: "short_text",
    stageId: 1,
    version: V,
    layer: "L1",
    category: "context",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 2, maxLength: 120 },
    mapsToOperatingModel: ["intent", "identity"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "primary_contact_role",
    label: "Primary contact role",
    helperText: "Role of the person guiding Discovery (e.g. founder, operations lead).",
    fieldType: "short_text",
    stageId: 1,
    version: V,
    layer: "L1",
    category: "context",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 2, maxLength: 80 },
    mapsToOperatingModel: ["people"],
    mapsToBlueprintSection: "identity",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "purpose_mission",
    label: "Purpose / mission",
    helperText: "In plain language: what this organization exists to achieve.",
    fieldType: "long_text",
    stageId: 1,
    version: V,
    layer: "L1",
    category: "context",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 20, maxLength: 2000 },
    mapsToOperatingModel: ["intent", "purpose"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "build_transform_objective",
    label: "Discovery objective",
    helperText: "What success looks like for this Discovery — build new or transform existing.",
    fieldType: "long_text",
    stageId: 1,
    version: V,
    layer: "L2",
    category: "context",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 20, maxLength: 2000 },
    mapsToOperatingModel: ["intent"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "expected_operating_start",
    label: "Expected operating start",
    helperText: "When you hope the new operating model should be ready to run (target window).",
    fieldType: "short_text",
    stageId: 1,
    version: V,
    layer: "L2",
    category: "context",
    requiredCondition: "if_journey_NEW",
    journeyApplicability: "NEW",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_NEW",
    validation: { minLength: 2, maxLength: 120 },
    mapsToOperatingModel: ["intent", "timeline"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "transformation_target",
    label: "Transformation target",
    helperText: "What should change first, and what must stay stable during transformation.",
    fieldType: "long_text",
    stageId: 1,
    version: V,
    layer: "L2",
    category: "context",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { minLength: 20, maxLength: 2000 },
    mapsToOperatingModel: ["intent", "target_state"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },

  // —— Stage 2 Organization shape ——
  {
    fieldKey: "industry_sector",
    label: "Industry / sector",
    helperText: "Primary industry or sector this Discovery should model.",
    fieldType: "short_text",
    stageId: 2,
    version: V,
    layer: "L3",
    category: "organization_shape",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 2, maxLength: 120 },
    mapsToOperatingModel: ["context", "industry"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "organization_size_range",
    label: "Organization size range",
    helperText: "Approximate people count for the scope of this Discovery.",
    fieldType: "single_select",
    stageId: 2,
    version: V,
    layer: "L3",
    category: "organization_shape",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { enum: SIZE_OPTIONS.map((o) => o.value) },
    mapsToOperatingModel: ["scale"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
    options: SIZE_OPTIONS,
  },
  {
    fieldKey: "location_model",
    label: "Location model",
    helperText: "How locations and sites are organized for day-to-day work.",
    fieldType: "single_select",
    stageId: 2,
    version: V,
    layer: "L3",
    category: "organization_shape",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { enum: LOCATION_OPTIONS.map((o) => o.value) },
    mapsToOperatingModel: ["topology"],
    mapsToBlueprintSection: "organization",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
    options: LOCATION_OPTIONS,
  },
  {
    fieldKey: "branch_site_count",
    label: "Branch / site count",
    helperText: "Approximate number of branches or sites in scope (0 if single site).",
    fieldType: "number",
    stageId: 2,
    version: V,
    layer: "L3",
    category: "organization_shape",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { min: 0, max: 10000 },
    mapsToOperatingModel: ["topology"],
    mapsToBlueprintSection: "organization",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },
  {
    fieldKey: "department_division_scope",
    label: "Department or division scope",
    helperText: "Which departments or divisions are in scope for this Discovery.",
    fieldType: "long_text",
    stageId: 2,
    version: V,
    layer: "L3",
    category: "organization_shape",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["structure", "departments"],
    mapsToBlueprintSection: "organization",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "customer_beneficiary_type",
    label: "Customer / beneficiary type",
    helperText: "Who the organization primarily serves (customers, patients, citizens, partners, etc.).",
    fieldType: "short_text",
    stageId: 2,
    version: V,
    layer: "L3",
    category: "organization_shape",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 2, maxLength: 160 },
    mapsToOperatingModel: ["context"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },
  {
    fieldKey: "parent_organization_relationship",
    label: "Parent organization relationship",
    helperText: "How this division relates to the parent (shared services, autonomy, reporting).",
    fieldType: "long_text",
    stageId: 2,
    version: V,
    layer: "L3",
    category: "organization_shape",
    requiredCondition: "if_org_NEW_DIVISION",
    journeyApplicability: "BOTH",
    organizationContextApplicability: ["NEW_DIVISION"],
    visibilityCondition: "if_org_NEW_DIVISION",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["structure", "parent"],
    mapsToBlueprintSection: "organization",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },

  // —— Stage 3 Operating reality ——
  {
    fieldKey: "key_teams_or_groups",
    label: "Key teams or groups",
    helperText: "List the main teams or groups that must appear in the Operating Model later.",
    fieldType: "long_text",
    stageId: 3,
    version: V,
    layer: "L4",
    category: "operating_reality",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["people", "teams"],
    mapsToBlueprintSection: "organization",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "core_responsibilities",
    label: "Core responsibilities",
    helperText: "What each key group is accountable for day to day.",
    fieldType: "long_text",
    stageId: 3,
    version: V,
    layer: "L4",
    category: "operating_reality",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["responsibilities"],
    mapsToBlueprintSection: "cem",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "main_workflows",
    label: "Main workflows",
    helperText: "Name the core workflow families (e.g. sell-to-cash, hire-to-retire, project delivery).",
    fieldType: "long_text",
    stageId: 3,
    version: V,
    layer: "L4",
    category: "operating_reality",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["workflows"],
    mapsToBlueprintSection: "workflows",
    riskSensitivity: "low",
    evidenceRequirement: "none",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "current_systems_tools",
    label: "Current systems / tools",
    helperText: "List systems and tools in use today (names only — no credentials).",
    fieldType: "long_text",
    stageId: 3,
    version: V,
    layer: "L4",
    category: "operating_reality",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { minLength: 5, maxLength: 2000 },
    mapsToOperatingModel: ["systems"],
    mapsToBlueprintSection: "integrations",
    riskSensitivity: "medium",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "legacy_systems_modernization",
    label: "Legacy systems to modernize",
    helperText: "Which legacy systems drive this modernization — names and roles only.",
    fieldType: "long_text",
    stageId: 3,
    version: V,
    layer: "L4",
    category: "operating_reality",
    requiredCondition: "if_org_MODERNIZATION",
    journeyApplicability: "BOTH",
    organizationContextApplicability: ["MODERNIZATION"],
    visibilityCondition: "if_org_MODERNIZATION",
    validation: { minLength: 5, maxLength: 2000 },
    mapsToOperatingModel: ["systems", "transition"],
    mapsToBlueprintSection: "integrations",
    riskSensitivity: "medium",
    evidenceRequirement: "recommended",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "target_systems_intent",
    label: "Target systems intent",
    helperText: "For a new build: which systems or tool categories you expect to need (intent only).",
    fieldType: "long_text",
    stageId: 3,
    version: V,
    layer: "L4",
    category: "operating_reality",
    requiredCondition: "if_journey_NEW",
    journeyApplicability: "NEW",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_NEW",
    validation: { minLength: 5, maxLength: 2000 },
    mapsToOperatingModel: ["systems", "target_state"],
    mapsToBlueprintSection: "integrations",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "important_records_data",
    label: "Important records / data",
    helperText: "What records or data types are critical (no sample secrets or personal data dumps).",
    fieldType: "long_text",
    stageId: 3,
    version: V,
    layer: "L5",
    category: "operating_reality",
    requiredCondition: "always",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { minLength: 10, maxLength: 2000 },
    mapsToOperatingModel: ["data"],
    mapsToBlueprintSection: "cybercrow",
    riskSensitivity: "high",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "review",
  },
  {
    fieldKey: "major_pain_points",
    label: "Major pain points",
    helperText: "What hurts most today — required for Transform journeys; optional for pure new builds.",
    fieldType: "long_text",
    stageId: 3,
    version: V,
    layer: "L8",
    category: "operating_reality",
    requiredCondition: "if_journey_TRANSFORM",
    journeyApplicability: "TRANSFORM",
    organizationContextApplicability: "ALL",
    visibilityCondition: "if_journey_TRANSFORM",
    validation: { minLength: 20, maxLength: 2000 },
    mapsToOperatingModel: ["current_state", "risks"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "medium",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "blocking_if_missing",
  },
  {
    fieldKey: "evidence_reference_note",
    label: "Evidence reference (optional)",
    helperText: "Text name or URL only — file uploads are not allowed in Discovery MVP.",
    fieldType: "url",
    stageId: 3,
    version: V,
    layer: "L9",
    category: "evidence_refs",
    requiredCondition: "never",
    journeyApplicability: "BOTH",
    organizationContextApplicability: "ALL",
    visibilityCondition: "always",
    validation: { maxLength: 500, refsOnly: true },
    mapsToOperatingModel: ["evidence"],
    mapsToBlueprintSection: "overview",
    riskSensitivity: "low",
    evidenceRequirement: "optional",
    clientVisible: true,
    operatorVisible: true,
    procrowReviewFlag: "none",
  },
] as const;

export function getDiscoveryMvpD3Catalog(): readonly DiscoveryMvpFieldDefinition[] {
  return DISCOVERY_MVP_D3_CATALOG;
}

export function getDiscoveryMvpD3FieldsByStage(
  stageId: 1 | 2 | 3,
): readonly DiscoveryMvpFieldDefinition[] {
  return DISCOVERY_MVP_D3_CATALOG.filter((f) => f.stageId === stageId);
}
