import type { DomainPackDefinition } from "../domain-types";

const pack = (
  key: string,
  displayName: string,
  description: string,
  specialistKeys: string[],
  deptKeys: string[],
): DomainPackDefinition => ({
  key,
  displayName,
  description,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  applicableIndustryKeys: [],
  specialistDomainKeys: specialistKeys,
  recommendedDepartmentKeys: deptKeys,
  entityPackKeys: ["core_operating"],
  capabilityKeys: [],
  workflowTemplateKeys: [],
  workPersonaKeys: [],
  jobFamilyKeys: ["operations"],
  permissionBundleRecommendationKeys: [],
  sareaPatternKeys: ["specialist_workspace"],
  cyberCrowPolicyPackKeys: ["baseline_identity_trust", "audit_and_evidence"],
  integrationPackKeys: ["google_workspace", "email_connector"],
  complianceOverlayKeys: ["data_privacy"],
  scaleBehavior: "Adapts department density with scale preset",
  topologyCompatibility: ["DEPARTMENTAL_HIERARCHY", "OUTCOME_PODS"],
  dependencies: [],
  conflicts: [],
  authoritative: false,
  grantsPermissions: false,
  provisionsTenant: false,
});

export const DOMAIN_PACK_CATALOG: readonly DomainPackDefinition[] = [
  {
    ...pack("bookkeeping_office_pack", "Bookkeeping office pack", "Small accounting office operating model.", ["accounting_and_bookkeeping"], ["finance_operations", "customer_service"]),
    applicableIndustryKeys: ["professional_services"],
    capabilityKeys: ["documents", "invoice_workflow", "crm"],
    workflowTemplateKeys: ["bookkeeping_month_close", "client_intake_and_qualification"],
    workPersonaKeys: ["client_bookkeeping_coordinator"],
  },
  {
    ...pack("esports_operations_pack", "Esports operations pack", "Tournament and team operations.", ["esports_organization", "gaming_and_esports"], ["operations", "creative", "technology"]),
    applicableIndustryKeys: ["technology_and_saas", "events_and_venues"],
    capabilityKeys: ["incident_management", "case_management"],
    workflowTemplateKeys: ["esports_tournament_operations", "release_readiness"],
    workPersonaKeys: ["esports_tournament_operations_coordinator", "live_game_operations_coordinator"],
  },
  {
    ...pack("legal_practice_pack", "Legal practice pack", "Matter intake and case coordination — advisory only.", ["legal_services"], ["legal", "compliance", "executive_office"]),
    applicableIndustryKeys: ["professional_services"],
    capabilityKeys: ["case_management", "documents", "contracts"],
    workflowTemplateKeys: ["matter_intake_and_conflict_check"],
    workPersonaKeys: ["legal_matter_intake_coordinator"],
    complianceOverlayKeys: ["legal_confidentiality", "data_privacy"],
  },
  {
    ...pack("logistics_fulfillment_pack", "Logistics fulfillment pack", "Warehouse and last-mile operations.", ["warehouse_and_fulfillment", "last_mile_delivery"], ["supply_chain", "operations", "field_operations"]),
    applicableIndustryKeys: ["logistics_and_fleet"],
    capabilityKeys: ["warehouse", "dispatch", "inventory"],
    workflowTemplateKeys: ["warehouse_fulfillment_cycle", "home_service_dispatch"],
    workPersonaKeys: ["warehouse_fulfillment_controller", "home_service_dispatch_coordinator"],
    integrationPackKeys: ["fleet_telematics", "mapping_geolocation"],
  },
] as const;
