import type { SpecialistDomainDefinition } from "../types";

function ext(
  key: string,
  displayName: string,
  description: string,
  industries: string[],
  caps: string[],
  workflows: string[],
  personas: string[],
  compliance: string[] = [],
): SpecialistDomainDefinition {
  return {
    key,
    displayName,
    description,
    status: "PLANNED",
    version: "1.0.0",
    provenance: "crow_core",
    applicableIndustryKeys: industries,
    recommendedCapabilityKeys: caps,
    workflowFamilyKeys: workflows,
    jobFamilyKeys: ["operations"],
    personaSuggestionKeys: personas,
    entitySuggestionKeys: [],
    recommendedSareaPatternKeys: ["specialist_workspace"],
    recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust", "audit_and_evidence"],
    complianceNotes: compliance,
  };
}

/** MODEL.2 — additional specialist domains for offices, practices and service operators. */
export const SPECIALIST_DOMAIN_EXTENDED_CATALOG: readonly SpecialistDomainDefinition[] = [
  ext("accounting_and_bookkeeping", "Accounting and bookkeeping", "Client bookkeeping coordination — not regulated audit certification.", ["professional_services"], ["documents", "invoice_workflow", "crm"], ["bookkeeping_month_close", "client_intake_and_qualification"], ["client_bookkeeping_coordinator"], ["Operational workflow only", "Not audit certification"]),
  ext("insurance_brokerage_operations", "Insurance brokerage operations", "Brokerage client service — not underwriting or claims unless implemented.", ["professional_services"], ["crm", "case_management", "contracts"], ["insurance_client_onboarding", "case_resolution"], ["insurance_client_service_coordinator"], ["Not underwriting", "Not claims processing unless implemented"]),
  ext("translation_and_localization", "Translation and localization", "Localization project delivery.", ["professional_services", "media_and_creative"], ["project_management", "documents"], ["translation_project_delivery"], ["localization_project_manager"]),
  ext("travel_and_tour_operations", "Travel and tour operations", "Travel booking and case handling.", ["hospitality_and_tourism"], ["crm", "case_management"], ["travel_booking_case", "service_booking_and_completion"], ["travel_operations_coordinator"]),
  ext("photography_and_content_studio", "Photography and content studio", "Studio shoot and delivery workflows.", ["media_and_creative"], ["project_management", "documents"], ["photography_project_delivery", "creative_asset_production"], ["studio_production_coordinator"]),
  ext("printing_and_signage", "Printing and signage", "Print job production.", ["retail_and_commerce", "media_and_creative"], ["work_orders", "inventory"], ["print_job_production"], ["print_production_controller"]),
  ext("talent_and_casting_agency", "Talent and casting agency", "Casting and talent engagement.", ["media_and_creative"], ["crm", "contracts"], ["talent_casting_and_engagement", "client_intake_and_qualification"], ["casting_and_talent_coordinator"]),
  ext("sports_club_operations", "Sports club operations", "Program enrollment and operations.", ["fitness_and_wellness", "events_and_venues"], ["crm", "customer_portal"], ["sports_program_enrollment", "member_enrollment"], ["sports_program_operations_lead"]),
  ext("esports_organization", "Esports organization", "Tournament and team operations.", ["technology_and_saas", "events_and_venues"], ["incident_management", "case_management"], ["esports_tournament_operations", "release_readiness"], ["esports_tournament_operations_coordinator"]),
  ext("coaching_and_consulting", "Coaching and consulting", "Engagement delivery.", ["professional_services"], ["project_management", "crm", "time_tracking"], ["consulting_engagement_delivery"], ["consulting_engagement_manager"]),
  ext("childcare_and_nursery_operations", "Childcare and nursery operations", "Enrollment and family coordination.", ["education_and_training"], ["crm", "case_management"], ["nursery_enrollment"], ["enrollment_and_family_coordinator"]),
  ext("veterinary_practice_operations", "Veterinary practice operations", "Practice administration — not diagnosis.", ["healthcare_operations"], ["case_management", "crm", "work_orders"], ["veterinary_visit_administration"], ["veterinary_practice_coordinator"], ["Administration only", "No diagnosis"]),
  ext("dental_practice_operations", "Dental practice operations", "Clinic scheduling admin — not clinical decisions.", ["healthcare_operations"], ["crm", "customer_service"], ["clinic_appointment_administration"], ["clinic_operations_coordinator"], ["Administration only"]),
  ext("clinic_administration", "Clinic administration", "Clinic ops scheduling — not clinical records.", ["healthcare_operations"], ["workforce_directory", "case_management"], ["clinic_appointment_administration", "booking_to_service_completion"], ["clinic_operations_coordinator"], ["No clinical decision support"]),
  ext("pharmacy_operations", "Pharmacy operations", "Stock and approval admin — not prescribing.", ["healthcare_operations", "retail_and_commerce"], ["inventory", "procurement"], ["pharmacy_stock_control"], ["pharmacy_inventory_controller"], ["No prescribing", "No medical advice"]),
  ext("automotive_dealership", "Automotive dealership", "Vehicle sales handover.", ["retail_and_commerce"], ["crm", "inventory", "contracts"], ["vehicle_sales_handover"], ["vehicle_handover_coordinator"]),
  ext("vehicle_rental", "Vehicle rental", "Fleet rental turnaround.", ["logistics_and_fleet"], ["fleet", "asset_registry", "crm"], ["vehicle_rental_turnaround"], ["rental_fleet_turnaround_controller"]),
  ext("home_services", "Home services", "Home service dispatch.", ["professional_services", "property_and_facilities"], ["field_service", "work_orders", "crm"], ["home_service_dispatch"], ["home_service_dispatch_coordinator"]),
  ext("pest_control_operations", "Pest control operations", "Route-based service delivery.", ["property_and_facilities"], ["field_service", "dispatch"], ["pest_control_service"], ["pest_control_route_planner"]),
  ext("landscaping_operations", "Landscaping operations", "Maintenance cycle management.", ["property_and_facilities", "construction_and_epc"], ["work_orders", "field_service"], ["landscaping_maintenance_cycle"], ["landscape_maintenance_supervisor"]),
  ext("laundry_and_cleaning_services", "Laundry and cleaning services", "Commercial cleaning contracts.", ["property_and_facilities"], ["work_orders", "contracts"], ["commercial_cleaning_contract"], ["commercial_cleaning_quality_controller"]),
  ext("catering_and_cloud_kitchen", "Catering and cloud kitchen", "Catering order fulfillment.", ["food_service"], ["inventory", "work_orders", "delivery_management"], ["catering_order_delivery"], ["catering_fulfillment_coordinator"]),
  ext("bakery_and_food_production", "Bakery and food production", "Production batch workflows.", ["food_service", "manufacturing_and_industrial"], ["inventory", "work_orders", "quality_management"], ["work_order_execution"], ["quality_reviewer"]),
  ext("wholesale_and_distribution", "Wholesale and distribution", "Wholesale order fulfillment.", ["retail_and_commerce", "logistics_and_fleet"], ["inventory", "procurement", "warehouse"], ["wholesale_order_fulfillment"], ["warehouse_fulfillment_controller"]),
  ext("import_export_trading", "Import export trading", "Trade document coordination.", ["logistics_and_fleet", "professional_services"], ["documents", "procurement", "case_management"], ["import_export_document_review"], ["import_documentation_coordinator"]),
  ext("customs_brokerage", "Customs brokerage", "Customs case coordination.", ["logistics_and_fleet"], ["case_management", "documents"], ["customs_submission_coordination"], ["customs_case_coordinator"]),
  ext("warehouse_and_fulfillment", "Warehouse and fulfillment", "Fulfillment cycle operations.", ["logistics_and_fleet", "retail_and_commerce"], ["warehouse", "inventory", "dispatch"], ["warehouse_fulfillment_cycle"], ["warehouse_fulfillment_controller"]),
  ext("last_mile_delivery", "Last mile delivery", "Last-mile dispatch and proof.", ["logistics_and_fleet", "food_service"], ["dispatch", "delivery_management"], ["dispatch_and_delivery"], ["home_service_dispatch_coordinator"]),
  ext("interior_design_and_fitout", "Interior design and fitout", "Fit-out project delivery.", ["construction_and_epc", "property_and_facilities"], ["project_management", "procurement"], ["property_fitout_project"], ["fit_out_project_coordinator"]),
  ext("wedding_and_social_event_planning", "Wedding and social event planning", "Event production coordination.", ["events_and_venues"], ["project_management", "crm", "vendor_management"], ["wedding_event_delivery"], ["wedding_production_coordinator"]),
  ext("nonprofit_program_delivery", "Nonprofit program delivery", "Program case management.", ["nonprofit_and_associations"], ["case_management", "crm"], ["nonprofit_program_case"], ["nonprofit_program_case_lead"]),
] as const;
