import type { IndustryArchetype, OrganizationalOverlay } from "./types";

const archetype = (
  key: string,
  displayName: string,
  model: string,
  status: IndustryArchetype["status"] = "PLANNED",
): IndustryArchetype => ({
  key,
  displayName,
  description: `${displayName} industry archetype — advisory recommendations only.`,
  status,
  version: "1.0.0",
  provenance: "crow_core",
  commonOperatingModel: model,
  commonDepartments: [],
  recommendedCapabilityKeys: [],
  commonWorkflowPatternKeys: [],
  commonJobFamilyKeys: [],
  commonRoleArchetypeKeys: [],
  recommendedSareaPatternKeys: [],
  recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust"],
  commonIntegrationNeeds: [],
  discoveryQuestionHints: [],
});

export const INDUSTRY_ARCHETYPE_CATALOG: readonly IndustryArchetype[] = [
  {
    ...archetype("logistics_and_fleet", "Logistics and fleet", "Hub-and-spoke dispatch with fleet utilization.", "PARTIAL"),
    provenance: "legacy",
    commonDepartments: ["operations", "dispatch", "warehouse", "fleet", "customer_service"],
    recommendedCapabilityKeys: ["dispatch", "fleet", "warehouse", "shipment_tracking", "delivery_management", "crm", "work_orders"],
    commonWorkflowPatternKeys: ["dispatch_and_delivery", "work_order_execution", "case_resolution"],
    commonJobFamilyKeys: ["operations", "supply_chain", "field_operations"],
    commonRoleArchetypeKeys: ["dispatcher", "driver", "supervisor", "coordinator", "customer"],
    recommendedSareaPatternKeys: ["dispatch_console", "field_task_mobile", "operations_control_board"],
    recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust", "field_device_trust", "branch_access_control"],
    commonIntegrationNeeds: ["gps_tracking", "erp_connector"],
    discoveryQuestionHints: ["branch_count", "fleet_size", "delivery_sla"],
  },
  {
    ...archetype("construction_and_epc", "Construction and EPC", "Project-based delivery with site crews."),
    commonDepartments: ["projects", "engineering", "procurement", "hse", "finance"],
    recommendedCapabilityKeys: ["project_management", "work_orders", "procurement", "safety_management", "time_tracking", "documents"],
    commonWorkflowPatternKeys: ["project_delivery", "work_order_execution", "request_and_approval", "inspection_to_corrective_action"],
    commonJobFamilyKeys: ["project_delivery", "engineering", "field_operations", "procurement"],
    commonRoleArchetypeKeys: ["department_manager", "supervisor", "technician", "procurement_specialist", "approver"],
    recommendedSareaPatternKeys: ["project_workspace", "field_task_mobile", "manager_work_queue"],
    recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust", "contractor_access", "high_risk_workflow_approval"],
    discoveryQuestionHints: ["project_count", "subcontractor_usage", "site_locations"],
  },
  {
    ...archetype("retail_and_commerce", "Retail and commerce", "Multi-branch retail with inventory and sales."),
    commonDepartments: ["stores", "inventory", "procurement", "marketing", "customer_service"],
    recommendedCapabilityKeys: ["inventory", "crm", "sales_pipeline", "procurement", "customer_portal", "returns"],
    commonWorkflowPatternKeys: ["procure_to_receive", "case_resolution", "customer_onboarding"],
    commonJobFamilyKeys: ["operations", "sales_and_commercial", "supply_chain"],
    commonRoleArchetypeKeys: ["supervisor", "sales_representative", "coordinator", "customer"],
    recommendedSareaPatternKeys: ["operations_control_board", "specialist_workspace", "customer_portal"],
    discoveryQuestionHints: ["store_count", "ecommerce_channel", "loyalty_program"],
  },
  {
    ...archetype("manufacturing_and_industrial", "Manufacturing and industrial", "Production with maintenance and quality."),
    commonDepartments: ["production", "maintenance", "quality", "supply_chain", "engineering"],
    recommendedCapabilityKeys: ["inventory", "maintenance", "quality_management", "work_orders", "procurement", "asset_registry"],
    commonWorkflowPatternKeys: ["work_order_execution", "inspection_to_corrective_action", "procure_to_receive"],
    commonJobFamilyKeys: ["engineering", "field_operations", "quality_and_safety", "supply_chain"],
    commonRoleArchetypeKeys: ["supervisor", "technician", "specialist", "procurement_specialist"],
    recommendedSareaPatternKeys: ["technician_workbench", "operations_control_board"],
    discoveryQuestionHints: ["production_lines", "preventive_maintenance", "regulatory_needs"],
  },
  {
    ...archetype("professional_services", "Professional services", "Engagement-based delivery and billing."),
    commonDepartments: ["delivery", "sales", "finance", "hr"],
    recommendedCapabilityKeys: ["project_management", "time_tracking", "crm", "contracts", "invoice_workflow", "documents"],
    commonWorkflowPatternKeys: ["project_delivery", "contract_review_and_approval", "request_and_approval"],
    commonJobFamilyKeys: ["project_delivery", "sales_and_commercial", "finance"],
    commonRoleArchetypeKeys: ["department_manager", "specialist", "sales_representative", "finance_specialist"],
    recommendedSareaPatternKeys: ["project_workspace", "specialist_workspace", "analytics_workspace"],
    discoveryQuestionHints: ["billable_model", "client_count", "approval_complexity"],
  },
  {
    ...archetype("property_and_facilities", "Property and facilities", "Property operations and tenant services."),
    commonDepartments: ["facilities", "maintenance", "leasing", "security"],
    recommendedCapabilityKeys: ["property_operations", "facilities", "maintenance", "work_orders", "inspections", "asset_registry"],
    commonWorkflowPatternKeys: ["work_order_execution", "inspection_to_corrective_action", "request_and_approval"],
    commonJobFamilyKeys: ["facilities", "field_operations"],
    commonRoleArchetypeKeys: ["supervisor", "technician", "coordinator", "customer"],
    recommendedSareaPatternKeys: ["manager_work_queue", "technician_workbench", "customer_portal"],
    discoveryQuestionHints: ["property_count", "tenant_portal", "maintenance_sla"],
  },
  {
    ...archetype("hospitality_and_tourism", "Hospitality and tourism", "Guest services and reservations."),
    commonDepartments: ["front_office", "housekeeping", "fnb", "sales"],
    recommendedCapabilityKeys: ["crm", "customer_service", "work_orders", "task_management"],
    commonWorkflowPatternKeys: ["booking_to_service_completion", "case_resolution", "request_and_approval"],
    commonJobFamilyKeys: ["hospitality", "customer_service", "operations"],
    commonRoleArchetypeKeys: ["coordinator", "supervisor", "customer", "specialist"],
    recommendedSareaPatternKeys: ["operations_control_board", "customer_portal", "simple_frontline_home"],
    discoveryQuestionHints: ["property_units", "booking_channels", "seasonality"],
  },
  {
    ...archetype("healthcare_operations", "Healthcare operations", "Organizational ops — not clinical records.", "PLANNED"),
    description:
      "Healthcare operations archetype — scheduling, workforce, and facilities only. No medical-record or clinical-decision claims.",
    commonDepartments: ["operations", "scheduling", "facilities", "hr", "patient_services"],
    recommendedCapabilityKeys: ["workforce_directory", "employee_lifecycle", "facilities", "incident_management", "case_management", "documents"],
    commonWorkflowPatternKeys: ["request_and_approval", "incident_to_resolution", "booking_to_service_completion"],
    commonJobFamilyKeys: ["healthcare_operations", "facilities", "human_resources"],
    commonRoleArchetypeKeys: ["coordinator", "supervisor", "hr_specialist", "security_administrator"],
    recommendedSareaPatternKeys: ["operations_control_board", "case_inbox", "compliance_cockpit"],
    recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust", "sensitive_hr_data", "audit_and_evidence"],
    discoveryQuestionHints: ["clinic_sites", "workforce_type", "regulatory_needs"],
  },
  {
    ...archetype("education_and_training", "Education and training", "Programs, cohorts, and administration."),
    commonDepartments: ["academics", "admissions", "finance", "facilities"],
    recommendedCapabilityKeys: ["learning", "crm", "documents", "case_management", "internal_requests"],
    commonWorkflowPatternKeys: ["member_enrollment", "request_and_approval", "booking_to_service_completion"],
    commonJobFamilyKeys: ["education_and_training", "customer_service"],
    commonRoleArchetypeKeys: ["coordinator", "specialist", "member", "approver"],
    recommendedSareaPatternKeys: ["guided_onboarding", "member_portal", "specialist_workspace"],
    discoveryQuestionHints: ["program_count", "learner_portal", "accreditation"],
  },
  {
    ...archetype("events_and_venues", "Events and venues", "Event planning and venue operations."),
    commonDepartments: ["events", "operations", "sales", "facilities"],
    recommendedCapabilityKeys: ["project_management", "crm", "work_orders", "vendor_management", "task_management"],
    commonWorkflowPatternKeys: ["project_delivery", "booking_to_service_completion", "procure_to_receive"],
    commonJobFamilyKeys: ["operations", "sales_and_commercial", "creative_and_media"],
    commonRoleArchetypeKeys: ["coordinator", "supervisor", "sales_representative", "supplier"],
    recommendedSareaPatternKeys: ["project_workspace", "operations_control_board"],
    discoveryQuestionHints: ["venue_count", "event_frequency", "vendor_heavy"],
  },
  {
    ...archetype("media_and_creative", "Media and creative", "Production pipelines and client delivery."),
    commonDepartments: ["production", "creative", "sales", "finance"],
    recommendedCapabilityKeys: ["project_management", "documents", "crm", "contracts", "time_tracking"],
    commonWorkflowPatternKeys: ["project_delivery", "contract_review_and_approval", "request_and_approval"],
    commonJobFamilyKeys: ["creative_and_media", "project_delivery"],
    commonRoleArchetypeKeys: ["specialist", "department_manager", "customer"],
    recommendedSareaPatternKeys: ["project_workspace", "specialist_workspace"],
    discoveryQuestionHints: ["production_type", "client_approval_cycles"],
  },
  {
    ...archetype("fitness_and_wellness", "Fitness and wellness", "Membership and session operations."),
    commonDepartments: ["membership", "coaching", "facilities"],
    recommendedCapabilityKeys: ["crm", "customer_portal", "work_orders", "task_management"],
    commonWorkflowPatternKeys: ["member_enrollment", "booking_to_service_completion"],
    commonJobFamilyKeys: ["hospitality", "customer_service"],
    commonRoleArchetypeKeys: ["member", "coordinator", "supervisor"],
    recommendedSareaPatternKeys: ["member_portal", "simple_frontline_home"],
    discoveryQuestionHints: ["location_count", "membership_model"],
  },
  {
    ...archetype("technology_and_saas", "Technology and SaaS", "Product-led with customer success."),
    commonDepartments: ["engineering", "customer_success", "sales", "finance"],
    recommendedCapabilityKeys: ["crm", "case_management", "subscriptions", "documents", "analytics"],
    commonWorkflowPatternKeys: ["customer_onboarding", "case_resolution", "incident_to_resolution"],
    commonJobFamilyKeys: ["technology", "customer_service", "sales_and_commercial"],
    commonRoleArchetypeKeys: ["specialist", "tenant_administrator", "customer", "security_administrator"],
    recommendedSareaPatternKeys: ["specialist_workspace", "customer_portal", "security_posture_console"],
    discoveryQuestionHints: ["subscription_model", "sla_tiers", "integration_needs"],
  },
  {
    ...archetype("food_service", "Food service", "Kitchen, delivery, and outlet operations."),
    commonDepartments: ["kitchen", "delivery", "procurement", "hr"],
    recommendedCapabilityKeys: ["inventory", "procurement", "delivery_management", "work_orders", "attendance"],
    commonWorkflowPatternKeys: ["dispatch_and_delivery", "procure_to_receive", "work_order_execution"],
    commonJobFamilyKeys: ["operations", "supply_chain", "field_operations"],
    commonRoleArchetypeKeys: ["supervisor", "driver", "coordinator", "procurement_specialist"],
    recommendedSareaPatternKeys: ["operations_control_board", "field_task_mobile"],
    discoveryQuestionHints: ["outlet_count", "delivery_radius"],
  },
  {
    ...archetype("nonprofit_and_associations", "Nonprofit and associations", "Programs, donors, and volunteers."),
    commonDepartments: ["programs", "fundraising", "membership", "finance"],
    recommendedCapabilityKeys: ["crm", "documents", "case_management", "budget_requests", "internal_requests"],
    commonWorkflowPatternKeys: ["member_enrollment", "request_and_approval", "case_resolution"],
    commonJobFamilyKeys: ["governance_and_risk", "customer_service"],
    commonRoleArchetypeKeys: ["coordinator", "member", "approver", "auditor"],
    recommendedSareaPatternKeys: ["member_portal", "compliance_cockpit"],
    discoveryQuestionHints: ["donor_tracking", "volunteer_program", "grant_reporting"],
  },
  {
    ...archetype("holding_group", "Holding group", "Multi-entity governance with shared services."),
    commonDepartments: ["group_finance", "shared_services", "governance", "hr"],
    recommendedCapabilityKeys: ["organization_structure", "financial_reporting", "policy_management", "audit", "analytics"],
    commonWorkflowPatternKeys: ["request_and_approval", "contract_review_and_approval"],
    commonJobFamilyKeys: ["executive_leadership", "finance", "governance_and_risk"],
    commonRoleArchetypeKeys: ["executive", "finance_specialist", "auditor", "tenant_administrator"],
    recommendedSareaPatternKeys: ["executive_command_center", "analytics_workspace", "compliance_cockpit"],
    recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust", "privileged_access", "audit_and_evidence", "data_export_control"],
    discoveryQuestionHints: ["entity_count", "shared_services", "consolidated_reporting"],
  },
] as const;

export const ORGANIZATIONAL_OVERLAY_CATALOG: readonly OrganizationalOverlay[] = [
  { key: "startup", displayName: "Startup", description: "Lean team, minimal departments.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["reduce_department_depth", "prefer_self_service"] },
  { key: "small_business", displayName: "Small business", description: "Single or few locations.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["consolidate_roles", "simplify_approvals"] },
  { key: "mid_market", displayName: "Mid market", description: "Growing multi-team organization.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["add_department_managers"] },
  { key: "enterprise", displayName: "Enterprise", description: "Complex hierarchy and governance.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["add_audit", "add_executive_read", "segregation_of_duties"] },
  { key: "multi_branch", displayName: "Multi branch", description: "Multiple operating branches.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["branch_access_control", "branch_scoped_permissions"] },
  { key: "holding_group", displayName: "Holding group overlay", description: "Parent entity over subsidiaries.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["consolidated_reporting", "entity_separation"] },
  { key: "franchise", displayName: "Franchise", description: "Franchisee-operated units.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["franchisee_portal", "brand_standards"] },
  { key: "project_based", displayName: "Project based", description: "Revenue primarily from projects.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["project_delivery", "time_tracking"] },
  { key: "field_workforce", displayName: "Field workforce", description: "Majority mobile workforce.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["field_task_mobile", "field_device_trust"] },
  { key: "highly_regulated", displayName: "Highly regulated", description: "Strong compliance requirements.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["audit_and_evidence", "compliance_cockpit", "high_risk_workflow_approval"] },
  { key: "seasonal_workforce", displayName: "Seasonal workforce", description: "Seasonal hiring patterns.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["contractor_management", "simplified_onboarding"] },
  { key: "customer_membership", displayName: "Customer membership", description: "Membership-based customers.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["member_portal", "member_enrollment"] },
  { key: "vendor_heavy", displayName: "Vendor heavy", description: "High third-party dependency.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["vendor_access", "supplier_portal", "procure_to_receive"] },
  { key: "asset_heavy", displayName: "Asset heavy", description: "Capital-intensive assets.", status: "PLANNED", version: "1.0.0", provenance: "crow_core", adjustsRecommendations: ["asset_registry", "preventive_maintenance"] },
] as const;
