import type { RoleArchetype, JobFamily, JobDefinition } from "./types";

const role = (
  key: string,
  displayName: string,
  summary: string,
): RoleArchetype => ({
  key,
  displayName,
  description: summary,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  responsibilitySummary: summary,
  suggestedJobFamilyKeys: [],
  suggestedPermissionBundleKeys: [],
  suggestedSareaPatternKeys: [],
  grantsPermissions: false,
});

export const ROLE_ARCHETYPE_CATALOG: readonly RoleArchetype[] = [
  { ...role("executive", "Executive", "Strategic oversight and executive approvals."), suggestedPermissionBundleKeys: ["tenant_executive_read"], suggestedSareaPatternKeys: ["executive_command_center"] },
  { ...role("tenant_administrator", "Tenant administrator", "Tenant configuration and user administration."), suggestedPermissionBundleKeys: ["tenant_operations_admin"], suggestedSareaPatternKeys: ["operations_control_board"] },
  { ...role("department_manager", "Department manager", "Department operations and approvals."), suggestedPermissionBundleKeys: ["department_manager", "workflow_approver"], suggestedSareaPatternKeys: ["manager_work_queue"] },
  { ...role("approver", "Approver", "Approval authority within assigned scope."), suggestedPermissionBundleKeys: ["workflow_approver"] },
  { ...role("supervisor", "Supervisor", "Team supervision and task assignment."), suggestedPermissionBundleKeys: ["team_supervisor"], suggestedSareaPatternKeys: ["manager_work_queue"] },
  { ...role("specialist", "Specialist", "Domain specialist execution."), suggestedPermissionBundleKeys: ["department_operator"], suggestedSareaPatternKeys: ["specialist_workspace"] },
  { ...role("coordinator", "Coordinator", "Cross-functional coordination."), suggestedPermissionBundleKeys: ["department_operator"], suggestedSareaPatternKeys: ["operations_control_board"] },
  { ...role("analyst", "Analyst", "Analysis and reporting."), suggestedPermissionBundleKeys: ["department_operator"], suggestedSareaPatternKeys: ["analytics_workspace"] },
  { ...role("dispatcher", "Dispatcher", "Dispatch and routing."), suggestedPermissionBundleKeys: ["department_operator", "field_execution"], suggestedSareaPatternKeys: ["dispatch_console"] },
  { ...role("field_worker", "Field worker", "Mobile field execution."), suggestedPermissionBundleKeys: ["field_execution"], suggestedSareaPatternKeys: ["field_task_mobile", "simple_frontline_home"] },
  { ...role("technician", "Technician", "Technical work execution."), suggestedPermissionBundleKeys: ["field_execution"], suggestedSareaPatternKeys: ["technician_workbench"] },
  { ...role("driver", "Driver", "Transport execution."), suggestedPermissionBundleKeys: ["field_execution"], suggestedSareaPatternKeys: ["field_task_mobile"] },
  { ...role("sales_representative", "Sales representative", "Commercial outreach and pipeline."), suggestedPermissionBundleKeys: ["department_operator"], suggestedSareaPatternKeys: ["specialist_workspace"] },
  { ...role("hr_specialist", "HR specialist", "HR programs and employee lifecycle."), suggestedPermissionBundleKeys: ["department_operator"], suggestedSareaPatternKeys: ["specialist_workspace"] },
  { ...role("finance_specialist", "Finance specialist", "Finance operations support."), suggestedPermissionBundleKeys: ["department_operator", "financial_approver"], suggestedSareaPatternKeys: ["specialist_workspace"] },
  { ...role("procurement_specialist", "Procurement specialist", "Procurement operations."), suggestedPermissionBundleKeys: ["department_operator"], suggestedSareaPatternKeys: ["specialist_workspace"] },
  { ...role("security_administrator", "Security administrator", "Tenant security posture administration."), suggestedPermissionBundleKeys: ["security_tenant_admin"], suggestedSareaPatternKeys: ["security_posture_console"] },
  { ...role("auditor", "Auditor", "Read-only audit access."), suggestedPermissionBundleKeys: ["auditor_read_only"], suggestedSareaPatternKeys: ["compliance_cockpit"] },
  { ...role("contractor", "Contractor", "Limited external contractor access."), suggestedPermissionBundleKeys: ["external_contractor"], suggestedSareaPatternKeys: ["contractor_portal"] },
  { ...role("supplier", "Supplier", "Supplier portal access."), suggestedPermissionBundleKeys: ["external_supplier"], suggestedSareaPatternKeys: ["supplier_portal"] },
  { ...role("customer", "Customer", "Customer portal access."), suggestedPermissionBundleKeys: ["external_customer"], suggestedSareaPatternKeys: ["customer_portal"] },
  { ...role("member", "Member", "Membership portal access."), suggestedPermissionBundleKeys: ["external_customer"], suggestedSareaPatternKeys: ["member_portal"] },
  { ...role("guest", "Guest", "Minimal guest access."), suggestedPermissionBundleKeys: ["self_service"], suggestedSareaPatternKeys: ["simple_frontline_home"] },
] as const;

const family = (key: string, displayName: string, domain: string): JobFamily => ({
  key,
  displayName,
  description: `${displayName} job family.`,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  domain,
  exampleTitles: [],
  recommendedRoleArchetypeKeys: [],
});

export const JOB_FAMILY_CATALOG: readonly JobFamily[] = [
  { ...family("executive_leadership", "Executive leadership", "leadership"), recommendedRoleArchetypeKeys: ["executive"], exampleTitles: ["CEO", "Managing Director"] },
  { ...family("operations", "Operations", "operations"), recommendedRoleArchetypeKeys: ["coordinator", "supervisor", "dispatcher"], exampleTitles: ["Operations Manager", "Dispatcher"] },
  { ...family("human_resources", "Human resources", "hr"), recommendedRoleArchetypeKeys: ["hr_specialist"], exampleTitles: ["HR Specialist", "HR Manager"] },
  { ...family("finance", "Finance", "finance"), recommendedRoleArchetypeKeys: ["finance_specialist", "approver"], exampleTitles: ["Finance Officer", "Controller"] },
  { ...family("sales_and_commercial", "Sales and commercial", "commercial"), recommendedRoleArchetypeKeys: ["sales_representative"], exampleTitles: ["Account Executive"] },
  { ...family("procurement", "Procurement", "procurement"), recommendedRoleArchetypeKeys: ["procurement_specialist"], exampleTitles: ["Buyer", "Procurement Manager"] },
  { ...family("supply_chain", "Supply chain", "supply_chain"), recommendedRoleArchetypeKeys: ["coordinator", "dispatcher"], exampleTitles: ["Supply Chain Analyst"] },
  { ...family("project_delivery", "Project delivery", "projects"), recommendedRoleArchetypeKeys: ["department_manager", "specialist"], exampleTitles: ["Project Manager", "Project Engineer"] },
  { ...family("engineering", "Engineering", "engineering"), recommendedRoleArchetypeKeys: ["specialist", "technician"], exampleTitles: ["Engineer", "Site Engineer"] },
  { ...family("field_operations", "Field operations", "field"), recommendedRoleArchetypeKeys: ["field_worker", "technician", "driver"], exampleTitles: ["Field Technician", "Driver"] },
  { ...family("customer_service", "Customer service", "service"), recommendedRoleArchetypeKeys: ["specialist", "coordinator"], exampleTitles: ["Support Agent"] },
  { ...family("technology", "Technology", "it"), recommendedRoleArchetypeKeys: ["specialist", "tenant_administrator"], exampleTitles: ["IT Administrator"] },
  { ...family("cybersecurity", "Cybersecurity", "security"), recommendedRoleArchetypeKeys: ["security_administrator"], exampleTitles: ["Security Administrator"] },
  { ...family("governance_and_risk", "Governance and risk", "governance"), recommendedRoleArchetypeKeys: ["auditor", "approver"], exampleTitles: ["Compliance Officer"] },
  { ...family("quality_and_safety", "Quality and safety", "quality"), recommendedRoleArchetypeKeys: ["specialist", "supervisor"], exampleTitles: ["QHSE Officer"] },
  { ...family("facilities", "Facilities", "facilities"), recommendedRoleArchetypeKeys: ["supervisor", "technician"], exampleTitles: ["Facilities Manager"] },
  { ...family("creative_and_media", "Creative and media", "creative"), recommendedRoleArchetypeKeys: ["specialist"], exampleTitles: ["Producer", "Designer"] },
  { ...family("education_and_training", "Education and training", "education"), recommendedRoleArchetypeKeys: ["specialist", "coordinator"], exampleTitles: ["Trainer", "Academic Coordinator"] },
  { ...family("healthcare_operations", "Healthcare operations", "healthcare"), recommendedRoleArchetypeKeys: ["coordinator", "supervisor"], exampleTitles: ["Clinic Coordinator", "Operations Manager"] },
  { ...family("hospitality", "Hospitality", "hospitality"), recommendedRoleArchetypeKeys: ["supervisor", "coordinator"], exampleTitles: ["Front Office Manager"] },
] as const;

export const JOB_DEFINITION_SAMPLES: readonly JobDefinition[] = [
  {
    key: "operations_manager",
    displayName: "Operations Manager",
    description: "Organizational operations leadership — advisory job definition.",
    status: "PLANNED",
    version: "1.0.0",
    provenance: "crow_core",
    jobFamilyKey: "operations",
    recommendedRoleArchetypeKeys: ["department_manager", "supervisor"],
    seniority: "manager",
    responsibilities: ["Team scheduling", "Operational KPIs", "Escalation handling"],
    workflowParticipation: ["request_and_approval", "dispatch_and_delivery"],
    recommendedSareaPatternKey: "operations_control_board",
    grantsPermissions: false,
  },
  {
    key: "dispatcher",
    displayName: "Dispatcher",
    description: "Dispatch coordination — title does not grant permissions.",
    status: "PLANNED",
    version: "1.0.0",
    provenance: "crow_core",
    jobFamilyKey: "operations",
    recommendedRoleArchetypeKeys: ["dispatcher", "coordinator"],
    responsibilities: ["Assign routes", "Monitor exceptions"],
    workflowParticipation: ["dispatch_and_delivery"],
    recommendedSareaPatternKey: "dispatch_console",
    grantsPermissions: false,
  },
] as const;
