import type { SareaExperiencePattern } from "./types";

const pattern = (
  key: string,
  displayName: string,
  density: SareaExperiencePattern["navigationDensity"],
  mobile: SareaExperiencePattern["mobileSuitability"],
): SareaExperiencePattern => ({
  key,
  displayName,
  description: `${displayName} — presentation pattern only.`,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  targetRoleArchetypeKeys: [],
  navigationDensity: density,
  primaryWidgets: [],
  primaryActions: [],
  mobileSuitability: mobile,
  informationComplexity: "moderate",
  alertStrategy: "contextual_banners",
  accessibilityNotes: ["keyboard_navigation", "contrast_compliant"],
  grantsPermissions: false,
});

export const SAREA_EXPERIENCE_PATTERN_CATALOG: readonly SareaExperiencePattern[] = [
  { ...pattern("executive_command_center", "Executive command center", "dense", "medium"), targetRoleArchetypeKeys: ["executive"], primaryWidgets: ["kpi_summary", "risk_radar"], informationComplexity: "complex" },
  { ...pattern("operations_control_board", "Operations control board", "dense", "medium"), targetRoleArchetypeKeys: ["tenant_administrator", "coordinator"], primaryWidgets: ["queue_health", "sla_tracker"] },
  { ...pattern("manager_work_queue", "Manager work queue", "balanced", "medium"), targetRoleArchetypeKeys: ["department_manager", "supervisor"], primaryWidgets: ["approval_queue", "team_load"] },
  { ...pattern("specialist_workspace", "Specialist workspace", "balanced", "medium"), targetRoleArchetypeKeys: ["specialist", "analyst"], primaryWidgets: ["task_list", "record_detail"] },
  { ...pattern("case_inbox", "Case inbox", "balanced", "medium"), targetRoleArchetypeKeys: ["specialist", "coordinator"], primaryWidgets: ["case_list", "sla_timer"] },
  { ...pattern("project_workspace", "Project workspace", "balanced", "low"), targetRoleArchetypeKeys: ["department_manager", "specialist"], primaryWidgets: ["gantt", "milestone_tracker"] },
  { ...pattern("dispatch_console", "Dispatch console", "dense", "medium"), targetRoleArchetypeKeys: ["dispatcher"], primaryWidgets: ["map_board", "assignment_grid"], status: "PARTIAL", provenance: "legacy" },
  { ...pattern("field_task_mobile", "Field task mobile", "minimal", "high"), targetRoleArchetypeKeys: ["field_worker", "driver"], primaryWidgets: ["next_task", "proof_capture"], informationComplexity: "simple" },
  { ...pattern("technician_workbench", "Technician workbench", "balanced", "high"), targetRoleArchetypeKeys: ["technician"], primaryWidgets: ["work_order_detail", "parts_lookup"] },
  { ...pattern("customer_portal", "Customer portal", "minimal", "high"), targetRoleArchetypeKeys: ["customer"], primaryWidgets: ["request_status", "documents"], informationComplexity: "simple" },
  { ...pattern("supplier_portal", "Supplier portal", "minimal", "medium"), targetRoleArchetypeKeys: ["supplier"], primaryWidgets: ["po_inbox", "shipment_updates"] },
  { ...pattern("contractor_portal", "Contractor portal", "minimal", "high"), targetRoleArchetypeKeys: ["contractor"], primaryWidgets: ["assigned_jobs", "timesheet"] },
  { ...pattern("member_portal", "Member portal", "minimal", "high"), targetRoleArchetypeKeys: ["member"], primaryWidgets: ["membership_status", "bookings"] },
  { ...pattern("compliance_cockpit", "Compliance cockpit", "dense", "low"), targetRoleArchetypeKeys: ["auditor", "security_administrator"], primaryWidgets: ["control_status", "evidence_gaps"] },
  { ...pattern("security_posture_console", "Security posture console", "dense", "low"), targetRoleArchetypeKeys: ["security_administrator"], primaryWidgets: ["trust_signals", "policy_coverage"] },
  { ...pattern("analytics_workspace", "Analytics workspace", "dense", "medium"), targetRoleArchetypeKeys: ["analyst", "executive"], primaryWidgets: ["dashboards", "drilldowns"], informationComplexity: "complex" },
  { ...pattern("guided_onboarding", "Guided onboarding", "minimal", "high"), targetRoleArchetypeKeys: ["customer", "member"], primaryWidgets: ["step_wizard", "checklist"], informationComplexity: "simple" },
  { ...pattern("simple_frontline_home", "Simple frontline home", "minimal", "high"), targetRoleArchetypeKeys: ["field_worker", "guest"], primaryWidgets: ["today_tasks", "alerts"], informationComplexity: "simple" },
] as const;
