import type { WorkflowPattern } from "./types";

const wf = (
  key: string,
  displayName: string,
  description: string,
  status: WorkflowPattern["status"] = "PLANNED",
): WorkflowPattern => ({
  key,
  displayName,
  description,
  status,
  version: "1.0.0",
  provenance: "crow_core",
  primitives: ["submit", "review", "approve"],
  actors: ["requester", "reviewer"],
  states: ["draft", "submitted", "approved", "closed"],
  transitions: ["submit", "approve", "close"],
  requiredPermissionBundleKeys: ["self_service", "workflow_approver"],
  optionalApprovalSteps: [],
  evidenceRequirements: [],
  escalationPoints: [],
  auditEvents: ["workflow.state_changed"],
  sareaPresentationHints: ["manager_work_queue"],
  cyberCrowTrustChecks: ["baseline_identity_trust"],
  dependencies: [],
  conflicts: [],
});

export const WORKFLOW_PRIMITIVES = [
  "submit",
  "review",
  "approve",
  "reject",
  "return_for_revision",
  "assign",
  "schedule",
  "dispatch",
  "accept",
  "start",
  "pause",
  "complete",
  "inspect",
  "verify",
  "escalate",
  "sign_off",
  "invoice",
  "close",
  "cancel",
  "archive",
] as const;

export const WORKFLOW_PATTERN_CATALOG: readonly WorkflowPattern[] = [
  {
    ...wf("request_and_approval", "Request and approval", "Generic submit-review-approve pattern."),
    primitives: ["submit", "review", "approve", "reject", "return_for_revision"],
    actors: ["requester", "approver", "auditor"],
    states: ["draft", "submitted", "in_review", "approved", "rejected", "closed"],
    transitions: ["submit", "approve", "reject", "return_for_revision", "close"],
    requiredPermissionBundleKeys: ["self_service", "workflow_approver"],
    cyberCrowTrustChecks: ["high_risk_workflow_approval", "financial_approval_protection"],
  },
  {
    ...wf("case_resolution", "Case resolution", "Service case intake through resolution."),
    primitives: ["submit", "assign", "start", "pause", "complete", "escalate", "close"],
    actors: ["customer", "agent", "supervisor"],
    states: ["open", "assigned", "in_progress", "waiting", "resolved", "closed"],
    transitions: ["assign", "start", "escalate", "complete", "close"],
    requiredPermissionBundleKeys: ["department_operator", "team_supervisor"],
    sareaPresentationHints: ["case_inbox", "specialist_workspace"],
    cyberCrowTrustChecks: ["customer_data_protection"],
  },
  {
    ...wf("project_delivery", "Project delivery", "Project phases through sign-off."),
    primitives: ["start", "assign", "complete", "sign_off", "invoice", "close"],
    actors: ["project_manager", "contributor", "approver"],
    states: ["planning", "active", "blocked", "completed", "closed"],
    transitions: ["start", "assign", "complete", "sign_off", "close"],
    requiredPermissionBundleKeys: ["department_manager", "workflow_approver"],
    sareaPresentationHints: ["project_workspace"],
  },
  {
    ...wf("work_order_execution", "Work order execution", "Field or shop-floor work order lifecycle."),
    primitives: ["assign", "accept", "start", "pause", "complete", "inspect", "verify"],
    actors: ["dispatcher", "technician", "supervisor"],
    states: ["queued", "assigned", "in_progress", "paused", "completed", "verified"],
    transitions: ["assign", "accept", "start", "complete", "verify"],
    requiredPermissionBundleKeys: ["field_execution", "team_supervisor"],
    sareaPresentationHints: ["technician_workbench", "field_task_mobile"],
    cyberCrowTrustChecks: ["field_device_trust"],
  },
  {
    ...wf("dispatch_and_delivery", "Dispatch and delivery", "Dispatch assignment through delivery proof."),
    primitives: ["dispatch", "accept", "start", "complete", "verify"],
    actors: ["dispatcher", "driver", "customer"],
    states: ["pending", "dispatched", "in_transit", "delivered", "exception"],
    transitions: ["dispatch", "accept", "start", "complete", "verify"],
    requiredPermissionBundleKeys: ["field_execution", "department_operator"],
    sareaPresentationHints: ["dispatch_console", "field_task_mobile"],
    status: "PARTIAL",
    provenance: "legacy",
    cyberCrowTrustChecks: ["field_device_trust", "branch_access_control"],
  },
  {
    ...wf("procure_to_receive", "Procure to receive", "Purchase request through goods receipt."),
    primitives: ["submit", "approve", "assign", "verify", "complete"],
    actors: ["requester", "procurement", "receiver"],
    states: ["requested", "approved", "ordered", "received", "closed"],
    transitions: ["submit", "approve", "assign", "verify", "complete"],
    requiredPermissionBundleKeys: ["department_operator", "financial_approver"],
    cyberCrowTrustChecks: ["financial_approval_protection", "vendor_access"],
  },
  {
    ...wf("hire_to_onboard", "Hire to onboard", "Offer through onboarding checklist."),
    primitives: ["submit", "approve", "assign", "complete"],
    actors: ["hiring_manager", "hr", "new_hire"],
    states: ["offer", "accepted", "onboarding", "active"],
    transitions: ["submit", "approve", "assign", "complete"],
    requiredPermissionBundleKeys: ["department_manager", "department_operator"],
    cyberCrowTrustChecks: ["sensitive_hr_data"],
  },
  {
    ...wf("incident_to_resolution", "Incident to resolution", "Security or safety incident handling."),
    primitives: ["submit", "assign", "escalate", "review", "close"],
    actors: ["reporter", "responder", "security_admin"],
    states: ["reported", "triaged", "investigating", "contained", "resolved"],
    transitions: ["assign", "escalate", "close"],
    requiredPermissionBundleKeys: ["security_posture_reader", "security_tenant_admin"],
    sareaPresentationHints: ["security_posture_console"],
    cyberCrowTrustChecks: ["incident_escalation", "audit_and_evidence"],
  },
  {
    ...wf("inspection_to_corrective_action", "Inspection to corrective action", "Findings through remediation."),
    primitives: ["inspect", "verify", "assign", "complete", "sign_off"],
    actors: ["inspector", "owner", "supervisor"],
    states: ["scheduled", "inspected", "action_required", "remediated", "verified"],
    transitions: ["inspect", "assign", "complete", "verify"],
    requiredPermissionBundleKeys: ["department_operator", "workflow_approver"],
  },
  {
    ...wf("contract_review_and_approval", "Contract review and approval", "Legal/commercial contract review."),
    primitives: ["submit", "review", "approve", "sign_off", "archive"],
    actors: ["author", "legal", "approver"],
    states: ["draft", "in_review", "approved", "executed", "archived"],
    transitions: ["submit", "review", "approve", "sign_off", "archive"],
    requiredPermissionBundleKeys: ["workflow_approver", "tenant_executive_read"],
  },
  {
    ...wf("customer_onboarding", "Customer onboarding", "Customer account setup and verification."),
    primitives: ["submit", "verify", "assign", "complete"],
    actors: ["customer", "onboarding_specialist"],
    states: ["invited", "in_progress", "verified", "active"],
    transitions: ["submit", "verify", "complete"],
    requiredPermissionBundleKeys: ["external_customer", "department_operator"],
    sareaPresentationHints: ["guided_onboarding", "customer_portal"],
    cyberCrowTrustChecks: ["external_portal_protection", "customer_data_protection"],
  },
  {
    ...wf("member_enrollment", "Member enrollment", "Membership enrollment and activation."),
    primitives: ["submit", "verify", "approve", "complete"],
    actors: ["member", "coordinator"],
    states: ["applied", "verified", "active"],
    transitions: ["submit", "verify", "approve", "complete"],
    requiredPermissionBundleKeys: ["external_customer", "department_operator"],
    sareaPresentationHints: ["member_portal", "guided_onboarding"],
  },
  {
    ...wf("booking_to_service_completion", "Booking to service completion", "Appointment through service delivery."),
    primitives: ["schedule", "assign", "start", "complete"],
    actors: ["customer", "coordinator", "provider"],
    states: ["booked", "confirmed", "in_service", "completed"],
    transitions: ["schedule", "assign", "start", "complete"],
    requiredPermissionBundleKeys: ["department_operator", "field_execution"],
    sareaPresentationHints: ["specialist_workspace", "customer_portal"],
  },
] as const;
