export const EMAIL_VERIFICATION_SOURCES = {
  CROW_EMAIL_OTP: "CROW_EMAIL_OTP",
  GOOGLE_OAUTH_VERIFIED: "GOOGLE_OAUTH_VERIFIED",
  MICROSOFT_OAUTH_VERIFIED: "MICROSOFT_OAUTH_VERIFIED",
  ADMIN_REVIEWED_MIGRATION: "ADMIN_REVIEWED_MIGRATION",
} as const;

export type EmailVerificationSource =
  (typeof EMAIL_VERIFICATION_SOURCES)[keyof typeof EMAIL_VERIFICATION_SOURCES];

export const PHONE_VERIFICATION_SOURCES = {
  CROW_SMS_OTP: "CROW_SMS_OTP",
  ADMIN_REVIEWED_MIGRATION: "ADMIN_REVIEWED_MIGRATION",
} as const;

export type PhoneVerificationSource =
  (typeof PHONE_VERIFICATION_SOURCES)[keyof typeof PHONE_VERIFICATION_SOURCES];
