import type {
  EvidenceSignalDef,
  EvidenceSignalFamily,
  HorizonId,
  MissionTemplate,
  WorldState,
} from "../../living-mission/types";

const initialWorld: WorldState = {
  SERVICE_HEALTH: 55,
  SYSTEM_UNDERSTANDING: 25,
  EVIDENCE_INTEGRITY: 50,
  RISK_EXPOSURE: 60,
  STAKEHOLDER_TRUST: 55,
  TECHNICAL_DEBT: 40,
  TIME_PRESSURE: 70,
};

function sig(
  signalId: string,
  family: EvidenceSignalFamily,
  capabilityTag: string,
  horizon: HorizonId,
  lineageHints: string[],
  direction: "SUPPORTING" | "CONFLICTING" | "NEUTRAL",
  strength: 1 | 2 | 3,
  explanationKey: string,
): EvidenceSignalDef {
  return {
    signalId,
    family,
    capabilityTag,
    horizon,
    lineageHints,
    direction,
    strength,
    explanationKey,
  };
}

/** Black Signal alpha fixture — synthetic district launch incident. */
export const BLACK_SIGNAL_V010: MissionTemplate = {
  missionId: "LM-BLACK-SIGNAL",
  version: "0.1.0",
  rulesetVersion: "lm-ruleset-0.1.0",
  titleAr: "الرحلة الأولى — الإشارة السوداء",
  titleEn: "First Flight — Black Signal",
  classification: "ALPHA_FIXTURE",
  initialWorld,
  entryNodeId: "N01_signal_arrival",
  echoCandidateNodeIds: [
    "N04_triage_priority",
    "N09_containment_mode",
    "N12_comms_stance",
  ],
  scenes: [
    {
      sceneId: "S1",
      titleAr: "وصول الإشارة",
      titleEn: "Signal Arrival",
      order: 1,
    },
    {
      sceneId: "S2",
      titleAr: "الفرز والفهم",
      titleEn: "Triage and Understanding",
      order: 2,
    },
    {
      sceneId: "S3",
      titleAr: "الاحتواء والتعافي والتواصل",
      titleEn: "Containment, Recovery and Communication",
      order: 3,
    },
    {
      sceneId: "S4",
      titleAr: "العواقب والمراجعة",
      titleEn: "Consequence and Debrief",
      order: 4,
    },
  ],
  outcomes: [
    {
      outcomeId: "OUTCOME_CONTINUITY_FIRST",
      titleAr: "استعادة سريعة للخدمة",
      titleEn: "Continuity first",
      summaryAr: "عدت الوصول بسرعة لكن مسار الأدلة أضعف.",
      summaryEn: "Access restored quickly; evidence trail is thinner.",
    },
    {
      outcomeId: "OUTCOME_EVIDENCE_FIRST",
      titleAr: "مسار أدلة قوي",
      titleEn: "Evidence first",
      summaryAr: "حافظت على الأدلة؛ التعافي استغرق وقتاً أطول.",
      summaryEn: "Evidence preserved well; recovery took longer.",
    },
    {
      outcomeId: "OUTCOME_BALANCED_CONTAINMENT",
      titleAr: "احتواء متوازن",
      titleEn: "Balanced containment",
      summaryAr: "وازنت بين الاستمرارية والأدلة مع مخاطر مضبوطة.",
      summaryEn: "Balanced continuity and evidence with controlled risk.",
    },
    {
      outcomeId: "OUTCOME_DEBT_HEAVY",
      titleAr: "رقعة قصيرة الأمد",
      titleEn: "Debt-heavy patch",
      summaryAr: "أصلحت العرض سريعاً على حساب دين تقني ومخاطر متبقية.",
      summaryEn: "Short-term patch; high debt and residual risk.",
    },
  ],
  nodes: [
    {
      nodeId: "N01_signal_arrival",
      sceneId: "S1",
      titleAr: "تنبيه متضارب",
      titleEn: "Conflicting alert",
      bodyAr:
        "بلاغات الأمان تقول هجوماً. العمليات تقول تعثّر نشر. المستخدمون يفقدون الدخول.",
      bodyEn:
        "Security reports attack. Ops reports deploy fault. Users lose access.",
      choices: [
        {
          choiceId: "C01_map_deps",
          labelAr: "ارسم خريطة التبعيات أولاً",
          labelEn: "Map dependencies first",
          effect: {
            world: { SYSTEM_UNDERSTANDING: 12, TIME_PRESSURE: 5 },
            nextNodeId: "N02_scope_blast",
            signals: [
              sig(
                "SIG-N01-A",
                "DEPENDENCY_MAPPING",
                "dep-map",
                "BUILD",
                ["CRW-BLD-01", "CRW-BLD-03"],
                "SUPPORTING",
                2,
                "map_deps",
              ),
            ],
          },
        },
        {
          choiceId: "C01_restore_now",
          labelAr: "أعد الخدمة فوراً بأي وسيلة",
          labelEn: "Restore service immediately",
          effect: {
            world: {
              SERVICE_HEALTH: 15,
              EVIDENCE_INTEGRITY: -10,
              RISK_EXPOSURE: 8,
              TECHNICAL_DEBT: 10,
            },
            nextNodeId: "N02_scope_blast",
            signals: [
              sig(
                "SIG-N01-B",
                "SERVICE_RECOVERY",
                "svc-restore",
                "OPERATE",
                ["CRW-OPR-03", "CRW-OPR-05"],
                "SUPPORTING",
                2,
                "restore_now",
              ),
              sig(
                "SIG-N01-B2",
                "EVIDENCE_PRESERVATION",
                "ev-loss",
                "PROTECT",
                ["CRW-OPR-03"],
                "CONFLICTING",
                1,
                "evidence_risk",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N02_scope_blast",
      sceneId: "S1",
      titleAr: "نطاق التأثير",
      titleEn: "Blast radius",
      bodyAr: "أي فصول رقمية متأثرة؟ البيانات تركيبية فقط.",
      bodyEn: "Which digital classrooms are hit? Synthetic data only.",
      choices: [
        {
          choiceId: "C02_broad_survey",
          labelAr: "مسح واسع عبر الأفق",
          labelEn: "Broad survey across horizons",
          effect: {
            world: { SYSTEM_UNDERSTANDING: 10, TIME_PRESSURE: 8 },
            nextNodeId: "N03_conflicting_reports",
            signals: [
              sig(
                "SIG-N02-A",
                "SYSTEMS_THINKING",
                "sys-scope",
                "BUILD",
                ["CRW-BLD-03", "CRW-BLD-04"],
                "SUPPORTING",
                2,
                "broad_survey",
              ),
            ],
          },
        },
        {
          choiceId: "C02_hot_path",
          labelAr: "ركّز على مسار الإطلاق الساخن",
          labelEn: "Focus on launch hot path",
          effect: {
            world: {
              TIME_PRESSURE: -8,
              SYSTEM_UNDERSTANDING: 5,
              RISK_EXPOSURE: 5,
            },
            nextNodeId: "N03_conflicting_reports",
            signals: [
              sig(
                "SIG-N02-B",
                "DECISION_SPEED",
                "speed",
                "OPERATE",
                ["CRW-OPR-01", "CRW-OPR-02"],
                "SUPPORTING",
                2,
                "hot_path",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N03_conflicting_reports",
      sceneId: "S1",
      titleAr: "تقارير متعارضة",
      titleEn: "Conflicting reports",
      bodyAr: "سجلّ أمني يشير لتسلل. سجلّ نشر يشير لخطأ إعداد.",
      bodyEn: "Security log hints intrusion. Deploy log hints misconfig.",
      choices: [
        {
          choiceId: "C03_hold_judgment",
          labelAr: "علق الحكم واجمع سياقاً",
          labelEn: "Hold judgment; gather context",
          effect: {
            world: { SYSTEM_UNDERSTANDING: 8, TIME_PRESSURE: 4 },
            nextNodeId: "N04_triage_priority",
            signals: [
              sig(
                "SIG-N03-A",
                "UNCERTAINTY_HANDLING",
                "uncertainty",
                "ANALYZE",
                ["CRW-BLD-05", "CRW-OPR-02"],
                "SUPPORTING",
                2,
                "hold_judgment",
              ),
            ],
          },
        },
        {
          choiceId: "C03_treat_security",
          labelAr: "عاملها كحادثة أمنية فوراً",
          labelEn: "Treat as security incident now",
          effect: {
            world: {
              RISK_EXPOSURE: -10,
              SERVICE_HEALTH: -8,
              STAKEHOLDER_TRUST: 5,
            },
            nextNodeId: "N04_triage_priority",
            signals: [
              sig(
                "SIG-N03-B",
                "RISK_CONTROL",
                "sec-first",
                "PROTECT",
                ["CRW-OPR-03"],
                "SUPPORTING",
                3,
                "security_first",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N04_triage_priority",
      sceneId: "S2",
      titleAr: "أولوية الفرز",
      titleEn: "Triage priority",
      bodyAr: "محور حاسم: استمرارية أم أدلة؟",
      bodyEn: "Pivotal: continuity or evidence?",
      choices: [
        {
          choiceId: "C04_continuity",
          labelAr: "أولوية استمرارية الخدمة",
          labelEn: "Prioritize service continuity",
          effect: {
            world: {
              SERVICE_HEALTH: 12,
              EVIDENCE_INTEGRITY: -12,
              TIME_PRESSURE: -10,
            },
            nextNodeId: "N05_diagnostic_path",
            echoCandidate: true,
            signals: [
              sig(
                "SIG-N04-A",
                "SERVICE_RECOVERY",
                "cont",
                "OPERATE",
                ["CRW-OPR-03", "CRW-OPR-05"],
                "SUPPORTING",
                3,
                "triage_continuity",
              ),
            ],
          },
        },
        {
          choiceId: "C04_evidence",
          labelAr: "أولوية حفظ الأدلة",
          labelEn: "Prioritize evidence preservation",
          effect: {
            world: {
              EVIDENCE_INTEGRITY: 15,
              SERVICE_HEALTH: -10,
              TIME_PRESSURE: 6,
            },
            nextNodeId: "N05_diagnostic_path",
            echoCandidate: true,
            signals: [
              sig(
                "SIG-N04-B",
                "EVIDENCE_PRESERVATION",
                "ev",
                "PROTECT",
                ["CRW-OPR-03", "CRW-BLD-05"],
                "SUPPORTING",
                3,
                "triage_evidence",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N05_diagnostic_path",
      sceneId: "S2",
      titleAr: "مسار التشخيص",
      titleEn: "Diagnostic path",
      bodyAr: "كيف ترتّب الفحص؟",
      bodyEn: "How do you sequence diagnosis?",
      choices: [
        {
          choiceId: "C05_layered",
          labelAr: "تشخيص طبقي من الشبكة للتطبيق",
          labelEn: "Layered network-to-app diagnosis",
          effect: {
            world: { SYSTEM_UNDERSTANDING: 14, TIME_PRESSURE: 5 },
            nextNodeId: "N06_experiment",
            signals: [
              sig(
                "SIG-N05-A",
                "DIAGNOSTIC_SEQUENCE",
                "diag",
                "OPERATE",
                ["CRW-OPR-02", "CRW-BLD-03"],
                "SUPPORTING",
                3,
                "layered_diag",
              ),
            ],
          },
        },
        {
          choiceId: "C05_guess_patch",
          labelAr: "رقعة تخمينية سريعة",
          labelEn: "Quick guess-and-patch",
          effect: {
            world: {
              TECHNICAL_DEBT: 15,
              SYSTEM_UNDERSTANDING: -5,
              SERVICE_HEALTH: 8,
              RISK_EXPOSURE: 10,
            },
            nextNodeId: "N06_experiment",
            signals: [
              sig(
                "SIG-N05-B",
                "TECHNICAL_DEBT_AWARENESS",
                "debt",
                "BUILD",
                ["CRW-BLD-02"],
                "CONFLICTING",
                2,
                "guess_patch",
              ),
              sig(
                "SIG-N05-B2",
                "SERVICE_RECOVERY",
                "quick",
                "OPERATE",
                ["CRW-OPR-01"],
                "SUPPORTING",
                1,
                "quick_up",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N06_experiment",
      sceneId: "S2",
      titleAr: "تجربة مضبوطة",
      titleEn: "Controlled experiment",
      bodyAr: "هل تختبر فرضية النشر في بيئة معزولة؟",
      bodyEn: "Test the deploy hypothesis in an isolated lane?",
      choices: [
        {
          choiceId: "C06_sandbox",
          labelAr: "نعم — تجربة معزولة",
          labelEn: "Yes — isolated experiment",
          effect: {
            world: { SYSTEM_UNDERSTANDING: 10, TIME_PRESSURE: 6 },
            nextNodeId: "N07_interop",
            signals: [
              sig(
                "SIG-N06-A",
                "EXPERIMENTATION",
                "exp",
                "BUILD",
                ["CRW-BLD-02", "CRW-BLD-01"],
                "SUPPORTING",
                2,
                "sandbox",
              ),
              sig(
                "SIG-N06-A2",
                "VALIDATION_DISCIPLINE",
                "val",
                "BUILD",
                ["CRW-BLD-05"],
                "SUPPORTING",
                2,
                "validate",
              ),
            ],
          },
        },
        {
          choiceId: "C06_prod_probe",
          labelAr: "اختبر مباشرة على المسار الحي",
          labelEn: "Probe the live path",
          effect: {
            world: {
              RISK_EXPOSURE: 12,
              SYSTEM_UNDERSTANDING: 6,
              EVIDENCE_INTEGRITY: -5,
            },
            nextNodeId: "N07_interop",
            signals: [
              sig(
                "SIG-N06-B",
                "EXPERIMENTATION",
                "live-probe",
                "OPERATE",
                ["CRW-OPR-04"],
                "SUPPORTING",
                1,
                "live_probe",
              ),
              sig(
                "SIG-N06-B2",
                "RISK_CONTROL",
                "risk",
                "PROTECT",
                ["CRW-OPR-03"],
                "CONFLICTING",
                2,
                "live_risk",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N07_interop",
      sceneId: "S2",
      titleAr: "توافق الأنظمة",
      titleEn: "Interoperability",
      bodyAr: "بوابة الهوية وخدمة الإشعارات تختلفان في الحالة.",
      bodyEn: "Identity gateway and notify service disagree on status.",
      choices: [
        {
          choiceId: "C07_contract_check",
          labelAr: "راجع عقود الواجهة بين الخدمات",
          labelEn: "Review service interface contracts",
          effect: {
            world: { SYSTEM_UNDERSTANDING: 10, TECHNICAL_DEBT: -5 },
            nextNodeId: "N08_structure",
            signals: [
              sig(
                "SIG-N07-A",
                "INTEROPERABILITY",
                "interop",
                "BUILD",
                ["CRW-BLD-04", "CRW-BLD-01"],
                "SUPPORTING",
                3,
                "contracts",
              ),
            ],
          },
        },
        {
          choiceId: "C07_force_sync",
          labelAr: "افرض مزامنة يدوية سريعة",
          labelEn: "Force a quick manual sync",
          effect: {
            world: {
              SERVICE_HEALTH: 10,
              TECHNICAL_DEBT: 12,
              EVIDENCE_INTEGRITY: -6,
            },
            nextNodeId: "N08_structure",
            signals: [
              sig(
                "SIG-N07-B",
                "SERVICE_RECOVERY",
                "force-sync",
                "OPERATE",
                ["CRW-OPR-04", "CRW-OPR-01"],
                "SUPPORTING",
                2,
                "force_sync",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N08_structure",
      sceneId: "S2",
      titleAr: "سبب هيكلي؟",
      titleEn: "Structural cause?",
      bodyAr: "هل المشكلة في البنية أم في حدث عابر؟",
      bodyEn: "Structural flaw or transient event?",
      choices: [
        {
          choiceId: "C08_structural",
          labelAr: "افترض سبباً هيكلياً وأعد التصميم الجزئي",
          labelEn: "Assume structural cause; redesign slice",
          effect: {
            world: {
              TECHNICAL_DEBT: -12,
              TIME_PRESSURE: 10,
              SYSTEM_UNDERSTANDING: 8,
            },
            nextNodeId: "N09_containment_mode",
            signals: [
              sig(
                "SIG-N08-A",
                "STRUCTURAL_REASONING",
                "struct",
                "BUILD",
                ["CRW-BLD-01", "CRW-BLD-03"],
                "SUPPORTING",
                3,
                "structural",
              ),
            ],
          },
        },
        {
          choiceId: "C08_transient",
          labelAr: "عاملها كحدث عابر وراقب",
          labelEn: "Treat as transient; monitor",
          effect: {
            world: { TIME_PRESSURE: -8, RISK_EXPOSURE: 8, TECHNICAL_DEBT: 8 },
            nextNodeId: "N09_containment_mode",
            signals: [
              sig(
                "SIG-N08-B",
                "UNCERTAINTY_HANDLING",
                "transient",
                "OPERATE",
                ["CRW-OPR-02"],
                "SUPPORTING",
                1,
                "transient",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N09_containment_mode",
      sceneId: "S3",
      titleAr: "نمط الاحتواء",
      titleEn: "Containment mode",
      bodyAr: "عزل المسار أم ترقيع حي؟",
      bodyEn: "Isolate the path or live-patch?",
      choices: [
        {
          choiceId: "C09_isolate",
          labelAr: "اعزل المسار المتأثر",
          labelEn: "Isolate affected path",
          effect: {
            world: {
              RISK_EXPOSURE: -15,
              SERVICE_HEALTH: -5,
              EVIDENCE_INTEGRITY: 8,
            },
            nextNodeId: "N10_recovery_plan",
            echoCandidate: true,
            signals: [
              sig(
                "SIG-N09-A",
                "RISK_CONTROL",
                "isolate",
                "PROTECT",
                ["CRW-OPR-03", "CRW-BLD-05"],
                "SUPPORTING",
                3,
                "isolate",
              ),
            ],
          },
        },
        {
          choiceId: "C09_live_patch",
          labelAr: "رقعة حية سريعة",
          labelEn: "Fast live patch",
          effect: {
            world: {
              SERVICE_HEALTH: 15,
              TECHNICAL_DEBT: 15,
              RISK_EXPOSURE: 5,
              EVIDENCE_INTEGRITY: -8,
            },
            nextNodeId: "N10_recovery_plan",
            echoCandidate: true,
            signals: [
              sig(
                "SIG-N09-B",
                "SERVICE_RECOVERY",
                "live-patch",
                "OPERATE",
                ["CRW-OPR-01", "CRW-OPR-04"],
                "SUPPORTING",
                3,
                "live_patch",
              ),
              sig(
                "SIG-N09-B2",
                "TECHNICAL_DEBT_AWARENESS",
                "debt2",
                "BUILD",
                ["CRW-BLD-02"],
                "CONFLICTING",
                2,
                "patch_debt",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N10_recovery_plan",
      sceneId: "S3",
      titleAr: "خطة التعافي",
      titleEn: "Recovery plan",
      bodyAr: "كيف تعيد المستخدمين؟",
      bodyEn: "How do you restore learners?",
      choices: [
        {
          choiceId: "C10_staged",
          labelAr: "تعافٍ مرحلي مع تحقق",
          labelEn: "Staged recovery with validation",
          effect: {
            world: { SERVICE_HEALTH: 10, TIME_PRESSURE: 4 },
            nextNodeId: "N11_debt_choice",
            signals: [
              sig(
                "SIG-N10-A",
                "VALIDATION_DISCIPLINE",
                "staged",
                "OPERATE",
                ["CRW-OPR-05", "CRW-BLD-05"],
                "SUPPORTING",
                2,
                "staged",
              ),
              sig(
                "SIG-N10-A2",
                "SERVICE_RECOVERY",
                "rec",
                "OPERATE",
                ["CRW-OPR-05"],
                "SUPPORTING",
                2,
                "recover",
              ),
            ],
          },
        },
        {
          choiceId: "C10_all_at_once",
          labelAr: "أعد الجميع دفعة واحدة",
          labelEn: "Bring everyone back at once",
          effect: {
            world: {
              SERVICE_HEALTH: 18,
              RISK_EXPOSURE: 12,
              STAKEHOLDER_TRUST: 5,
            },
            nextNodeId: "N11_debt_choice",
            signals: [
              sig(
                "SIG-N10-B",
                "DECISION_SPEED",
                "blast-restore",
                "OPERATE",
                ["CRW-OPR-01"],
                "SUPPORTING",
                2,
                "all_at_once",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N11_debt_choice",
      sceneId: "S3",
      titleAr: "الدين التقني",
      titleEn: "Technical debt",
      bodyAr: "هل توثّق الدين وتجدول إصلاحاً؟",
      bodyEn: "Document debt and schedule repair?",
      choices: [
        {
          choiceId: "C11_schedule_debt",
          labelAr: "نعم — سجّل الدين وخطة الإصلاح",
          labelEn: "Yes — record debt and repair plan",
          effect: {
            world: { TECHNICAL_DEBT: -10, STAKEHOLDER_TRUST: 8 },
            nextNodeId: "N12_comms_stance",
            signals: [
              sig(
                "SIG-N11-A",
                "TECHNICAL_DEBT_AWARENESS",
                "debt-plan",
                "BUILD",
                ["CRW-BLD-01", "CRW-BLD-05"],
                "SUPPORTING",
                3,
                "debt_plan",
              ),
            ],
          },
        },
        {
          choiceId: "C11_ignore_debt",
          labelAr: "لاحقاً — الآن يكفي أن يعمل",
          labelEn: "Later — working is enough now",
          effect: {
            world: { TECHNICAL_DEBT: 12, TIME_PRESSURE: -6, RISK_EXPOSURE: 6 },
            nextNodeId: "N12_comms_stance",
            signals: [
              sig(
                "SIG-N11-B",
                "TECHNICAL_DEBT_AWARENESS",
                "debt-ignore",
                "BUILD",
                ["CRW-BLD-02"],
                "CONFLICTING",
                2,
                "debt_ignore",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N12_comms_stance",
      sceneId: "S3",
      titleAr: "موقف التواصل",
      titleEn: "Communication stance",
      bodyAr: "ماذا تقول للحيّ التعليمي؟",
      bodyEn: "What do you tell the learning district?",
      choices: [
        {
          choiceId: "C12_transparent",
          labelAr: "شفافية مضبوطة مع خطوات تالية",
          labelEn: "Controlled transparency with next steps",
          effect: {
            world: { STAKEHOLDER_TRUST: 15, TIME_PRESSURE: 3 },
            nextNodeId: "N13_stakeholder",
            echoCandidate: true,
            signals: [
              sig(
                "SIG-N12-A",
                "COMMUNICATION",
                "transparent",
                "LEAD",
                ["CRW-OPR-05", "CRW-BLD-04"],
                "SUPPORTING",
                3,
                "transparent",
              ),
            ],
          },
        },
        {
          choiceId: "C12_minimize",
          labelAr: "قلل التفاصيل لتجنب الذعر",
          labelEn: "Minimize details to avoid panic",
          effect: {
            world: {
              STAKEHOLDER_TRUST: -8,
              TIME_PRESSURE: -5,
              RISK_EXPOSURE: 5,
            },
            nextNodeId: "N13_stakeholder",
            echoCandidate: true,
            signals: [
              sig(
                "SIG-N12-B",
                "COMMUNICATION",
                "minimize",
                "LEAD",
                ["CRW-OPR-05"],
                "CONFLICTING",
                2,
                "minimize",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N13_stakeholder",
      sceneId: "S3",
      titleAr: "طلب الإدارة",
      titleEn: "Leadership request",
      bodyAr: "يطلبون ضماناً بأن الإطلاق سيمر غداً.",
      bodyEn: "Leaders want a guarantee launch proceeds tomorrow.",
      choices: [
        {
          choiceId: "C13_honest_risk",
          labelAr: "اشرح المخاطر بصدق وخيارات التأجيل",
          labelEn: "Explain risks honestly; offer delay options",
          effect: {
            world: { STAKEHOLDER_TRUST: 10, RISK_EXPOSURE: -5 },
            nextNodeId: "N14_final_balance",
            signals: [
              sig(
                "SIG-N13-A",
                "COMMUNICATION",
                "honest",
                "LEAD",
                ["CRW-OPR-05"],
                "SUPPORTING",
                2,
                "honest_risk",
              ),
              sig(
                "SIG-N13-A2",
                "RISK_CONTROL",
                "delay-opt",
                "PROTECT",
                ["CRW-OPR-03"],
                "SUPPORTING",
                1,
                "delay_opt",
              ),
            ],
          },
        },
        {
          choiceId: "C13_promise",
          labelAr: "قدّم ضماناً قاطعاً للإطلاق",
          labelEn: "Promise a hard launch guarantee",
          effect: {
            world: {
              STAKEHOLDER_TRUST: 5,
              RISK_EXPOSURE: 15,
              TECHNICAL_DEBT: 5,
            },
            nextNodeId: "N14_final_balance",
            signals: [
              sig(
                "SIG-N13-B",
                "COMMUNICATION",
                "overpromise",
                "LEAD",
                ["CRW-OPR-05"],
                "CONFLICTING",
                2,
                "overpromise",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N14_final_balance",
      sceneId: "S4",
      titleAr: "التوازن الأخير",
      titleEn: "Final balance",
      bodyAr: "اختر كيفية إغلاق الحادثة لهذه الرحلة.",
      bodyEn: "Choose how this flight closes the incident.",
      choices: [
        {
          choiceId: "C14_continuity_close",
          labelAr: "أغلق مع تركيز على الاستمرارية",
          labelEn: "Close continuity-focused",
          effect: {
            world: { SERVICE_HEALTH: 8 },
            nextNodeId: "N15_debrief_prompt",
            outcomeId: "OUTCOME_CONTINUITY_FIRST",
            signals: [
              sig(
                "SIG-N14-A",
                "SERVICE_RECOVERY",
                "close-cont",
                "OPERATE",
                ["CRW-OPR-03", "CRW-OPR-05"],
                "SUPPORTING",
                2,
                "close_cont",
              ),
            ],
          },
        },
        {
          choiceId: "C14_evidence_close",
          labelAr: "أغلق مع تركيز على الأدلة",
          labelEn: "Close evidence-focused",
          effect: {
            world: { EVIDENCE_INTEGRITY: 8 },
            nextNodeId: "N15_debrief_prompt",
            outcomeId: "OUTCOME_EVIDENCE_FIRST",
            signals: [
              sig(
                "SIG-N14-B",
                "EVIDENCE_PRESERVATION",
                "close-ev",
                "PROTECT",
                ["CRW-OPR-03", "CRW-BLD-05"],
                "SUPPORTING",
                2,
                "close_ev",
              ),
            ],
          },
        },
        {
          choiceId: "C14_balanced_close",
          labelAr: "أغلق باحتواء متوازن",
          labelEn: "Close with balanced containment",
          effect: {
            world: {
              SERVICE_HEALTH: 4,
              EVIDENCE_INTEGRITY: 4,
              RISK_EXPOSURE: -4,
            },
            nextNodeId: "N15_debrief_prompt",
            outcomeId: "OUTCOME_BALANCED_CONTAINMENT",
            signals: [
              sig(
                "SIG-N14-C",
                "SYSTEMS_THINKING",
                "close-bal",
                "BUILD",
                ["CRW-BLD-03", "CRW-OPR-02"],
                "SUPPORTING",
                2,
                "close_bal",
              ),
            ],
          },
        },
        {
          choiceId: "C14_debt_close",
          labelAr: "أغلق برقعة قصيرة الأمد",
          labelEn: "Close with short-term patch",
          effect: {
            world: { TECHNICAL_DEBT: 10, SERVICE_HEALTH: 6, RISK_EXPOSURE: 6 },
            nextNodeId: "N15_debrief_prompt",
            outcomeId: "OUTCOME_DEBT_HEAVY",
            signals: [
              sig(
                "SIG-N14-D",
                "TECHNICAL_DEBT_AWARENESS",
                "close-debt",
                "BUILD",
                ["CRW-BLD-02"],
                "CONFLICTING",
                2,
                "close_debt",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N15_debrief_prompt",
      sceneId: "S4",
      titleAr: "تأمل قصير",
      titleEn: "Short reflection",
      bodyAr: "ما أكثر قرار أثر على نتيجتك؟ (ذاتي — ليس إتقاناً)",
      bodyEn:
        "Which decision most shaped your outcome? (self-report — not Mastery)",
      choices: [
        {
          choiceId: "C15_reflect_ops",
          labelAr: "قرارات التشغيل والتعافي",
          labelEn: "Operate / recovery decisions",
          effect: {
            world: {},
            nextNodeId: "N16_complete",
            signals: [
              sig(
                "SIG-N15-A",
                "SERVICE_RECOVERY",
                "reflect-ops",
                "OPERATE",
                ["CRW-OPR-03"],
                "NEUTRAL",
                1,
                "reflect_ops",
              ),
            ],
          },
        },
        {
          choiceId: "C15_reflect_build",
          labelAr: "قرارات البنية والتجريب",
          labelEn: "Build / structure decisions",
          effect: {
            world: {},
            nextNodeId: "N16_complete",
            signals: [
              sig(
                "SIG-N15-B",
                "STRUCTURAL_REASONING",
                "reflect-build",
                "BUILD",
                ["CRW-BLD-01"],
                "NEUTRAL",
                1,
                "reflect_build",
              ),
            ],
          },
        },
      ],
    },
    {
      nodeId: "N16_complete",
      sceneId: "S4",
      titleAr: "إكمال الرحلة",
      titleEn: "Complete flight",
      bodyAr: "أكد إكمال الرحلة الكنسية. يمكنك لاحقاً تجربة Echo Flight.",
      bodyEn: "Confirm canonical flight completion. Echo Flight may follow.",
      choices: [
        {
          choiceId: "C16_complete",
          labelAr: "أكمل الرحلة",
          labelEn: "Complete the flight",
          effect: {
            world: {},
            nextNodeId: null,
            signals: [],
          },
        },
      ],
    },
  ],
};

export const BLACK_SIGNAL_MISSION_ID = BLACK_SIGNAL_V010.missionId;
export const BLACK_SIGNAL_VERSION = BLACK_SIGNAL_V010.version;
