import type { OrgIntelligenceModel, SectorTemplateKey } from "@/lib/org-intelligence/types";

/** Live CEM catalog keys for logistics operating model (lighthouse / MEEM-aligned). */
export const LOGISTICS_RECOMMENDED_CEM_MODULE_KEYS = [
  "logistics",
  "warehouse",
  "inventory",
  "procurement",
  "crm",
  "finance",
  "hr",
  "sales",
  "approvals",
  "bi",
] as const;

/** ERP runtime keys (tasks → approvals, reports → bi per erp-module-registry). */
export const LOGISTICS_RECOMMENDED_ERP_MODULE_KEYS = [
  "logistics",
  "warehouse",
  "inventory",
  "procurement",
  "crm",
  "finance",
  "hr",
  "sales",
  "tasks",
  "reports",
] as const;

/** Future integration / readiness only — not live CEM modules. */
export const LOGISTICS_FUTURE_READINESS_KEYS = [
  "telematics_integration",
  "carrier_api_live",
  "route_optimization_saas",
  "live_pod_capture",
  "autonomous_dispatch",
] as const;

const LOGISTICS: OrgIntelligenceModel = {
  sectorTemplateKey: "logistics",
  sectorName: "Logistics Operating Model",
  industry: "logistics",
  maturityLevel: "growth",
  branchTypes: [
    { key: "hq", name: "Headquarters", description: "Executive and shared services" },
    { key: "hub", name: "Distribution hub", description: "Regional consolidation and cross-dock" },
    { key: "depot", name: "Fleet depot", description: "Vehicle and driver coordination" },
    { key: "warehouse", name: "Warehouse / DC", description: "Inventory movement and dispatch staging" },
    { key: "customer-site", name: "Customer delivery node", description: "Last-mile delivery context (readiness)" },
  ],
  departments: [
    { key: "exec", name: "Executive Office", recommendedPriority: 1, recommendedHeadcount: { min: 2, max: 8 } },
    {
      key: "logistics-ops",
      name: "Logistics Operations",
      recommendedPriority: 1,
      recommendedHeadcount: { min: 5, max: 45 },
    },
    {
      key: "dispatch",
      name: "Dispatch / Delivery Coordination",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 4, max: 35 },
    },
    {
      key: "fleet",
      name: "Fleet / Driver Coordination",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 4, max: 40 },
    },
    {
      key: "warehouse",
      name: "Warehouse Operations",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 8, max: 80 },
    },
    {
      key: "inventory",
      name: "Inventory Control",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 4, max: 30 },
    },
    {
      key: "procurement",
      name: "Procurement / Supplier Management",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 2, max: 18 },
    },
    {
      key: "crm-accts",
      name: "Customer Accounts / CRM",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 4, max: 28 },
    },
    {
      key: "finance",
      name: "Finance / Billing Coordination",
      recommendedPriority: 4,
      recommendedHeadcount: { min: 3, max: 18 },
    },
    { key: "hr", name: "HR / Workforce", recommendedPriority: 5, recommendedHeadcount: { min: 2, max: 14 } },
    {
      key: "compliance",
      name: "Compliance / Safety",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 2, max: 12 },
    },
    { key: "it", name: "IT & Security", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 10 } },
    { key: "security", name: "CyberCrow Security", recommendedPriority: 2, recommendedHeadcount: { min: 1, max: 6 } },
  ],
  positions: [
    {
      key: "exec-owner",
      title: "Executive / Owner",
      departmentKey: "exec",
      level: "executive",
      responsibilities: ["Strategy", "Network KPIs", "Risk posture"],
      sareaPersonaKey: "executive",
      cybercrowSensitive: true,
    },
    {
      key: "logistics-ops-mgr",
      title: "Logistics Operations Manager",
      departmentKey: "logistics-ops",
      level: "manager",
      responsibilities: ["SLA governance", "Multi-branch coordination", "Exception handling"],
      sareaPersonaKey: "manager",
      riskSensitive: true,
    },
    {
      key: "dispatch-coord",
      title: "Dispatch Coordinator",
      departmentKey: "dispatch",
      level: "specialist",
      responsibilities: ["Route assignment", "Delivery scheduling", "Live status updates"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "driver",
      title: "Driver / Field Operator",
      departmentKey: "fleet",
      level: "frontline",
      responsibilities: ["Deliveries", "Task updates", "Vehicle checks"],
      sareaPersonaKey: "frontline",
      cybercrowSensitive: true,
      recommendedCountMin: 5,
      recommendedCountMax: 120,
    },
    {
      key: "wh-sup",
      title: "Warehouse Supervisor",
      departmentKey: "warehouse",
      level: "manager",
      responsibilities: ["Inbound/outbound", "Labor planning", "Dispatch staging"],
      sareaPersonaKey: "manager",
    },
    {
      key: "inv-ctrl",
      title: "Inventory Controller",
      departmentKey: "inventory",
      level: "specialist",
      responsibilities: ["Stock accuracy", "Movements", "Cycle counts"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "proc-spec",
      title: "Procurement Specialist",
      departmentKey: "procurement",
      level: "specialist",
      responsibilities: ["Supplier requests", "PO coordination", "Vendor evidence"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "acct-mgr",
      title: "Customer Account Manager",
      departmentKey: "crm-accts",
      level: "manager",
      responsibilities: ["Key accounts", "Escalations", "Service levels"],
      sareaPersonaKey: "manager",
    },
    {
      key: "finance-coord",
      title: "Finance Coordinator",
      departmentKey: "finance",
      level: "specialist",
      responsibilities: ["Billing coordination", "Approvals", "Cost allocation"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "hr-coord",
      title: "HR Coordinator",
      departmentKey: "hr",
      level: "specialist",
      responsibilities: ["Onboarding", "Workforce scheduling", "Policy"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "compliance-officer",
      title: "Compliance / Safety Officer",
      departmentKey: "compliance",
      level: "specialist",
      responsibilities: ["Safety process", "Incident review", "Audit support"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "it-admin",
      title: "IT / Security Administrator",
      departmentKey: "it",
      level: "specialist",
      responsibilities: ["Access provisioning", "Integration readiness", "Device policy"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "analyst",
      title: "Analyst",
      departmentKey: "logistics-ops",
      level: "specialist",
      responsibilities: ["Performance reporting", "Trend analysis", "Evidence gaps"],
      sareaPersonaKey: "analyst",
    },
    {
      key: "tenant-admin",
      title: "Tenant Admin",
      departmentKey: "exec",
      level: "manager",
      responsibilities: ["Tenant config", "User access", "Role assignments"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "cc-analyst",
      title: "CyberCrow Security Reviewer",
      departmentKey: "security",
      level: "specialist",
      responsibilities: ["Delivery audit", "Incident triage", "Access reviews"],
      sareaPersonaKey: "security",
      cybercrowSensitive: true,
    },
  ],
  workflows: [
    {
      key: "delivery-intake",
      name: "Delivery request intake",
      departmentScope: "dispatch",
      complexityLevel: "standard",
    },
    {
      key: "dispatch-assign",
      name: "Dispatch assignment",
      departmentScope: "dispatch",
      complexityLevel: "standard",
    },
    {
      key: "driver-task-update",
      name: "Driver task update",
      departmentScope: "fleet",
      complexityLevel: "lite",
    },
    {
      key: "shipment-status",
      name: "Shipment status update",
      departmentScope: "logistics-ops",
      complexityLevel: "lite",
    },
    {
      key: "wh-receiving",
      name: "Warehouse receiving",
      departmentScope: "warehouse",
      complexityLevel: "standard",
    },
    {
      key: "inv-movement",
      name: "Inventory movement",
      departmentScope: "inventory",
      complexityLevel: "standard",
    },
    {
      key: "stock-adjust-review",
      name: "Stock adjustment review",
      departmentScope: "inventory",
      complexityLevel: "standard",
    },
    {
      key: "supplier-pr",
      name: "Supplier purchase request",
      departmentScope: "procurement",
      complexityLevel: "standard",
    },
    {
      key: "cust-issue-esc",
      name: "Customer issue escalation",
      departmentScope: "crm-accts",
      complexityLevel: "standard",
    },
    {
      key: "delivery-exception",
      name: "Delivery exception / incident report",
      departmentScope: "compliance",
      complexityLevel: "advanced",
    },
    {
      key: "pod-review",
      name: "Proof-of-delivery review",
      departmentScope: "dispatch",
      complexityLevel: "standard",
    },
    {
      key: "logistics-perf",
      name: "Monthly logistics performance review",
      departmentScope: "logistics-ops",
      complexityLevel: "advanced",
    },
    {
      key: "access-review",
      name: "Access review / role change review",
      departmentScope: "security",
      complexityLevel: "standard",
    },
    {
      key: "route-approval",
      name: "Route approval",
      departmentScope: "fleet",
      complexityLevel: "standard",
    },
    {
      key: "wh-dispatch",
      name: "Warehouse dispatch to carrier",
      departmentScope: "warehouse",
      complexityLevel: "standard",
    },
  ],
  approvalChains: [
    {
      key: "dispatch-chain",
      name: "Dispatch assignment",
      workflowKey: "dispatch-assign",
      steps: ["Dispatch Coordinator", "Logistics Operations Manager", "Executive / Owner"],
    },
    {
      key: "pod-chain",
      name: "Proof-of-delivery dispute",
      workflowKey: "pod-review",
      steps: ["Driver / Field Operator", "Dispatch Coordinator", "Customer Account Manager"],
    },
    {
      key: "exception-chain",
      name: "Delivery exception",
      workflowKey: "delivery-exception",
      steps: ["Dispatch Coordinator", "Compliance / Safety Officer", "Logistics Operations Manager"],
    },
    {
      key: "adjust-chain",
      name: "Stock adjustment",
      workflowKey: "stock-adjust-review",
      steps: ["Inventory Controller", "Warehouse Supervisor", "Logistics Operations Manager"],
    },
    {
      key: "supplier-chain",
      name: "Supplier purchase",
      workflowKey: "supplier-pr",
      steps: ["Procurement Specialist", "Finance Coordinator", "Logistics Operations Manager"],
    },
    {
      key: "cust-chain",
      name: "Customer escalation",
      workflowKey: "cust-issue-esc",
      steps: ["Customer Account Manager", "Logistics Operations Manager", "Executive / Owner"],
    },
    {
      key: "access-chain",
      name: "Role change review",
      workflowKey: "access-review",
      steps: ["IT / Security Administrator", "CyberCrow Security Reviewer", "Tenant Admin"],
    },
  ],
  cybercrowBaselines: [
    {
      key: "dispatch-change",
      name: "Unauthorized dispatch change readiness",
      controls: ["dispatch_assignment_trail", "route_change_approval"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "pod-dispute",
      name: "Proof-of-delivery dispute readiness",
      controls: ["pod_record", "delivery_exception_link"],
      riskFocus: "disputes",
      monitoringLevel: "elevated",
    },
    {
      key: "delivery-exception-fraud",
      name: "Delivery exception fraud readiness",
      controls: ["exception_reason_codes", "supervisor_signoff"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "inv-movement-abuse",
      name: "Inventory movement abuse readiness",
      controls: ["movement_audit", "adjustment_signoff"],
      riskFocus: "inventory_integrity",
      monitoringLevel: "elevated",
    },
    {
      key: "warehouse-access",
      name: "Warehouse access anomaly readiness",
      controls: ["warehouse_rbac", "after_hours_access"],
      riskFocus: "physical_digital",
      monitoringLevel: "standard",
    },
    {
      key: "supplier-fraud",
      name: "Supplier fraud readiness",
      controls: ["vendor_approval", "bank_detail_change"],
      riskFocus: "supply_chain",
      monitoringLevel: "standard",
    },
    {
      key: "customer-data",
      name: "Customer data exposure readiness",
      controls: ["crm_access_review", "pii_minimization"],
      riskFocus: "privacy",
      monitoringLevel: "standard",
    },
    {
      key: "driver-misuse",
      name: "Driver / account misuse readiness",
      controls: ["mobile_mfa", "route_scope", "device_trust"],
      riskFocus: "identity",
      monitoringLevel: "elevated",
    },
    {
      key: "mobile-workforce",
      name: "Mobile workforce monitoring (advisory)",
      controls: ["device_trust", "session_geo"],
      riskFocus: "field_operations",
      monitoringLevel: "elevated",
    },
    {
      key: "branch-boundary",
      name: "Branch-level access boundaries",
      controls: ["tenant_rbac", "branch_scope"],
      riskFocus: "access",
      monitoringLevel: "standard",
    },
    {
      key: "logistics-audit",
      name: "Logistics workflow audit trail",
      controls: ["audit_chain", "shipment_events"],
      riskFocus: "compliance",
      monitoringLevel: "standard",
    },
    {
      key: "privileged-monitor",
      name: "Privileged role monitoring",
      controls: ["admin_session", "approval_log", "role_change_log"],
      riskFocus: "privilege",
      monitoringLevel: "critical",
    },
  ],
  sareaProfiles: [
    {
      key: "exec-dash",
      name: "Executive / owner strategic view",
      positionKey: "exec-owner",
      experienceProfile: "Network KPIs, SLA health, risk posture",
      dashboardType: "strategic",
      complexityLevel: "executive",
      personaKey: "executive",
    },
    {
      key: "logistics-ops-dash",
      name: "Logistics operations control board",
      positionKey: "logistics-ops-mgr",
      experienceProfile: "Dispatch queues, exceptions, branch coordination",
      dashboardType: "control",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "dispatcher-dash",
      name: "Dispatch coordinator operational board",
      positionKey: "dispatch-coord",
      experienceProfile: "Live routes, assignments, delivery exceptions",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "warehouse-dash",
      name: "Warehouse supervisor dashboard",
      positionKey: "wh-sup",
      experienceProfile: "Inbound/outbound, staging, labor",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "driver-dash",
      name: "Driver / field operator mobile UI",
      positionKey: "driver",
      experienceProfile: "Tasks, routes, POD guidance (readiness)",
      dashboardType: "mobile",
      complexityLevel: "frontline",
      personaKey: "frontline",
    },
    {
      key: "acct-dash",
      name: "Customer account manager view",
      positionKey: "acct-mgr",
      experienceProfile: "Escalations, SLAs, open issues",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "analyst-dash",
      name: "Logistics analyst insights",
      positionKey: "analyst",
      experienceProfile: "Performance trends, reporting readiness",
      dashboardType: "analytical",
      complexityLevel: "specialist",
      personaKey: "analyst",
    },
    {
      key: "admin-dash",
      name: "Tenant admin configuration",
      positionKey: "tenant-admin",
      experienceProfile: "Users, roles, branches, access",
      dashboardType: "admin",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "cc-console",
      name: "CyberCrow security console",
      positionKey: "cc-analyst",
      experienceProfile: "Delivery audit, incidents, evidence gaps",
      dashboardType: "security",
      complexityLevel: "security",
      personaKey: "security",
    },
  ],
};

const CONSTRUCTION: OrgIntelligenceModel = {
  sectorTemplateKey: "construction",
  sectorName: "Construction & Projects",
  industry: "construction",
  maturityLevel: "growth",
  branchTypes: [
    { key: "hq", name: "Head office" },
    { key: "site", name: "Project site" },
    { key: "yard", name: "Equipment yard" },
  ],
  departments: [
    { key: "exec", name: "Executive Office", recommendedPriority: 1, recommendedHeadcount: { min: 2, max: 6 } },
    { key: "projects", name: "Project Management", recommendedPriority: 2, recommendedHeadcount: { min: 5, max: 40 } },
    { key: "engineering", name: "Engineering", recommendedPriority: 2, recommendedHeadcount: { min: 4, max: 30 } },
    { key: "procurement", name: "Procurement", recommendedPriority: 3, recommendedHeadcount: { min: 3, max: 15 } },
    { key: "equipment", name: "Equipment & plant", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 20 } },
    { key: "safety", name: "Health & Safety (HSE)", recommendedPriority: 2, recommendedHeadcount: { min: 2, max: 12 } },
    { key: "finance", name: "Finance", recommendedPriority: 4, recommendedHeadcount: { min: 3, max: 12 } },
    { key: "hr", name: "HR", recommendedPriority: 5, recommendedHeadcount: { min: 2, max: 10 } },
    { key: "security", name: "CyberCrow Security", recommendedPriority: 2, recommendedHeadcount: { min: 1, max: 4 } },
  ],
  positions: [
    { key: "pm", title: "Project Manager", departmentKey: "projects", level: "manager", responsibilities: ["Schedule", "Budget", "Stakeholders"], sareaPersonaKey: "manager" },
    { key: "site-mgr", title: "Site Manager", departmentKey: "projects", level: "manager", responsibilities: ["Site ops", "Contractors"], sareaPersonaKey: "manager", riskSensitive: true },
    { key: "engineer", title: "Site Engineer", departmentKey: "engineering", level: "specialist", responsibilities: ["Drawings", "QA", "RFIs"], sareaPersonaKey: "specialist" },
    { key: "safety-officer", title: "Safety Officer", departmentKey: "safety", level: "specialist", responsibilities: ["HSE inspections", "Incidents"], sareaPersonaKey: "specialist", cybercrowSensitive: true },
    { key: "proc-spec", title: "Procurement Specialist", departmentKey: "procurement", level: "specialist", responsibilities: ["PO workflow", "Vendors"], sareaPersonaKey: "specialist" },
    { key: "equip-coord", title: "Equipment Coordinator", departmentKey: "equipment", level: "specialist", responsibilities: ["Plant allocation", "Mobilization"], sareaPersonaKey: "specialist" },
    { key: "cc-analyst", title: "CyberCrow Analyst", departmentKey: "security", level: "specialist", responsibilities: ["Contractor access", "Audit review"], sareaPersonaKey: "security", cybercrowSensitive: true },
  ],
  workflows: [
    { key: "rfi", name: "RFI / change request", departmentScope: "projects", complexityLevel: "standard" },
    { key: "site-inspection", name: "Site HSE inspection", departmentScope: "safety", complexityLevel: "standard" },
    { key: "po-approval", name: "Purchase order approval", departmentScope: "procurement", complexityLevel: "advanced" },
    { key: "equip-mob", name: "Equipment mobilization", departmentScope: "equipment", complexityLevel: "lite" },
  ],
  approvalChains: [
    { key: "change-chain", name: "Change approval", workflowKey: "rfi", steps: ["Site Engineer", "Project Manager", "Executive"] },
    { key: "po-chain", name: "PO approval", workflowKey: "po-approval", steps: ["Procurement Specialist", "Project Manager", "Finance Manager"] },
  ],
  cybercrowBaselines: [
    { key: "site-access", name: "Site access control", controls: ["site_rbac", "contractor_access"], riskFocus: "physical_digital", monitoringLevel: "elevated" },
    { key: "vendor-trust", name: "Vendor access controls", controls: ["vendor_session", "approval_log"], riskFocus: "supply_chain", monitoringLevel: "standard" },
  ],
  sareaProfiles: [
    { key: "pm-dash", name: "Project manager dashboard", positionKey: "pm", experienceProfile: "Portfolio and milestones", dashboardType: "control", complexityLevel: "manager", personaKey: "manager" },
    { key: "site-dash", name: "Site manager field dashboard", positionKey: "site-mgr", experienceProfile: "Site KPIs, HSE, and crews", dashboardType: "mobile", complexityLevel: "manager", personaKey: "manager" },
    { key: "hse-dash", name: "HSE officer dashboard", positionKey: "safety-officer", experienceProfile: "Inspections and open findings", dashboardType: "operational", complexityLevel: "specialist", personaKey: "specialist" },
    { key: "cc-console", name: "CyberCrow security console", positionKey: "cc-analyst", experienceProfile: "Contractor access and incidents", dashboardType: "security", complexityLevel: "security", personaKey: "security" },
  ],
};

const AVIATION: OrgIntelligenceModel = {
  sectorTemplateKey: "aviation",
  sectorName: "Aviation Operations",
  industry: "aviation",
  maturityLevel: "enterprise",
  branchTypes: [
    { key: "hq", name: "Operations center" },
    { key: "station", name: "Station / airport" },
    { key: "mro", name: "MRO facility" },
  ],
  departments: [
    { key: "ops", name: "Operations control", recommendedPriority: 1, recommendedHeadcount: { min: 5, max: 50 } },
    { key: "ground", name: "Ground operations", recommendedPriority: 2, recommendedHeadcount: { min: 10, max: 80 } },
    { key: "maintenance", name: "Maintenance (MRO)", recommendedPriority: 2, recommendedHeadcount: { min: 8, max: 60 } },
    { key: "safety", name: "Safety & compliance", recommendedPriority: 2, recommendedHeadcount: { min: 3, max: 15 } },
    { key: "finance", name: "Finance", recommendedPriority: 4, recommendedHeadcount: { min: 3, max: 12 } },
    { key: "security", name: "CyberCrow Security", recommendedPriority: 2, recommendedHeadcount: { min: 2, max: 8 } },
  ],
  positions: [
    { key: "occ-mgr", title: "Operations Control Manager", departmentKey: "ops", level: "manager", responsibilities: ["Dispatch", "Irregular ops"], sareaPersonaKey: "manager", cybercrowSensitive: true },
    { key: "duty-mgr", title: "Duty Manager", departmentKey: "ops", level: "manager", responsibilities: ["Shift oversight", "Escalations"], sareaPersonaKey: "manager", riskSensitive: true },
    { key: "mro-lead", title: "MRO Lead", departmentKey: "maintenance", level: "manager", responsibilities: ["Work orders", "Airworthiness"], sareaPersonaKey: "manager" },
    { key: "ramp-sup", title: "Ramp Supervisor", departmentKey: "ground", level: "specialist", responsibilities: ["Turnaround", "Shift handover"], sareaPersonaKey: "specialist" },
    { key: "safety-officer", title: "Safety Officer", departmentKey: "safety", level: "specialist", responsibilities: ["Compliance", "Reporting"], sareaPersonaKey: "specialist", cybercrowSensitive: true },
    { key: "cc-analyst", title: "CyberCrow Analyst", departmentKey: "security", level: "specialist", responsibilities: ["OCC audit", "Evidence review"], sareaPersonaKey: "security", cybercrowSensitive: true },
  ],
  workflows: [
    { key: "disruption", name: "Disruption management", departmentScope: "ops", complexityLevel: "advanced" },
    { key: "work-order", name: "Maintenance work order", departmentScope: "maintenance", complexityLevel: "standard" },
    { key: "safety-report", name: "Safety report", departmentScope: "safety", complexityLevel: "standard" },
    { key: "shift-handover", name: "Shift handover", departmentScope: "ground", complexityLevel: "lite" },
  ],
  approvalChains: [
    { key: "mro-chain", name: "MRO release", workflowKey: "work-order", steps: ["Technician", "MRO Lead", "Safety Officer"] },
  ],
  cybercrowBaselines: [
    { key: "occ-audit", name: "Operations audit trail", controls: ["occ_events", "privileged_access"], riskFocus: "safety", monitoringLevel: "critical" },
    { key: "maintenance-evidence", name: "Maintenance evidence chain", controls: ["work_order_signoff"], riskFocus: "compliance", monitoringLevel: "elevated" },
  ],
  sareaProfiles: [
    { key: "occ-dash", name: "Operations control dashboard", positionKey: "occ-mgr", experienceProfile: "Fleet status and disruptions", dashboardType: "control", complexityLevel: "manager", personaKey: "manager" },
    { key: "ramp-dash", name: "Ramp supervisor shift board", positionKey: "ramp-sup", experienceProfile: "Turnaround tasks and handover", dashboardType: "operational", complexityLevel: "specialist", personaKey: "specialist" },
    { key: "cc-console", name: "CyberCrow security console", positionKey: "cc-analyst", experienceProfile: "OCC audit and maintenance evidence", dashboardType: "security", complexityLevel: "security", personaKey: "security" },
  ],
};

const HEALTHCARE: OrgIntelligenceModel = {
  sectorTemplateKey: "healthcare",
  sectorName: "Healthcare Network",
  industry: "healthcare",
  maturityLevel: "enterprise",
  branchTypes: [
    { key: "hq", name: "Administrative HQ" },
    { key: "clinic", name: "Clinic / facility" },
    { key: "lab", name: "Diagnostic lab" },
  ],
  departments: [
    { key: "clinical", name: "Clinical Operations", recommendedHeadcount: { min: 20, max: 200 } },
    { key: "nursing", name: "Nursing", recommendedHeadcount: { min: 15, max: 150 } },
    { key: "admin", name: "Administration", recommendedHeadcount: { min: 5, max: 30 } },
    { key: "finance", name: "Finance & Billing", recommendedHeadcount: { min: 4, max: 25 } },
    { key: "compliance", name: "Compliance", recommendedHeadcount: { min: 2, max: 12 } },
    { key: "security", name: "CyberCrow Security", recommendedHeadcount: { min: 2, max: 8 } },
  ],
  positions: [
    { key: "cmo", title: "Chief Medical Officer", departmentKey: "clinical", level: "executive", responsibilities: ["Clinical governance"], sareaPersonaKey: "executive", cybercrowSensitive: true },
    { key: "nurse-mgr", title: "Nursing Manager", departmentKey: "nursing", level: "manager", responsibilities: ["Staffing", "Patient flow"], sareaPersonaKey: "manager" },
    { key: "compliance-off", title: "Compliance Officer", departmentKey: "compliance", level: "specialist", responsibilities: ["HIPAA/NCA alignment"], sareaPersonaKey: "specialist", cybercrowSensitive: true },
  ],
  workflows: [
    { key: "patient-admit", name: "Patient admission", departmentScope: "clinical", complexityLevel: "standard" },
    { key: "incident-clinical", name: "Clinical incident", departmentScope: "compliance", complexityLevel: "advanced" },
  ],
  approvalChains: [
    { key: "clinical-chain", name: "Clinical escalation", workflowKey: "incident-clinical", steps: ["Frontline clinician", "Nursing Manager", "Compliance Officer"] },
  ],
  cybercrowBaselines: [
    { key: "phi-access", name: "PHI access monitoring", controls: ["phi_audit", "break_glass"], riskFocus: "privacy", monitoringLevel: "critical" },
    { key: "clinical-session", name: "Clinical session trust", controls: ["workstation_trust"], riskFocus: "identity", monitoringLevel: "elevated" },
  ],
  sareaProfiles: [
    { key: "exec-health", name: "Executive clinical overview", positionKey: "cmo", experienceProfile: "Network KPIs and compliance", dashboardType: "strategic", complexityLevel: "executive", personaKey: "executive" },
    { key: "nurse-ops", name: "Nursing operations dashboard", positionKey: "nurse-mgr", experienceProfile: "Patient flow and staffing", dashboardType: "operational", complexityLevel: "manager", personaKey: "manager" },
  ],
};

/** Live CEM catalog keys for retail operating model (no loyalty/ecommerce/POS modules). */
export const RETAIL_RECOMMENDED_CEM_MODULE_KEYS = [
  "sales",
  "crm",
  "inventory",
  "warehouse",
  "procurement",
  "finance",
  "hr",
  "approvals",
  "bi",
] as const;

/** ERP runtime keys (tasks → approvals, reports → bi per erp-module-registry). */
export const RETAIL_RECOMMENDED_ERP_MODULE_KEYS = [
  "sales",
  "crm",
  "inventory",
  "warehouse",
  "procurement",
  "finance",
  "hr",
  "tasks",
  "reports",
] as const;

/** Future integration / readiness only — not live CEM modules. */
export const RETAIL_FUTURE_READINESS_KEYS = [
  "loyalty",
  "ecommerce",
  "pos_integration",
  "payment_reconciliation",
  "advanced_bi",
] as const;

const RETAIL: OrgIntelligenceModel = {
  sectorTemplateKey: "retail",
  sectorName: "Retail Operating Model",
  industry: "retail",
  maturityLevel: "growth",
  branchTypes: [
    { key: "hq", name: "Head office", description: "Merchandising, finance, and shared services" },
    { key: "store", name: "Retail store", description: "Point of sale and floor operations" },
    { key: "dc", name: "Distribution center", description: "Inbound, picking, and outbound to stores" },
    { key: "ecom", name: "E-commerce fulfillment node", description: "Optional online order fulfillment (readiness)" },
  ],
  departments: [
    { key: "retail-ops", name: "Retail Operations", recommendedPriority: 1, recommendedHeadcount: { min: 3, max: 25 } },
    { key: "stores", name: "Store Management", recommendedPriority: 2, recommendedHeadcount: { min: 8, max: 120 } },
    { key: "merch", name: "Merchandising", recommendedPriority: 2, recommendedHeadcount: { min: 3, max: 25 } },
    { key: "inventory", name: "Inventory & Stock Control", recommendedPriority: 2, recommendedHeadcount: { min: 4, max: 40 } },
    { key: "procurement", name: "Procurement / Supplier Management", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 18 } },
    { key: "sales-crm", name: "Sales & CRM", recommendedPriority: 3, recommendedHeadcount: { min: 4, max: 30 } },
    { key: "cs", name: "Customer Service", recommendedPriority: 3, recommendedHeadcount: { min: 3, max: 25 } },
    { key: "finance", name: "Finance & Reconciliation", recommendedPriority: 4, recommendedHeadcount: { min: 3, max: 20 } },
    { key: "marketing", name: "Marketing / Promotions / Loyalty", recommendedPriority: 4, recommendedHeadcount: { min: 2, max: 15 } },
    { key: "hr", name: "HR / Workforce", recommendedPriority: 5, recommendedHeadcount: { min: 2, max: 12 } },
    { key: "it", name: "IT & Security", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 10 } },
    { key: "security", name: "CyberCrow Security", recommendedPriority: 2, recommendedHeadcount: { min: 1, max: 6 } },
  ],
  positions: [
    {
      key: "owner",
      title: "Executive / Business Owner",
      departmentKey: "retail-ops",
      level: "executive",
      responsibilities: ["Strategy", "Store network health", "Risk posture"],
      sareaPersonaKey: "executive",
      cybercrowSensitive: true,
    },
    {
      key: "retail-ops-mgr",
      title: "Retail Operations Manager",
      departmentKey: "retail-ops",
      level: "manager",
      responsibilities: ["Multi-store workflows", "Exceptions", "Branch coordination"],
      sareaPersonaKey: "manager",
      riskSensitive: true,
    },
    {
      key: "store-mgr",
      title: "Store Manager",
      departmentKey: "stores",
      level: "manager",
      responsibilities: ["Store P&L", "Staff scheduling", "Daily review"],
      sareaPersonaKey: "manager",
    },
    {
      key: "associate",
      title: "Sales Associate / Cashier",
      departmentKey: "stores",
      level: "frontline",
      responsibilities: ["POS guidance", "Customer escalation", "Assigned tasks"],
      sareaPersonaKey: "frontline",
      recommendedCountMin: 5,
      recommendedCountMax: 120,
    },
    {
      key: "inv-ctrl",
      title: "Inventory Controller",
      departmentKey: "inventory",
      level: "specialist",
      responsibilities: ["Receiving", "Counts", "Stock adjustments"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "merch-mgr",
      title: "Merchandiser",
      departmentKey: "merch",
      level: "manager",
      responsibilities: ["Assortment", "Pricing", "Planograms"],
      sareaPersonaKey: "manager",
    },
    {
      key: "buyer",
      title: "Buyer / Procurement Specialist",
      departmentKey: "procurement",
      level: "specialist",
      responsibilities: ["Supplier POs", "Replenishment", "Vendor terms"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "cs-agent",
      title: "Customer Service Agent",
      departmentKey: "cs",
      level: "specialist",
      responsibilities: ["Complaints", "Returns intake", "Escalation"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "finance-clerk",
      title: "Finance Clerk",
      departmentKey: "finance",
      level: "specialist",
      responsibilities: ["Cash reconciliation", "Refund review", "AR/AP support"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "loyalty-coord",
      title: "Marketing / Loyalty Coordinator",
      departmentKey: "marketing",
      level: "specialist",
      responsibilities: ["Promotions", "Campaign readiness", "Loyalty rules (advisory)"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "hr-coord",
      title: "HR Coordinator",
      departmentKey: "hr",
      level: "specialist",
      responsibilities: ["Hiring", "Shift compliance", "Policy"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "it-admin",
      title: "IT / Security Administrator",
      departmentKey: "it",
      level: "manager",
      responsibilities: ["Store systems", "Access requests", "Config"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "analyst",
      title: "Retail Analyst",
      departmentKey: "retail-ops",
      level: "specialist",
      responsibilities: ["Reports", "Trends", "Evidence gaps"],
      sareaPersonaKey: "analyst",
    },
    {
      key: "tenant-admin",
      title: "Tenant Admin",
      departmentKey: "it",
      level: "manager",
      responsibilities: ["Users", "Roles", "Tenant configuration"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "cc-analyst",
      title: "CyberCrow Analyst",
      departmentKey: "security",
      level: "specialist",
      responsibilities: ["Retail evidence review", "Incident triage", "Access reviews"],
      sareaPersonaKey: "security",
      cybercrowSensitive: true,
    },
  ],
  workflows: [
    { key: "catalog-onboard", name: "Product onboarding / catalog update", departmentScope: "merch", complexityLevel: "standard" },
    { key: "stock-receive", name: "Stock receiving", departmentScope: "inventory", complexityLevel: "standard" },
    { key: "inv-count", name: "Inventory count / stock adjustment", departmentScope: "inventory", complexityLevel: "standard" },
    { key: "replenish-req", name: "Replenishment request", departmentScope: "inventory", complexityLevel: "lite" },
    { key: "supplier-pr", name: "Supplier purchase request", departmentScope: "procurement", complexityLevel: "standard" },
    { key: "pos-summary", name: "Sales order / POS summary review", departmentScope: "finance", complexityLevel: "lite" },
    { key: "return-review", name: "Return / exchange review", departmentScope: "cs", complexityLevel: "standard" },
    { key: "promo-approval", name: "Discount / promotion approval", departmentScope: "marketing", complexityLevel: "standard" },
    { key: "complaint-esc", name: "Customer complaint escalation", departmentScope: "cs", complexityLevel: "standard" },
    { key: "cash-recon", name: "Cash reconciliation", departmentScope: "finance", complexityLevel: "advanced" },
    { key: "store-incident", name: "Store incident report", departmentScope: "security", complexityLevel: "standard" },
    { key: "perf-review", name: "Monthly retail performance review", departmentScope: "retail-ops", complexityLevel: "advanced" },
    { key: "stock-transfer", name: "Stock transfer (DC ↔ store)", departmentScope: "inventory", complexityLevel: "standard" },
    { key: "price-change", name: "Price change approval", departmentScope: "merch", complexityLevel: "standard" },
  ],
  approvalChains: [
    {
      key: "price-chain",
      name: "Pricing approval",
      workflowKey: "price-change",
      steps: ["Merchandiser", "Merchandising Manager", "Finance Manager"],
    },
    {
      key: "promo-chain",
      name: "Promotion approval",
      workflowKey: "promo-approval",
      steps: ["Marketing Coordinator", "Retail Operations Manager", "Finance Manager"],
    },
    {
      key: "return-chain",
      name: "Return / refund review",
      workflowKey: "return-review",
      steps: ["Customer Service Agent", "Store Manager", "Finance Clerk"],
    },
    {
      key: "adjust-chain",
      name: "Stock adjustment",
      workflowKey: "inv-count",
      steps: ["Inventory Controller", "Store Manager", "Retail Operations Manager"],
    },
    {
      key: "cash-chain",
      name: "Cash reconciliation",
      workflowKey: "cash-recon",
      steps: ["Finance Clerk", "Store Manager", "Finance Manager"],
    },
    {
      key: "supplier-chain",
      name: "Supplier purchase",
      workflowKey: "supplier-pr",
      steps: ["Buyer", "Procurement Lead", "Finance Manager"],
    },
  ],
  cybercrowBaselines: [
    {
      key: "pos-boundary",
      name: "POS / payment boundary readiness",
      controls: ["pos_role_separation", "payment_data_boundary"],
      riskFocus: "payment_boundary",
      monitoringLevel: "elevated",
    },
    {
      key: "refund-abuse",
      name: "Refund and return abuse readiness",
      controls: ["refund_approval_trail", "return_reason_codes"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "discount-override",
      name: "Discount override monitoring (advisory)",
      controls: ["discount_approval_log", "manager_override"],
      riskFocus: "fraud",
      monitoringLevel: "standard",
    },
    {
      key: "inv-adjust-audit",
      name: "Inventory adjustment audit trail",
      controls: ["stock_adjustment_signoff", "count_variance"],
      riskFocus: "inventory_integrity",
      monitoringLevel: "elevated",
    },
    {
      key: "store-access",
      name: "Store and branch access boundaries",
      controls: ["store_rbac", "branch_scope"],
      riskFocus: "access",
      monitoringLevel: "standard",
    },
    {
      key: "customer-privacy",
      name: "Customer data handling readiness",
      controls: ["crm_access_review", "pii_minimization"],
      riskFocus: "privacy",
      monitoringLevel: "standard",
    },
    {
      key: "privileged-retail",
      name: "Privileged retail role changes",
      controls: ["admin_session", "role_change_log"],
      riskFocus: "privilege",
      monitoringLevel: "critical",
    },
    {
      key: "supplier-fraud",
      name: "Supplier onboarding evidence",
      controls: ["vendor_approval", "bank_detail_change"],
      riskFocus: "supply_chain",
      monitoringLevel: "standard",
    },
  ],
  sareaProfiles: [
    {
      key: "exec-retail",
      name: "Executive / owner strategic view",
      positionKey: "owner",
      experienceProfile: "Revenue, store health, risk posture",
      dashboardType: "strategic",
      complexityLevel: "executive",
      personaKey: "executive",
    },
    {
      key: "retail-ops-dash",
      name: "Retail operations control board",
      positionKey: "retail-ops-mgr",
      experienceProfile: "Workflows, branches, tasks, exceptions",
      dashboardType: "control",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "store-dash",
      name: "Store manager operational dashboard",
      positionKey: "store-mgr",
      experienceProfile: "Daily tasks, stock issues, staff actions",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "associate-mobile",
      name: "Frontline associate mobile UI",
      positionKey: "associate",
      experienceProfile: "Assigned tasks, escalations, POS guidance (no live payments)",
      dashboardType: "mobile",
      complexityLevel: "frontline",
      personaKey: "frontline",
    },
    {
      key: "inventory-dash",
      name: "Inventory controller workspace",
      positionKey: "inv-ctrl",
      experienceProfile: "Receiving, adjustments, replenishment",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "analyst-dash",
      name: "Retail analyst insights",
      positionKey: "analyst",
      experienceProfile: "Reports, trends, evidence gaps",
      dashboardType: "analytical",
      complexityLevel: "specialist",
      personaKey: "analyst",
    },
    {
      key: "admin-dash",
      name: "Tenant admin configuration",
      positionKey: "tenant-admin",
      experienceProfile: "Users, roles, access, configuration",
      dashboardType: "admin",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "cc-console",
      name: "CyberCrow security console",
      positionKey: "cc-analyst",
      experienceProfile: "Retail evidence, incidents, access reviews",
      dashboardType: "security",
      complexityLevel: "security",
      personaKey: "security",
    },
  ],
};

export const SECTOR_TEMPLATE_CATALOG: Record<SectorTemplateKey, OrgIntelligenceModel> = {
  logistics: LOGISTICS,
  construction: CONSTRUCTION,
  aviation: AVIATION,
  healthcare: HEALTHCARE,
  retail: RETAIL,
};

export const SECTOR_TEMPLATE_KEYS = Object.keys(SECTOR_TEMPLATE_CATALOG) as SectorTemplateKey[];

export function getSectorTemplateModel(key: SectorTemplateKey): OrgIntelligenceModel {
  return structuredClone(SECTOR_TEMPLATE_CATALOG[key]);
}
