import type { OrgIntelligenceModel, SectorTemplateKey } from "@/lib/org-intelligence/types";

/** Live CEM catalog keys for logistics operating model (lighthouse / MEEM-aligned). */
export const LOGISTICS_RECOMMENDED_CEM_MODULE_KEYS = [
  "logistics",
  "warehouse",
  "inventory",
  "procurement",
  "crm",
  "finance",
  "hr",
  "sales",
  "approvals",
  "bi",
] as const;

/** ERP runtime keys (tasks → approvals, reports → bi per erp-module-registry). */
export const LOGISTICS_RECOMMENDED_ERP_MODULE_KEYS = [
  "logistics",
  "warehouse",
  "inventory",
  "procurement",
  "crm",
  "finance",
  "hr",
  "sales",
  "tasks",
  "reports",
] as const;

/** Future integration / readiness only — not live CEM modules. */
export const LOGISTICS_FUTURE_READINESS_KEYS = [
  "telematics_integration",
  "carrier_api_live",
  "route_optimization_saas",
  "live_pod_capture",
  "autonomous_dispatch",
] as const;

const LOGISTICS: OrgIntelligenceModel = {
  sectorTemplateKey: "logistics",
  sectorName: "Logistics Operating Model",
  industry: "logistics",
  maturityLevel: "growth",
  branchTypes: [
    { key: "hq", name: "Headquarters", description: "Executive and shared services" },
    { key: "hub", name: "Distribution hub", description: "Regional consolidation and cross-dock" },
    { key: "depot", name: "Fleet depot", description: "Vehicle and driver coordination" },
    { key: "warehouse", name: "Warehouse / DC", description: "Inventory movement and dispatch staging" },
    { key: "customer-site", name: "Customer delivery node", description: "Last-mile delivery context (readiness)" },
  ],
  departments: [
    { key: "exec", name: "Executive Office", recommendedPriority: 1, recommendedHeadcount: { min: 2, max: 8 } },
    {
      key: "logistics-ops",
      name: "Logistics Operations",
      recommendedPriority: 1,
      recommendedHeadcount: { min: 5, max: 45 },
    },
    {
      key: "dispatch",
      name: "Dispatch / Delivery Coordination",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 4, max: 35 },
    },
    {
      key: "fleet",
      name: "Fleet / Driver Coordination",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 4, max: 40 },
    },
    {
      key: "warehouse",
      name: "Warehouse Operations",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 8, max: 80 },
    },
    {
      key: "inventory",
      name: "Inventory Control",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 4, max: 30 },
    },
    {
      key: "procurement",
      name: "Procurement / Supplier Management",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 2, max: 18 },
    },
    {
      key: "crm-accts",
      name: "Customer Accounts / CRM",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 4, max: 28 },
    },
    {
      key: "finance",
      name: "Finance / Billing Coordination",
      recommendedPriority: 4,
      recommendedHeadcount: { min: 3, max: 18 },
    },
    { key: "hr", name: "HR / Workforce", recommendedPriority: 5, recommendedHeadcount: { min: 2, max: 14 } },
    {
      key: "compliance",
      name: "Compliance / Safety",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 2, max: 12 },
    },
    { key: "it", name: "IT & Security", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 10 } },
    { key: "security", name: "CyberCrow Security", recommendedPriority: 2, recommendedHeadcount: { min: 1, max: 6 } },
  ],
  positions: [
    {
      key: "exec-owner",
      title: "Executive / Owner",
      departmentKey: "exec",
      level: "executive",
      responsibilities: ["Strategy", "Network KPIs", "Risk posture"],
      sareaPersonaKey: "executive",
      cybercrowSensitive: true,
    },
    {
      key: "logistics-ops-mgr",
      title: "Logistics Operations Manager",
      departmentKey: "logistics-ops",
      level: "manager",
      responsibilities: ["SLA governance", "Multi-branch coordination", "Exception handling"],
      sareaPersonaKey: "manager",
      riskSensitive: true,
    },
    {
      key: "dispatch-coord",
      title: "Dispatch Coordinator",
      departmentKey: "dispatch",
      level: "specialist",
      responsibilities: ["Route assignment", "Delivery scheduling", "Live status updates"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "driver",
      title: "Driver / Field Operator",
      departmentKey: "fleet",
      level: "frontline",
      responsibilities: ["Deliveries", "Task updates", "Vehicle checks"],
      sareaPersonaKey: "frontline",
      cybercrowSensitive: true,
      recommendedCountMin: 5,
      recommendedCountMax: 120,
    },
    {
      key: "wh-sup",
      title: "Warehouse Supervisor",
      departmentKey: "warehouse",
      level: "manager",
      responsibilities: ["Inbound/outbound", "Labor planning", "Dispatch staging"],
      sareaPersonaKey: "manager",
    },
    {
      key: "inv-ctrl",
      title: "Inventory Controller",
      departmentKey: "inventory",
      level: "specialist",
      responsibilities: ["Stock accuracy", "Movements", "Cycle counts"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "proc-spec",
      title: "Procurement Specialist",
      departmentKey: "procurement",
      level: "specialist",
      responsibilities: ["Supplier requests", "PO coordination", "Vendor evidence"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "acct-mgr",
      title: "Customer Account Manager",
      departmentKey: "crm-accts",
      level: "manager",
      responsibilities: ["Key accounts", "Escalations", "Service levels"],
      sareaPersonaKey: "manager",
    },
    {
      key: "finance-coord",
      title: "Finance Coordinator",
      departmentKey: "finance",
      level: "specialist",
      responsibilities: ["Billing coordination", "Approvals", "Cost allocation"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "hr-coord",
      title: "HR Coordinator",
      departmentKey: "hr",
      level: "specialist",
      responsibilities: ["Onboarding", "Workforce scheduling", "Policy"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "compliance-officer",
      title: "Compliance / Safety Officer",
      departmentKey: "compliance",
      level: "specialist",
      responsibilities: ["Safety process", "Incident review", "Audit support"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "it-admin",
      title: "IT / Security Administrator",
      departmentKey: "it",
      level: "specialist",
      responsibilities: ["Access provisioning", "Integration readiness", "Device policy"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "analyst",
      title: "Analyst",
      departmentKey: "logistics-ops",
      level: "specialist",
      responsibilities: ["Performance reporting", "Trend analysis", "Evidence gaps"],
      sareaPersonaKey: "analyst",
    },
    {
      key: "tenant-admin",
      title: "Tenant Admin",
      departmentKey: "exec",
      level: "manager",
      responsibilities: ["Tenant config", "User access", "Role assignments"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "cc-analyst",
      title: "CyberCrow Security Reviewer",
      departmentKey: "security",
      level: "specialist",
      responsibilities: ["Delivery audit", "Incident triage", "Access reviews"],
      sareaPersonaKey: "security",
      cybercrowSensitive: true,
    },
  ],
  workflows: [
    {
      key: "delivery-intake",
      name: "Delivery request intake",
      departmentScope: "dispatch",
      complexityLevel: "standard",
    },
    {
      key: "dispatch-assign",
      name: "Dispatch assignment",
      departmentScope: "dispatch",
      complexityLevel: "standard",
    },
    {
      key: "driver-task-update",
      name: "Driver task update",
      departmentScope: "fleet",
      complexityLevel: "lite",
    },
    {
      key: "shipment-status",
      name: "Shipment status update",
      departmentScope: "logistics-ops",
      complexityLevel: "lite",
    },
    {
      key: "wh-receiving",
      name: "Warehouse receiving",
      departmentScope: "warehouse",
      complexityLevel: "standard",
    },
    {
      key: "inv-movement",
      name: "Inventory movement",
      departmentScope: "inventory",
      complexityLevel: "standard",
    },
    {
      key: "stock-adjust-review",
      name: "Stock adjustment review",
      departmentScope: "inventory",
      complexityLevel: "standard",
    },
    {
      key: "supplier-pr",
      name: "Supplier purchase request",
      departmentScope: "procurement",
      complexityLevel: "standard",
    },
    {
      key: "cust-issue-esc",
      name: "Customer issue escalation",
      departmentScope: "crm-accts",
      complexityLevel: "standard",
    },
    {
      key: "delivery-exception",
      name: "Delivery exception / incident report",
      departmentScope: "compliance",
      complexityLevel: "advanced",
    },
    {
      key: "pod-review",
      name: "Proof-of-delivery review",
      departmentScope: "dispatch",
      complexityLevel: "standard",
    },
    {
      key: "logistics-perf",
      name: "Monthly logistics performance review",
      departmentScope: "logistics-ops",
      complexityLevel: "advanced",
    },
    {
      key: "access-review",
      name: "Access review / role change review",
      departmentScope: "security",
      complexityLevel: "standard",
    },
    {
      key: "route-approval",
      name: "Route approval",
      departmentScope: "fleet",
      complexityLevel: "standard",
    },
    {
      key: "wh-dispatch",
      name: "Warehouse dispatch to carrier",
      departmentScope: "warehouse",
      complexityLevel: "standard",
    },
  ],
  approvalChains: [
    {
      key: "dispatch-chain",
      name: "Dispatch assignment",
      workflowKey: "dispatch-assign",
      steps: ["Dispatch Coordinator", "Logistics Operations Manager", "Executive / Owner"],
    },
    {
      key: "pod-chain",
      name: "Proof-of-delivery dispute",
      workflowKey: "pod-review",
      steps: ["Driver / Field Operator", "Dispatch Coordinator", "Customer Account Manager"],
    },
    {
      key: "exception-chain",
      name: "Delivery exception",
      workflowKey: "delivery-exception",
      steps: ["Dispatch Coordinator", "Compliance / Safety Officer", "Logistics Operations Manager"],
    },
    {
      key: "adjust-chain",
      name: "Stock adjustment",
      workflowKey: "stock-adjust-review",
      steps: ["Inventory Controller", "Warehouse Supervisor", "Logistics Operations Manager"],
    },
    {
      key: "supplier-chain",
      name: "Supplier purchase",
      workflowKey: "supplier-pr",
      steps: ["Procurement Specialist", "Finance Coordinator", "Logistics Operations Manager"],
    },
    {
      key: "cust-chain",
      name: "Customer escalation",
      workflowKey: "cust-issue-esc",
      steps: ["Customer Account Manager", "Logistics Operations Manager", "Executive / Owner"],
    },
    {
      key: "access-chain",
      name: "Role change review",
      workflowKey: "access-review",
      steps: ["IT / Security Administrator", "CyberCrow Security Reviewer", "Tenant Admin"],
    },
  ],
  cybercrowBaselines: [
    {
      key: "dispatch-change",
      name: "Unauthorized dispatch change readiness",
      controls: ["dispatch_assignment_trail", "route_change_approval"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "pod-dispute",
      name: "Proof-of-delivery dispute readiness",
      controls: ["pod_record", "delivery_exception_link"],
      riskFocus: "disputes",
      monitoringLevel: "elevated",
    },
    {
      key: "delivery-exception-fraud",
      name: "Delivery exception fraud readiness",
      controls: ["exception_reason_codes", "supervisor_signoff"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "inv-movement-abuse",
      name: "Inventory movement abuse readiness",
      controls: ["movement_audit", "adjustment_signoff"],
      riskFocus: "inventory_integrity",
      monitoringLevel: "elevated",
    },
    {
      key: "warehouse-access",
      name: "Warehouse access anomaly readiness",
      controls: ["warehouse_rbac", "after_hours_access"],
      riskFocus: "physical_digital",
      monitoringLevel: "standard",
    },
    {
      key: "supplier-fraud",
      name: "Supplier fraud readiness",
      controls: ["vendor_approval", "bank_detail_change"],
      riskFocus: "supply_chain",
      monitoringLevel: "standard",
    },
    {
      key: "customer-data",
      name: "Customer data exposure readiness",
      controls: ["crm_access_review", "pii_minimization"],
      riskFocus: "privacy",
      monitoringLevel: "standard",
    },
    {
      key: "driver-misuse",
      name: "Driver / account misuse readiness",
      controls: ["mobile_mfa", "route_scope", "device_trust"],
      riskFocus: "identity",
      monitoringLevel: "elevated",
    },
    {
      key: "mobile-workforce",
      name: "Mobile workforce monitoring (advisory)",
      controls: ["device_trust", "session_geo"],
      riskFocus: "field_operations",
      monitoringLevel: "elevated",
    },
    {
      key: "branch-boundary",
      name: "Branch-level access boundaries",
      controls: ["tenant_rbac", "branch_scope"],
      riskFocus: "access",
      monitoringLevel: "standard",
    },
    {
      key: "logistics-audit",
      name: "Logistics workflow audit trail",
      controls: ["audit_chain", "shipment_events"],
      riskFocus: "compliance",
      monitoringLevel: "standard",
    },
    {
      key: "privileged-monitor",
      name: "Privileged role monitoring",
      controls: ["admin_session", "approval_log", "role_change_log"],
      riskFocus: "privilege",
      monitoringLevel: "critical",
    },
  ],
  sareaProfiles: [
    {
      key: "exec-dash",
      name: "Executive / owner strategic view",
      positionKey: "exec-owner",
      experienceProfile: "Network KPIs, SLA health, risk posture",
      dashboardType: "strategic",
      complexityLevel: "executive",
      personaKey: "executive",
    },
    {
      key: "logistics-ops-dash",
      name: "Logistics operations control board",
      positionKey: "logistics-ops-mgr",
      experienceProfile: "Dispatch queues, exceptions, branch coordination",
      dashboardType: "control",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "dispatcher-dash",
      name: "Dispatch coordinator operational board",
      positionKey: "dispatch-coord",
      experienceProfile: "Live routes, assignments, delivery exceptions",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "warehouse-dash",
      name: "Warehouse supervisor dashboard",
      positionKey: "wh-sup",
      experienceProfile: "Inbound/outbound, staging, labor",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "driver-dash",
      name: "Driver / field operator mobile UI",
      positionKey: "driver",
      experienceProfile: "Tasks, routes, POD guidance (readiness)",
      dashboardType: "mobile",
      complexityLevel: "frontline",
      personaKey: "frontline",
    },
    {
      key: "acct-dash",
      name: "Customer account manager view",
      positionKey: "acct-mgr",
      experienceProfile: "Escalations, SLAs, open issues",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "analyst-dash",
      name: "Logistics analyst insights",
      positionKey: "analyst",
      experienceProfile: "Performance trends, reporting readiness",
      dashboardType: "analytical",
      complexityLevel: "specialist",
      personaKey: "analyst",
    },
    {
      key: "admin-dash",
      name: "Tenant admin configuration",
      positionKey: "tenant-admin",
      experienceProfile: "Users, roles, branches, access",
      dashboardType: "admin",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "cc-console",
      name: "CyberCrow security console",
      positionKey: "cc-analyst",
      experienceProfile: "Delivery audit, incidents, evidence gaps",
      dashboardType: "security",
      complexityLevel: "security",
      personaKey: "security",
    },
  ],
};

/** Live CEM catalog keys for construction operating model (Rimal-aligned). */
export const CONSTRUCTION_RECOMMENDED_CEM_MODULE_KEYS = [
  "procurement",
  "inventory",
  "finance",
  "hr",
  "crm",
  "sales",
  "approvals",
  "bi",
] as const;

/** ERP runtime keys (tasks → approvals, reports → bi). */
export const CONSTRUCTION_RECOMMENDED_ERP_MODULE_KEYS = [
  "procurement",
  "inventory",
  "finance",
  "hr",
  "crm",
  "sales",
  "tasks",
  "reports",
] as const;

/** Future integration / readiness only — not live CEM modules. */
export const CONSTRUCTION_FUTURE_READINESS_KEYS = [
  "document_management_integration",
  "bim_integration",
  "equipment_tracking",
  "subcontractor_portal",
  "field_mobile_app",
  "advanced_project_scheduling",
] as const;

const CONSTRUCTION: OrgIntelligenceModel = {
  sectorTemplateKey: "construction",
  sectorName: "Construction Operating Model",
  industry: "construction",
  maturityLevel: "growth",
  branchTypes: [
    { key: "hq", name: "Head office", description: "Executive and shared services" },
    { key: "site", name: "Project site", description: "Active construction site operations" },
    { key: "yard", name: "Equipment / materials yard", description: "Plant and materials staging" },
    { key: "project-office", name: "Project office", description: "Site-adjacent coordination hub (readiness)" },
  ],
  departments: [
    { key: "exec", name: "Executive Office", recommendedPriority: 1, recommendedHeadcount: { min: 2, max: 8 } },
    {
      key: "projects",
      name: "Project Management",
      recommendedPriority: 1,
      recommendedHeadcount: { min: 5, max: 45 },
    },
    {
      key: "site-ops",
      name: "Site Operations",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 6, max: 60 },
    },
    {
      key: "engineering",
      name: "Engineering / Technical Office",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 4, max: 35 },
    },
    {
      key: "procurement",
      name: "Procurement / Supplier Management",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 3, max: 20 },
    },
    {
      key: "materials",
      name: "Materials / Inventory Control",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 3, max: 25 },
    },
    {
      key: "finance",
      name: "Finance / Cost Control",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 3, max: 18 },
    },
    { key: "hr", name: "HR / Workforce", recommendedPriority: 4, recommendedHeadcount: { min: 2, max: 14 } },
    {
      key: "hse",
      name: "Health, Safety & Environment",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 2, max: 15 },
    },
    {
      key: "quality",
      name: "Quality Control",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 2, max: 12 },
    },
    {
      key: "doc-control",
      name: "Document Control",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 2, max: 10 },
    },
    { key: "it", name: "IT & Security", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 8 } },
    { key: "security", name: "CyberCrow Security", recommendedPriority: 2, recommendedHeadcount: { min: 1, max: 6 } },
  ],
  positions: [
    {
      key: "exec-owner",
      title: "Executive / Owner",
      departmentKey: "exec",
      level: "executive",
      responsibilities: ["Portfolio strategy", "Risk posture", "Major approvals"],
      sareaPersonaKey: "executive",
      cybercrowSensitive: true,
    },
    {
      key: "pm",
      title: "Project Manager",
      departmentKey: "projects",
      level: "manager",
      responsibilities: ["Schedule", "Budget", "Stakeholders", "Variations"],
      sareaPersonaKey: "manager",
      riskSensitive: true,
    },
    {
      key: "site-mgr",
      title: "Site Manager",
      departmentKey: "site-ops",
      level: "manager",
      responsibilities: ["Site crews", "Daily reporting", "Mobilization"],
      sareaPersonaKey: "manager",
      riskSensitive: true,
    },
    {
      key: "site-eng",
      title: "Site Engineer",
      departmentKey: "site-ops",
      level: "specialist",
      responsibilities: ["Site technical issues", "RFIs", "Field coordination"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "tech-office-eng",
      title: "Technical Office Engineer",
      departmentKey: "engineering",
      level: "specialist",
      responsibilities: ["Drawings", "Submittals", "Technical reviews"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "proc-spec",
      title: "Procurement Specialist",
      departmentKey: "procurement",
      level: "specialist",
      responsibilities: ["Purchase requests", "Supplier coordination", "PO workflow"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "materials-ctrl",
      title: "Materials Controller",
      departmentKey: "materials",
      level: "specialist",
      responsibilities: ["Material requests", "Receiving", "Stock accuracy"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "finance-ctrl",
      title: "Finance / Cost Controller",
      departmentKey: "finance",
      level: "specialist",
      responsibilities: ["Cost tracking", "Budget vs actual", "Billing coordination"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "hr-coord",
      title: "HR Coordinator",
      departmentKey: "hr",
      level: "specialist",
      responsibilities: ["Workforce requests", "Onboarding", "Scheduling"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "hse-officer",
      title: "HSE Officer",
      departmentKey: "hse",
      level: "specialist",
      responsibilities: ["Inspections", "Incidents", "Corrective actions"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "quality-insp",
      title: "Quality Inspector",
      departmentKey: "quality",
      level: "specialist",
      responsibilities: ["Inspections", "Non-conformance", "Sign-off"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "doc-ctrl",
      title: "Document Controller",
      departmentKey: "doc-control",
      level: "specialist",
      responsibilities: ["Submittals", "Approvals", "Version control"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "it-admin",
      title: "IT / Security Administrator",
      departmentKey: "it",
      level: "specialist",
      responsibilities: ["Access provisioning", "Integration readiness"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "analyst",
      title: "Analyst",
      departmentKey: "projects",
      level: "specialist",
      responsibilities: ["Project reporting", "Trend analysis", "Readiness gaps"],
      sareaPersonaKey: "analyst",
    },
    {
      key: "tenant-admin",
      title: "Tenant Admin",
      departmentKey: "exec",
      level: "manager",
      responsibilities: ["Users", "Roles", "Mappings"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "cc-analyst",
      title: "CyberCrow Security Reviewer",
      departmentKey: "security",
      level: "specialist",
      responsibilities: ["Site access", "Evidence review", "Audit support"],
      sareaPersonaKey: "security",
      cybercrowSensitive: true,
    },
  ],
  workflows: [
    { key: "project-kickoff", name: "Project kickoff", departmentScope: "projects", complexityLevel: "standard" },
    { key: "site-mobilization", name: "Site mobilization", departmentScope: "site-ops", complexityLevel: "standard" },
    { key: "material-request", name: "Material request", departmentScope: "materials", complexityLevel: "standard" },
    { key: "purchase-request", name: "Purchase request", departmentScope: "procurement", complexityLevel: "standard" },
    { key: "supplier-approval", name: "Supplier approval", departmentScope: "procurement", complexityLevel: "standard" },
    { key: "material-receiving", name: "Material receiving", departmentScope: "materials", complexityLevel: "standard" },
    { key: "site-task-assign", name: "Site task assignment", departmentScope: "site-ops", complexityLevel: "lite" },
    { key: "daily-site-report", name: "Daily site report", departmentScope: "site-ops", complexityLevel: "lite" },
    { key: "hse-incident", name: "HSE incident report", departmentScope: "hse", complexityLevel: "advanced" },
    { key: "quality-inspection", name: "Quality inspection", departmentScope: "quality", complexityLevel: "standard" },
    {
      key: "variation-change",
      name: "Variation / change request",
      departmentScope: "projects",
      complexityLevel: "advanced",
    },
    {
      key: "document-approval",
      name: "Document submission / approval",
      departmentScope: "doc-control",
      complexityLevel: "standard",
    },
    { key: "cost-review", name: "Cost review", departmentScope: "finance", complexityLevel: "standard" },
    { key: "workforce-request", name: "Workforce request", departmentScope: "hr", complexityLevel: "lite" },
    {
      key: "project-perf-review",
      name: "Monthly project performance review",
      departmentScope: "projects",
      complexityLevel: "advanced",
    },
    { key: "access-review", name: "Access / role review", departmentScope: "security", complexityLevel: "standard" },
  ],
  approvalChains: [
    {
      key: "material-chain",
      name: "Material request",
      workflowKey: "material-request",
      steps: ["Materials Controller", "Project Manager", "Finance / Cost Controller"],
    },
    {
      key: "purchase-chain",
      name: "Purchase request",
      workflowKey: "purchase-request",
      steps: ["Procurement Specialist", "Project Manager", "Finance / Cost Controller"],
    },
    {
      key: "supplier-chain",
      name: "Supplier approval",
      workflowKey: "supplier-approval",
      steps: ["Procurement Specialist", "Project Manager", "Executive / Owner"],
    },
    {
      key: "variation-chain",
      name: "Variation / change",
      workflowKey: "variation-change",
      steps: ["Site Engineer", "Project Manager", "Executive / Owner"],
    },
    {
      key: "document-chain",
      name: "Document approval",
      workflowKey: "document-approval",
      steps: ["Document Controller", "Technical Office Engineer", "Project Manager"],
    },
    {
      key: "hse-chain",
      name: "HSE incident",
      workflowKey: "hse-incident",
      steps: ["Site Manager", "HSE Officer", "Project Manager"],
    },
    {
      key: "access-chain",
      name: "Access review",
      workflowKey: "access-review",
      steps: ["IT / Security Administrator", "CyberCrow Security Reviewer", "Tenant Admin"],
    },
  ],
  cybercrowBaselines: [
    {
      key: "unauthorized-purchase",
      name: "Unauthorized purchase request readiness",
      controls: ["purchase_approval_trail", "spend_limit"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "supplier-approval-abuse",
      name: "Supplier / subcontractor approval abuse readiness",
      controls: ["vendor_onboarding", "approval_log"],
      riskFocus: "supply_chain",
      monitoringLevel: "elevated",
    },
    {
      key: "material-receiving-fraud",
      name: "Material receiving fraud readiness",
      controls: ["grn_record", "receiving_signoff"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "material-adjust-abuse",
      name: "Material / inventory adjustment abuse readiness",
      controls: ["adjustment_approval", "movement_audit"],
      riskFocus: "inventory_integrity",
      monitoringLevel: "elevated",
    },
    {
      key: "document-approval-gap",
      name: "Document approval gap readiness",
      controls: ["submittal_trail", "version_control"],
      riskFocus: "compliance",
      monitoringLevel: "standard",
    },
    {
      key: "hse-underreport",
      name: "HSE incident underreporting readiness",
      controls: ["incident_log", "supervisor_signoff"],
      riskFocus: "safety",
      monitoringLevel: "elevated",
    },
    {
      key: "quality-gap",
      name: "Quality inspection gap readiness",
      controls: ["inspection_record", "ncr_trail"],
      riskFocus: "quality",
      monitoringLevel: "standard",
    },
    {
      key: "site-access-anomaly",
      name: "Site access anomaly readiness",
      controls: ["site_rbac", "contractor_access"],
      riskFocus: "physical_digital",
      monitoringLevel: "elevated",
    },
    {
      key: "role-change-abuse",
      name: "Project role change abuse readiness",
      controls: ["role_change_log", "access_review"],
      riskFocus: "privilege",
      monitoringLevel: "elevated",
    },
    {
      key: "variation-abuse",
      name: "Cost / variation approval abuse readiness",
      controls: ["variation_approval", "budget_impact"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "project-data-exposure",
      name: "Customer / project data exposure readiness",
      controls: ["crm_access_review", "project_scope"],
      riskFocus: "privacy",
      monitoringLevel: "standard",
    },
    {
      key: "site-access",
      name: "Site access control (advisory)",
      controls: ["site_rbac", "contractor_access"],
      riskFocus: "physical_digital",
      monitoringLevel: "elevated",
    },
    {
      key: "vendor-trust",
      name: "Vendor access controls (advisory)",
      controls: ["vendor_session", "approval_log"],
      riskFocus: "supply_chain",
      monitoringLevel: "standard",
    },
  ],
  sareaProfiles: [
    {
      key: "exec-dash",
      name: "Executive / owner portfolio view",
      positionKey: "exec-owner",
      experienceProfile: "Project health, HSE open items, cost posture",
      dashboardType: "strategic",
      complexityLevel: "executive",
      personaKey: "executive",
    },
    {
      key: "pm-dash",
      name: "Project manager control board",
      positionKey: "pm",
      experienceProfile: "Workflows, tasks, cost readiness, variations",
      dashboardType: "control",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "site-dash",
      name: "Site manager field board",
      positionKey: "site-mgr",
      experienceProfile: "Site actions, daily reporting, crews",
      dashboardType: "mobile",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "site-eng-dash",
      name: "Site engineer task view",
      positionKey: "site-eng",
      experienceProfile: "Field tasks and technical coordination",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "proc-dash",
      name: "Procurement specialist workflow view",
      positionKey: "proc-spec",
      experienceProfile: "Purchase and supplier approvals",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "materials-dash",
      name: "Materials controller inventory view",
      positionKey: "materials-ctrl",
      experienceProfile: "Material requests and receiving",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "hse-quality-dash",
      name: "HSE / quality reviewer console",
      positionKey: "hse-officer",
      experienceProfile: "Incidents, inspections, evidence readiness",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "analyst-dash",
      name: "Construction analyst reporting",
      positionKey: "analyst",
      experienceProfile: "Project performance and readiness trends",
      dashboardType: "analytical",
      complexityLevel: "specialist",
      personaKey: "analyst",
    },
    {
      key: "admin-dash",
      name: "Tenant admin workspace",
      positionKey: "tenant-admin",
      experienceProfile: "Users, roles, mappings",
      dashboardType: "admin",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "cc-console",
      name: "CyberCrow security console",
      positionKey: "cc-analyst",
      experienceProfile: "Site access, incidents, evidence gaps",
      dashboardType: "security",
      complexityLevel: "security",
      personaKey: "security",
    },
  ],
};

/** Live CEM catalog keys for aviation operating model (service/station ops — no logistics/warehouse stack). */
export const AVIATION_RECOMMENDED_CEM_MODULE_KEYS = [
  "crm",
  "sales",
  "procurement",
  "finance",
  "hr",
  "approvals",
  "bi",
] as const;

/** ERP runtime keys (tasks → approvals, reports → bi per erp-module-registry). */
export const AVIATION_RECOMMENDED_ERP_MODULE_KEYS = [
  "crm",
  "sales",
  "procurement",
  "finance",
  "hr",
  "tasks",
  "reports",
] as const;

/** Future integration / readiness only — not live CEM modules. */
export const AVIATION_FUTURE_READINESS_KEYS = [
  "flight_operations_integration",
  "airport_systems_integration",
  "maintenance_system_integration",
  "iot_sensor_telemetry",
  "passenger_self_service_portal",
  "live_compliance_integrations",
  "advanced_bi",
] as const;

const AVIATION: OrgIntelligenceModel = {
  sectorTemplateKey: "aviation",
  sectorName: "Aviation Operating Model",
  industry: "aviation",
  maturityLevel: "enterprise",
  branchTypes: [
    { key: "hq", name: "Operations center", description: "Network oversight and shared services" },
    { key: "station", name: "Station / airport", description: "Ground and passenger service location" },
    { key: "service-center", name: "Service center", description: "Customer service and coordination hub" },
  ],
  departments: [
    { key: "exec", name: "Executive Office", recommendedPriority: 1, recommendedHeadcount: { min: 2, max: 12 } },
    {
      key: "aviation-ops",
      name: "Aviation Operations",
      recommendedPriority: 1,
      recommendedHeadcount: { min: 5, max: 50 },
    },
    {
      key: "ground-ops",
      name: "Ground Operations",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 10, max: 80 },
    },
    {
      key: "pax-service",
      name: "Passenger / Customer Service",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 8, max: 60 },
    },
    {
      key: "maintenance-coord",
      name: "Maintenance Coordination",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 6, max: 45 },
    },
    {
      key: "safety-compliance",
      name: "Safety / Compliance",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 3, max: 18 },
    },
    {
      key: "procurement",
      name: "Procurement / Supplier Management",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 3, max: 20 },
    },
    {
      key: "finance",
      name: "Finance / Billing Coordination",
      recommendedPriority: 4,
      recommendedHeadcount: { min: 3, max: 15 },
    },
    {
      key: "hr",
      name: "HR / Workforce Scheduling",
      recommendedPriority: 4,
      recommendedHeadcount: { min: 3, max: 15 },
    },
    {
      key: "quality",
      name: "Quality / Service Assurance",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 3, max: 15 },
    },
    { key: "it", name: "IT / CyberCrow Security", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 10 } },
    {
      key: "reporting",
      name: "Reporting / Analytics",
      recommendedPriority: 4,
      recommendedHeadcount: { min: 2, max: 10 },
    },
  ],
  positions: [
    {
      key: "owner",
      title: "Executive Viewer / Owner",
      departmentKey: "exec",
      level: "executive",
      responsibilities: ["Network health", "Risk posture", "Executive reporting"],
      sareaPersonaKey: "executive",
      cybercrowSensitive: true,
    },
    {
      key: "av-ops-mgr",
      title: "Aviation Operations Manager",
      departmentKey: "aviation-ops",
      level: "manager",
      responsibilities: ["Service coordination", "Exceptions", "Station alignment"],
      sareaPersonaKey: "manager",
      riskSensitive: true,
      cybercrowSensitive: true,
    },
    {
      key: "ground-coord",
      title: "Ground Operations Coordinator",
      departmentKey: "ground-ops",
      level: "manager",
      responsibilities: ["Ground tasks", "Shift handover", "Station ops"],
      sareaPersonaKey: "manager",
    },
    {
      key: "cs-supervisor",
      title: "Customer Service Supervisor",
      departmentKey: "pax-service",
      level: "manager",
      responsibilities: ["Escalations", "Service quality", "Team scheduling"],
      sareaPersonaKey: "manager",
    },
    {
      key: "pax-agent",
      title: "Passenger Service Agent",
      departmentKey: "pax-service",
      level: "frontline",
      responsibilities: ["Service requests", "Issue intake", "Customer follow-up"],
      sareaPersonaKey: "frontline",
      recommendedCountMin: 5,
      recommendedCountMax: 80,
    },
    {
      key: "maint-coord",
      title: "Maintenance Coordinator",
      departmentKey: "maintenance-coord",
      level: "specialist",
      responsibilities: ["Maintenance requests", "Vendor coordination", "Review items"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "safety-officer",
      title: "Safety / Compliance Officer",
      departmentKey: "safety-compliance",
      level: "specialist",
      responsibilities: ["Incidents", "Compliance readiness", "Evidence"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "proc-spec",
      title: "Procurement Specialist",
      departmentKey: "procurement",
      level: "specialist",
      responsibilities: ["Supplier requests", "Approvals", "Vendor coordination"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "finance-coord",
      title: "Finance Coordinator",
      departmentKey: "finance",
      level: "specialist",
      responsibilities: ["Billing review", "Cost coordination", "Month-end"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "hr-coord",
      title: "HR / Workforce Coordinator",
      departmentKey: "hr",
      level: "specialist",
      responsibilities: ["Shift requests", "Scheduling", "Workforce changes"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "quality-reviewer",
      title: "Quality Reviewer",
      departmentKey: "quality",
      level: "specialist",
      responsibilities: ["Service reviews", "Inspections", "Corrective actions"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "it-admin",
      title: "IT / Security Administrator",
      departmentKey: "it",
      level: "specialist",
      responsibilities: ["Access provisioning", "Station scope", "Integration readiness"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "analyst",
      title: "Analyst",
      departmentKey: "reporting",
      level: "specialist",
      responsibilities: ["Operations reporting", "Readiness gaps", "Trend review"],
      sareaPersonaKey: "analyst",
    },
    {
      key: "tenant-admin",
      title: "Tenant Admin",
      departmentKey: "exec",
      level: "manager",
      responsibilities: ["Users", "Roles", "Mappings"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "cc-analyst",
      title: "CyberCrow Security Reviewer",
      departmentKey: "it",
      level: "specialist",
      responsibilities: ["Access review", "Incident evidence", "Audit support"],
      sareaPersonaKey: "security",
      cybercrowSensitive: true,
    },
  ],
  workflows: [
    {
      key: "service-request-intake",
      name: "Service request intake",
      departmentScope: "pax-service",
      complexityLevel: "standard",
    },
    {
      key: "customer-escalation",
      name: "Passenger / customer issue escalation",
      departmentScope: "pax-service",
      complexityLevel: "standard",
    },
    {
      key: "ground-task-assign",
      name: "Ground operation task assignment",
      departmentScope: "ground-ops",
      complexityLevel: "lite",
    },
    {
      key: "maintenance-review",
      name: "Maintenance request review",
      departmentScope: "maintenance-coord",
      complexityLevel: "standard",
    },
    {
      key: "supplier-request",
      name: "Supplier request",
      departmentScope: "procurement",
      complexityLevel: "standard",
    },
    {
      key: "safety-incident",
      name: "Safety incident report",
      departmentScope: "safety-compliance",
      complexityLevel: "advanced",
    },
    {
      key: "quality-review",
      name: "Quality / service review",
      departmentScope: "quality",
      complexityLevel: "standard",
    },
    {
      key: "workforce-shift",
      name: "Workforce / shift request",
      departmentScope: "hr",
      complexityLevel: "lite",
    },
    { key: "access-review", name: "Access / role review", departmentScope: "it", complexityLevel: "standard" },
    {
      key: "finance-billing",
      name: "Finance / billing review",
      departmentScope: "finance",
      complexityLevel: "standard",
    },
    {
      key: "monthly-ops-report",
      name: "Monthly aviation operations report",
      departmentScope: "reporting",
      complexityLevel: "advanced",
    },
    {
      key: "cybercrow-incident-review",
      name: "CyberCrow incident review",
      departmentScope: "it",
      complexityLevel: "advanced",
    },
  ],
  approvalChains: [
    {
      key: "service-chain",
      name: "Service request",
      workflowKey: "service-request-intake",
      steps: ["Passenger Service Agent", "Customer Service Supervisor", "Aviation Operations Manager"],
    },
    {
      key: "escalation-chain",
      name: "Customer escalation",
      workflowKey: "customer-escalation",
      steps: ["Passenger Service Agent", "Customer Service Supervisor", "Executive Viewer / Owner"],
    },
    {
      key: "maintenance-chain",
      name: "Maintenance request",
      workflowKey: "maintenance-review",
      steps: ["Maintenance Coordinator", "Safety / Compliance Officer", "Aviation Operations Manager"],
    },
    {
      key: "supplier-chain",
      name: "Supplier request",
      workflowKey: "supplier-request",
      steps: ["Procurement Specialist", "Finance Coordinator", "Aviation Operations Manager"],
    },
    {
      key: "safety-chain",
      name: "Safety incident",
      workflowKey: "safety-incident",
      steps: ["Safety / Compliance Officer", "Aviation Operations Manager", "Executive Viewer / Owner"],
    },
    {
      key: "access-chain",
      name: "Access review",
      workflowKey: "access-review",
      steps: ["IT / Security Administrator", "CyberCrow Security Reviewer", "Tenant Admin"],
    },
  ],
  cybercrowBaselines: [
    {
      key: "role-change-abuse",
      name: "Unauthorized role / access change readiness",
      controls: ["access_review", "privileged_role_log"],
      riskFocus: "identity",
      monitoringLevel: "critical",
    },
    {
      key: "service-request-manipulation",
      name: "Service request manipulation readiness",
      controls: ["request_trail", "escalation_log"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "safety-underreport",
      name: "Safety incident underreporting readiness",
      controls: ["incident_report", "closure_tracking"],
      riskFocus: "safety",
      monitoringLevel: "critical",
    },
    {
      key: "maintenance-gap",
      name: "Maintenance request gap readiness",
      controls: ["maintenance_request_record", "review_signoff"],
      riskFocus: "operations",
      monitoringLevel: "elevated",
    },
    {
      key: "pax-data-exposure",
      name: "Passenger / customer data exposure readiness",
      controls: ["pii_access", "station_scope"],
      riskFocus: "privacy",
      monitoringLevel: "critical",
    },
    {
      key: "supplier-approval-abuse",
      name: "Supplier approval abuse readiness",
      controls: ["supplier_approval_trail", "vendor_onboarding"],
      riskFocus: "supply_chain",
      monitoringLevel: "elevated",
    },
    {
      key: "workforce-misuse",
      name: "Workforce / shift misuse readiness",
      controls: ["shift_request_log", "schedule_change"],
      riskFocus: "operations",
      monitoringLevel: "elevated",
    },
    {
      key: "escalation-audit-gap",
      name: "Service escalation audit gap readiness",
      controls: ["escalation_record", "supervisor_signoff"],
      riskFocus: "compliance",
      monitoringLevel: "elevated",
    },
    {
      key: "admin-misuse",
      name: "Privileged admin misuse readiness",
      controls: ["admin_action_log", "break_glass"],
      riskFocus: "identity",
      monitoringLevel: "critical",
    },
    {
      key: "station-access-anomaly",
      name: "Branch / station access anomaly readiness",
      controls: ["station_rbac", "location_scope"],
      riskFocus: "access",
      monitoringLevel: "elevated",
    },
  ],
  sareaProfiles: [
    {
      key: "exec-dash",
      name: "Executive operations health",
      positionKey: "owner",
      experienceProfile: "Network health, open safety items, service risk posture",
      dashboardType: "strategic",
      complexityLevel: "executive",
      personaKey: "executive",
    },
    {
      key: "ops-board",
      name: "Aviation operations control board",
      positionKey: "av-ops-mgr",
      experienceProfile: "Workflows, service tasks, exceptions, readiness",
      dashboardType: "control",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "ground-board",
      name: "Ground operations task board",
      positionKey: "ground-coord",
      experienceProfile: "Assigned operational tasks and shift handover",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "cs-queue",
      name: "Customer service escalation queue",
      positionKey: "cs-supervisor",
      experienceProfile: "Escalations and service requests",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "pax-mobile",
      name: "Passenger service agent workspace",
      positionKey: "pax-agent",
      experienceProfile: "Intake and follow-up tasks — mobile-first",
      dashboardType: "operational",
      complexityLevel: "frontline",
      personaKey: "frontline",
    },
    {
      key: "maint-review",
      name: "Maintenance coordination review",
      positionKey: "maint-coord",
      experienceProfile: "Maintenance requests and vendor review items",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "safety-quality",
      name: "Safety and quality evidence",
      positionKey: "safety-officer",
      experienceProfile: "Incidents, inspections, evidence trails",
      dashboardType: "compliance",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "analyst-readiness",
      name: "Analyst reporting readiness",
      positionKey: "analyst",
      experienceProfile: "Monthly ops report and readiness gaps",
      dashboardType: "analytical",
      complexityLevel: "specialist",
      personaKey: "analyst",
    },
    {
      key: "tenant-admin-hub",
      name: "Tenant admin hub",
      positionKey: "tenant-admin",
      experienceProfile: "Users, roles, SAREA mappings",
      dashboardType: "admin",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "cc-console",
      name: "CyberCrow security console",
      positionKey: "cc-analyst",
      experienceProfile: "Access review, incident evidence, audit trails",
      dashboardType: "security",
      complexityLevel: "security",
      personaKey: "security",
    },
  ],
};

/** Live CEM catalog keys for healthcare operating model (clinic ops — not logistics/retail stack). */
export const HEALTHCARE_RECOMMENDED_CEM_MODULE_KEYS = [
  "crm",
  "sales",
  "procurement",
  "finance",
  "hr",
  "approvals",
  "bi",
] as const;

/** ERP runtime keys (tasks → approvals, reports → bi per erp-module-registry). */
export const HEALTHCARE_RECOMMENDED_ERP_MODULE_KEYS = [
  "crm",
  "sales",
  "procurement",
  "finance",
  "hr",
  "tasks",
  "reports",
] as const;

/** Future integration / readiness only — not live CEM modules. */
export const HEALTHCARE_FUTURE_READINESS_KEYS = [
  "emr_ehr_integration",
  "appointment_system_integration",
  "pharmacy_system_integration",
  "insurance_integration",
  "patient_portal",
  "lab_system_integration",
  "clinical_decision_support",
  "medical_device_iot",
  "advanced_healthcare_compliance_automation",
] as const;

const HEALTHCARE: OrgIntelligenceModel = {
  sectorTemplateKey: "healthcare",
  sectorName: "Healthcare Operating Model",
  industry: "healthcare",
  maturityLevel: "enterprise",
  branchTypes: [
    { key: "hq", name: "Administrative HQ", description: "Network oversight and shared services" },
    { key: "clinic", name: "Clinic / facility", description: "Outpatient or clinic location" },
    { key: "lab", name: "Diagnostic lab", description: "Optional lab or diagnostic node (readiness)" },
  ],
  departments: [
    { key: "exec", name: "Executive Office", recommendedPriority: 1, recommendedHeadcount: { min: 2, max: 12 } },
    {
      key: "hc-ops",
      name: "Clinic / Healthcare Operations",
      recommendedPriority: 1,
      recommendedHeadcount: { min: 5, max: 40 },
    },
    {
      key: "patient-services",
      name: "Patient Services",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 8, max: 60 },
    },
    {
      key: "front-desk",
      name: "Appointment / Front Desk Coordination",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 6, max: 45 },
    },
    {
      key: "medical-staff",
      name: "Medical Staff Coordination",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 4, max: 35 },
    },
    {
      key: "nursing-care",
      name: "Nursing / Care Coordination",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 10, max: 80 },
    },
    {
      key: "pharmacy-supplies",
      name: "Pharmacy / Supplies Readiness",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 4, max: 30 },
    },
    {
      key: "procurement",
      name: "Procurement / Supplier Management",
      recommendedPriority: 3,
      recommendedHeadcount: { min: 3, max: 20 },
    },
    {
      key: "finance",
      name: "Finance / Billing Coordination",
      recommendedPriority: 4,
      recommendedHeadcount: { min: 4, max: 25 },
    },
    { key: "hr", name: "HR / Workforce", recommendedPriority: 4, recommendedHeadcount: { min: 3, max: 20 } },
    {
      key: "quality-safety",
      name: "Quality / Patient Safety",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 3, max: 18 },
    },
    {
      key: "privacy-compliance",
      name: "Privacy / Compliance",
      recommendedPriority: 2,
      recommendedHeadcount: { min: 2, max: 12 },
    },
    { key: "it", name: "IT / CyberCrow Security", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 10 } },
    {
      key: "reporting",
      name: "Reporting / Analytics",
      recommendedPriority: 4,
      recommendedHeadcount: { min: 2, max: 10 },
    },
  ],
  positions: [
    {
      key: "owner",
      title: "Executive Viewer / Owner",
      departmentKey: "exec",
      level: "executive",
      responsibilities: ["Network health", "Privacy posture", "Executive reporting"],
      sareaPersonaKey: "executive",
      cybercrowSensitive: true,
    },
    {
      key: "hc-ops-mgr",
      title: "Healthcare Operations Manager",
      departmentKey: "hc-ops",
      level: "manager",
      responsibilities: ["Clinic coordination", "Exceptions", "Branch alignment"],
      sareaPersonaKey: "manager",
      riskSensitive: true,
      cybercrowSensitive: true,
    },
    {
      key: "clinic-mgr",
      title: "Clinic Manager",
      departmentKey: "hc-ops",
      level: "manager",
      responsibilities: ["Daily clinic ops", "Staff coordination", "Service backlog"],
      sareaPersonaKey: "manager",
    },
    {
      key: "front-desk-coord",
      title: "Front Desk Coordinator",
      departmentKey: "front-desk",
      level: "manager",
      responsibilities: ["Appointments", "Check-in coordination", "Queue management"],
      sareaPersonaKey: "manager",
    },
    {
      key: "patient-agent",
      title: "Patient Service Agent",
      departmentKey: "patient-services",
      level: "frontline",
      responsibilities: ["Service requests", "Issue intake", "Follow-up"],
      sareaPersonaKey: "frontline",
      recommendedCountMin: 5,
      recommendedCountMax: 80,
    },
    {
      key: "medical-coord",
      title: "Medical Staff Coordinator",
      departmentKey: "medical-staff",
      level: "specialist",
      responsibilities: ["Staff schedules", "Coverage requests", "Coordination handoffs"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "nursing-coord",
      title: "Nursing Coordinator",
      departmentKey: "nursing-care",
      level: "manager",
      responsibilities: ["Care coordination", "Shift coverage", "Escalations"],
      sareaPersonaKey: "manager",
    },
    {
      key: "pharmacy-coord",
      title: "Pharmacy / Supplies Coordinator",
      departmentKey: "pharmacy-supplies",
      level: "specialist",
      responsibilities: ["Supplies requests", "Stock readiness", "Vendor coordination"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "proc-spec",
      title: "Procurement Specialist",
      departmentKey: "procurement",
      level: "specialist",
      responsibilities: ["Supplier requests", "Approvals", "Vendor terms"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "finance-coord",
      title: "Finance Coordinator",
      departmentKey: "finance",
      level: "specialist",
      responsibilities: ["Billing review", "Cost coordination", "Month-end"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "hr-coord",
      title: "HR Coordinator",
      departmentKey: "hr",
      level: "specialist",
      responsibilities: ["Workforce requests", "Scheduling", "Policy"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "quality-reviewer",
      title: "Quality / Safety Reviewer",
      departmentKey: "quality-safety",
      level: "specialist",
      responsibilities: ["Incidents", "Quality reviews", "Corrective actions"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "privacy-reviewer",
      title: "Privacy / Compliance Reviewer",
      departmentKey: "privacy-compliance",
      level: "specialist",
      responsibilities: ["Access reviews", "Privacy readiness", "Policy alignment (advisory)"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "it-admin",
      title: "IT / Security Administrator",
      departmentKey: "it",
      level: "specialist",
      responsibilities: ["Access provisioning", "Branch scope", "Integration readiness"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "analyst",
      title: "Analyst",
      departmentKey: "reporting",
      level: "specialist",
      responsibilities: ["Operations reporting", "Readiness gaps", "Trend review"],
      sareaPersonaKey: "analyst",
    },
    {
      key: "tenant-admin",
      title: "Tenant Admin",
      departmentKey: "exec",
      level: "manager",
      responsibilities: ["Users", "Roles", "Mappings"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "cc-analyst",
      title: "CyberCrow Security Reviewer",
      departmentKey: "it",
      level: "specialist",
      responsibilities: ["Access review", "Incident evidence", "Audit support"],
      sareaPersonaKey: "security",
      cybercrowSensitive: true,
    },
  ],
  workflows: [
    {
      key: "patient-service-intake",
      name: "Patient service request intake",
      departmentScope: "patient-services",
      complexityLevel: "standard",
    },
    {
      key: "appointment-coord",
      name: "Appointment request coordination",
      departmentScope: "front-desk",
      complexityLevel: "standard",
    },
    {
      key: "patient-escalation",
      name: "Patient issue escalation",
      departmentScope: "patient-services",
      complexityLevel: "standard",
    },
    {
      key: "workforce-request",
      name: "Staff schedule / workforce request",
      departmentScope: "hr",
      complexityLevel: "lite",
    },
    {
      key: "supplies-request",
      name: "Supplies request",
      departmentScope: "pharmacy-supplies",
      complexityLevel: "standard",
    },
    {
      key: "supplier-purchase",
      name: "Supplier purchase request",
      departmentScope: "procurement",
      complexityLevel: "standard",
    },
    {
      key: "safety-incident",
      name: "Incident / safety report",
      departmentScope: "quality-safety",
      complexityLevel: "advanced",
    },
    {
      key: "quality-review",
      name: "Quality review",
      departmentScope: "quality-safety",
      complexityLevel: "standard",
    },
    {
      key: "privacy-access-review",
      name: "Privacy access review",
      departmentScope: "privacy-compliance",
      complexityLevel: "standard",
    },
    {
      key: "billing-finance-review",
      name: "Billing / finance review",
      departmentScope: "finance",
      complexityLevel: "standard",
    },
    {
      key: "role-access-review",
      name: "Role / access change review",
      departmentScope: "it",
      complexityLevel: "standard",
    },
    {
      key: "monthly-hc-report",
      name: "Monthly healthcare operations report",
      departmentScope: "reporting",
      complexityLevel: "advanced",
    },
    {
      key: "cybercrow-incident-review",
      name: "CyberCrow incident review",
      departmentScope: "it",
      complexityLevel: "advanced",
    },
  ],
  approvalChains: [
    {
      key: "service-chain",
      name: "Patient service request",
      workflowKey: "patient-service-intake",
      steps: ["Patient Service Agent", "Healthcare Operations Manager", "Clinic Manager"],
    },
    {
      key: "escalation-chain",
      name: "Patient escalation",
      workflowKey: "patient-escalation",
      steps: ["Patient Service Agent", "Healthcare Operations Manager", "Executive Viewer / Owner"],
    },
    {
      key: "supplies-chain",
      name: "Supplies request",
      workflowKey: "supplies-request",
      steps: ["Pharmacy / Supplies Coordinator", "Procurement Specialist", "Healthcare Operations Manager"],
    },
    {
      key: "supplier-chain",
      name: "Supplier purchase",
      workflowKey: "supplier-purchase",
      steps: ["Procurement Specialist", "Finance Coordinator", "Healthcare Operations Manager"],
    },
    {
      key: "safety-chain",
      name: "Incident / safety",
      workflowKey: "safety-incident",
      steps: ["Quality / Safety Reviewer", "Privacy / Compliance Reviewer", "Executive Viewer / Owner"],
    },
    {
      key: "access-chain",
      name: "Role / access change",
      workflowKey: "role-access-review",
      steps: ["IT / Security Administrator", "CyberCrow Security Reviewer", "Tenant Admin"],
    },
  ],
  cybercrowBaselines: [
    {
      key: "sensitive-access",
      name: "Unauthorized access to sensitive records readiness",
      controls: ["access_review", "privileged_role_log"],
      riskFocus: "privacy",
      monitoringLevel: "critical",
    },
    {
      key: "role-change-abuse",
      name: "Role / access change abuse readiness",
      controls: ["role_change_approval", "admin_action_log"],
      riskFocus: "identity",
      monitoringLevel: "critical",
    },
    {
      key: "patient-data-exposure",
      name: "Patient / customer data exposure readiness",
      controls: ["pii_access", "branch_scope"],
      riskFocus: "privacy",
      monitoringLevel: "critical",
    },
    {
      key: "appointment-manipulation",
      name: "Appointment / request manipulation readiness",
      controls: ["appointment_trail", "request_log"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "safety-underreport",
      name: "Safety incident underreporting readiness",
      controls: ["incident_report", "closure_tracking"],
      riskFocus: "safety",
      monitoringLevel: "critical",
    },
    {
      key: "supplier-abuse",
      name: "Supplier / procurement abuse readiness",
      controls: ["supplier_approval_trail", "vendor_onboarding"],
      riskFocus: "supply_chain",
      monitoringLevel: "elevated",
    },
    {
      key: "billing-gap",
      name: "Billing / finance review gap readiness",
      controls: ["billing_review_record", "finance_signoff"],
      riskFocus: "compliance",
      monitoringLevel: "elevated",
    },
    {
      key: "access-audit-gap",
      name: "Access review audit gap readiness",
      controls: ["access_review_record", "privacy_signoff"],
      riskFocus: "compliance",
      monitoringLevel: "elevated",
    },
    {
      key: "admin-misuse",
      name: "Privileged admin misuse readiness",
      controls: ["admin_action_log", "break_glass"],
      riskFocus: "identity",
      monitoringLevel: "critical",
    },
    {
      key: "branch-access-anomaly",
      name: "Branch / location access anomaly readiness",
      controls: ["branch_rbac", "location_scope"],
      riskFocus: "access",
      monitoringLevel: "elevated",
    },
  ],
  sareaProfiles: [
    {
      key: "exec-dash",
      name: "Executive operations health",
      positionKey: "owner",
      experienceProfile: "Network health, open safety items, privacy posture",
      dashboardType: "strategic",
      complexityLevel: "executive",
      personaKey: "executive",
    },
    {
      key: "ops-board",
      name: "Healthcare operations control board",
      positionKey: "hc-ops-mgr",
      experienceProfile: "Workflows, service tasks, exceptions, readiness",
      dashboardType: "control",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "clinic-board",
      name: "Clinic manager operations board",
      positionKey: "clinic-mgr",
      experienceProfile: "Daily clinic backlog and staff coordination",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "front-desk-queue",
      name: "Front desk / patient services queue",
      positionKey: "front-desk-coord",
      experienceProfile: "Appointments and service requests",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "patient-workspace",
      name: "Patient service agent workspace",
      positionKey: "patient-agent",
      experienceProfile: "Intake and follow-up — minimal sensitive detail on screen",
      dashboardType: "operational",
      complexityLevel: "frontline",
      personaKey: "frontline",
    },
    {
      key: "medical-coord-board",
      name: "Medical staff coordination board",
      positionKey: "medical-coord",
      experienceProfile: "Schedule and coverage requests",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "nursing-board",
      name: "Nursing / care coordination board",
      positionKey: "nursing-coord",
      experienceProfile: "Care tasks and escalations",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "supplies-board",
      name: "Pharmacy / supplies coordination",
      positionKey: "pharmacy-coord",
      experienceProfile: "Supplies requests and readiness items",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "safety-quality",
      name: "Quality / safety evidence",
      positionKey: "quality-reviewer",
      experienceProfile: "Incidents, quality reviews, evidence trails",
      dashboardType: "compliance",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "privacy-console",
      name: "Privacy / compliance review console",
      positionKey: "privacy-reviewer",
      experienceProfile: "Access reviews and privacy readiness notes",
      dashboardType: "compliance",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "analyst-readiness",
      name: "Analyst reporting readiness",
      positionKey: "analyst",
      experienceProfile: "Monthly ops report and readiness gaps",
      dashboardType: "analytical",
      complexityLevel: "specialist",
      personaKey: "analyst",
    },
    {
      key: "tenant-admin-hub",
      name: "Tenant admin hub",
      positionKey: "tenant-admin",
      experienceProfile: "Users, roles, SAREA mappings",
      dashboardType: "admin",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "cc-console",
      name: "CyberCrow security console",
      positionKey: "cc-analyst",
      experienceProfile: "Access review, incident evidence, audit trails",
      dashboardType: "security",
      complexityLevel: "security",
      personaKey: "security",
    },
  ],
};

/** Live CEM catalog keys for retail operating model (no loyalty/ecommerce/POS modules). */
export const RETAIL_RECOMMENDED_CEM_MODULE_KEYS = [
  "sales",
  "crm",
  "inventory",
  "warehouse",
  "procurement",
  "finance",
  "hr",
  "approvals",
  "bi",
] as const;

/** ERP runtime keys (tasks → approvals, reports → bi per erp-module-registry). */
export const RETAIL_RECOMMENDED_ERP_MODULE_KEYS = [
  "sales",
  "crm",
  "inventory",
  "warehouse",
  "procurement",
  "finance",
  "hr",
  "tasks",
  "reports",
] as const;

/** Future integration / readiness only — not live CEM modules. */
export const RETAIL_FUTURE_READINESS_KEYS = [
  "loyalty",
  "ecommerce",
  "pos_integration",
  "payment_reconciliation",
  "advanced_bi",
] as const;

const RETAIL: OrgIntelligenceModel = {
  sectorTemplateKey: "retail",
  sectorName: "Retail Operating Model",
  industry: "retail",
  maturityLevel: "growth",
  branchTypes: [
    { key: "hq", name: "Head office", description: "Merchandising, finance, and shared services" },
    { key: "store", name: "Retail store", description: "Point of sale and floor operations" },
    { key: "dc", name: "Distribution center", description: "Inbound, picking, and outbound to stores" },
    { key: "ecom", name: "E-commerce fulfillment node", description: "Optional online order fulfillment (readiness)" },
  ],
  departments: [
    { key: "retail-ops", name: "Retail Operations", recommendedPriority: 1, recommendedHeadcount: { min: 3, max: 25 } },
    { key: "stores", name: "Store Management", recommendedPriority: 2, recommendedHeadcount: { min: 8, max: 120 } },
    { key: "merch", name: "Merchandising", recommendedPriority: 2, recommendedHeadcount: { min: 3, max: 25 } },
    { key: "inventory", name: "Inventory & Stock Control", recommendedPriority: 2, recommendedHeadcount: { min: 4, max: 40 } },
    { key: "procurement", name: "Procurement / Supplier Management", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 18 } },
    { key: "sales-crm", name: "Sales & CRM", recommendedPriority: 3, recommendedHeadcount: { min: 4, max: 30 } },
    { key: "cs", name: "Customer Service", recommendedPriority: 3, recommendedHeadcount: { min: 3, max: 25 } },
    { key: "finance", name: "Finance & Reconciliation", recommendedPriority: 4, recommendedHeadcount: { min: 3, max: 20 } },
    { key: "marketing", name: "Marketing / Promotions / Loyalty", recommendedPriority: 4, recommendedHeadcount: { min: 2, max: 15 } },
    { key: "hr", name: "HR / Workforce", recommendedPriority: 5, recommendedHeadcount: { min: 2, max: 12 } },
    { key: "it", name: "IT & Security", recommendedPriority: 3, recommendedHeadcount: { min: 2, max: 10 } },
    { key: "security", name: "CyberCrow Security", recommendedPriority: 2, recommendedHeadcount: { min: 1, max: 6 } },
  ],
  positions: [
    {
      key: "owner",
      title: "Executive / Business Owner",
      departmentKey: "retail-ops",
      level: "executive",
      responsibilities: ["Strategy", "Store network health", "Risk posture"],
      sareaPersonaKey: "executive",
      cybercrowSensitive: true,
    },
    {
      key: "retail-ops-mgr",
      title: "Retail Operations Manager",
      departmentKey: "retail-ops",
      level: "manager",
      responsibilities: ["Multi-store workflows", "Exceptions", "Branch coordination"],
      sareaPersonaKey: "manager",
      riskSensitive: true,
    },
    {
      key: "store-mgr",
      title: "Store Manager",
      departmentKey: "stores",
      level: "manager",
      responsibilities: ["Store P&L", "Staff scheduling", "Daily review"],
      sareaPersonaKey: "manager",
    },
    {
      key: "associate",
      title: "Sales Associate / Cashier",
      departmentKey: "stores",
      level: "frontline",
      responsibilities: ["POS guidance", "Customer escalation", "Assigned tasks"],
      sareaPersonaKey: "frontline",
      recommendedCountMin: 5,
      recommendedCountMax: 120,
    },
    {
      key: "inv-ctrl",
      title: "Inventory Controller",
      departmentKey: "inventory",
      level: "specialist",
      responsibilities: ["Receiving", "Counts", "Stock adjustments"],
      sareaPersonaKey: "specialist",
      riskSensitive: true,
    },
    {
      key: "merch-mgr",
      title: "Merchandiser",
      departmentKey: "merch",
      level: "manager",
      responsibilities: ["Assortment", "Pricing", "Planograms"],
      sareaPersonaKey: "manager",
    },
    {
      key: "buyer",
      title: "Buyer / Procurement Specialist",
      departmentKey: "procurement",
      level: "specialist",
      responsibilities: ["Supplier POs", "Replenishment", "Vendor terms"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "cs-agent",
      title: "Customer Service Agent",
      departmentKey: "cs",
      level: "specialist",
      responsibilities: ["Complaints", "Returns intake", "Escalation"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "finance-clerk",
      title: "Finance Clerk",
      departmentKey: "finance",
      level: "specialist",
      responsibilities: ["Cash reconciliation", "Refund review", "AR/AP support"],
      sareaPersonaKey: "specialist",
      cybercrowSensitive: true,
    },
    {
      key: "loyalty-coord",
      title: "Marketing / Loyalty Coordinator",
      departmentKey: "marketing",
      level: "specialist",
      responsibilities: ["Promotions", "Campaign readiness", "Loyalty rules (advisory)"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "hr-coord",
      title: "HR Coordinator",
      departmentKey: "hr",
      level: "specialist",
      responsibilities: ["Hiring", "Shift compliance", "Policy"],
      sareaPersonaKey: "specialist",
    },
    {
      key: "it-admin",
      title: "IT / Security Administrator",
      departmentKey: "it",
      level: "manager",
      responsibilities: ["Store systems", "Access requests", "Config"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "analyst",
      title: "Retail Analyst",
      departmentKey: "retail-ops",
      level: "specialist",
      responsibilities: ["Reports", "Trends", "Evidence gaps"],
      sareaPersonaKey: "analyst",
    },
    {
      key: "tenant-admin",
      title: "Tenant Admin",
      departmentKey: "it",
      level: "manager",
      responsibilities: ["Users", "Roles", "Tenant configuration"],
      sareaPersonaKey: "manager",
      cybercrowSensitive: true,
    },
    {
      key: "cc-analyst",
      title: "CyberCrow Analyst",
      departmentKey: "security",
      level: "specialist",
      responsibilities: ["Retail evidence review", "Incident triage", "Access reviews"],
      sareaPersonaKey: "security",
      cybercrowSensitive: true,
    },
  ],
  workflows: [
    { key: "catalog-onboard", name: "Product onboarding / catalog update", departmentScope: "merch", complexityLevel: "standard" },
    { key: "stock-receive", name: "Stock receiving", departmentScope: "inventory", complexityLevel: "standard" },
    { key: "inv-count", name: "Inventory count / stock adjustment", departmentScope: "inventory", complexityLevel: "standard" },
    { key: "replenish-req", name: "Replenishment request", departmentScope: "inventory", complexityLevel: "lite" },
    { key: "supplier-pr", name: "Supplier purchase request", departmentScope: "procurement", complexityLevel: "standard" },
    { key: "pos-summary", name: "Sales order / POS summary review", departmentScope: "finance", complexityLevel: "lite" },
    { key: "return-review", name: "Return / exchange review", departmentScope: "cs", complexityLevel: "standard" },
    { key: "promo-approval", name: "Discount / promotion approval", departmentScope: "marketing", complexityLevel: "standard" },
    { key: "complaint-esc", name: "Customer complaint escalation", departmentScope: "cs", complexityLevel: "standard" },
    { key: "cash-recon", name: "Cash reconciliation", departmentScope: "finance", complexityLevel: "advanced" },
    { key: "store-incident", name: "Store incident report", departmentScope: "security", complexityLevel: "standard" },
    { key: "perf-review", name: "Monthly retail performance review", departmentScope: "retail-ops", complexityLevel: "advanced" },
    { key: "stock-transfer", name: "Stock transfer (DC ↔ store)", departmentScope: "inventory", complexityLevel: "standard" },
    { key: "price-change", name: "Price change approval", departmentScope: "merch", complexityLevel: "standard" },
  ],
  approvalChains: [
    {
      key: "price-chain",
      name: "Pricing approval",
      workflowKey: "price-change",
      steps: ["Merchandiser", "Merchandising Manager", "Finance Manager"],
    },
    {
      key: "promo-chain",
      name: "Promotion approval",
      workflowKey: "promo-approval",
      steps: ["Marketing Coordinator", "Retail Operations Manager", "Finance Manager"],
    },
    {
      key: "return-chain",
      name: "Return / refund review",
      workflowKey: "return-review",
      steps: ["Customer Service Agent", "Store Manager", "Finance Clerk"],
    },
    {
      key: "adjust-chain",
      name: "Stock adjustment",
      workflowKey: "inv-count",
      steps: ["Inventory Controller", "Store Manager", "Retail Operations Manager"],
    },
    {
      key: "cash-chain",
      name: "Cash reconciliation",
      workflowKey: "cash-recon",
      steps: ["Finance Clerk", "Store Manager", "Finance Manager"],
    },
    {
      key: "supplier-chain",
      name: "Supplier purchase",
      workflowKey: "supplier-pr",
      steps: ["Buyer", "Procurement Lead", "Finance Manager"],
    },
  ],
  cybercrowBaselines: [
    {
      key: "pos-boundary",
      name: "POS / payment boundary readiness",
      controls: ["pos_role_separation", "payment_data_boundary"],
      riskFocus: "payment_boundary",
      monitoringLevel: "elevated",
    },
    {
      key: "refund-abuse",
      name: "Refund and return abuse readiness",
      controls: ["refund_approval_trail", "return_reason_codes"],
      riskFocus: "fraud",
      monitoringLevel: "elevated",
    },
    {
      key: "discount-override",
      name: "Discount override monitoring (advisory)",
      controls: ["discount_approval_log", "manager_override"],
      riskFocus: "fraud",
      monitoringLevel: "standard",
    },
    {
      key: "inv-adjust-audit",
      name: "Inventory adjustment audit trail",
      controls: ["stock_adjustment_signoff", "count_variance"],
      riskFocus: "inventory_integrity",
      monitoringLevel: "elevated",
    },
    {
      key: "store-access",
      name: "Store and branch access boundaries",
      controls: ["store_rbac", "branch_scope"],
      riskFocus: "access",
      monitoringLevel: "standard",
    },
    {
      key: "customer-privacy",
      name: "Customer data handling readiness",
      controls: ["crm_access_review", "pii_minimization"],
      riskFocus: "privacy",
      monitoringLevel: "standard",
    },
    {
      key: "privileged-retail",
      name: "Privileged retail role changes",
      controls: ["admin_session", "role_change_log"],
      riskFocus: "privilege",
      monitoringLevel: "critical",
    },
    {
      key: "supplier-fraud",
      name: "Supplier onboarding evidence",
      controls: ["vendor_approval", "bank_detail_change"],
      riskFocus: "supply_chain",
      monitoringLevel: "standard",
    },
  ],
  sareaProfiles: [
    {
      key: "exec-retail",
      name: "Executive / owner strategic view",
      positionKey: "owner",
      experienceProfile: "Revenue, store health, risk posture",
      dashboardType: "strategic",
      complexityLevel: "executive",
      personaKey: "executive",
    },
    {
      key: "retail-ops-dash",
      name: "Retail operations control board",
      positionKey: "retail-ops-mgr",
      experienceProfile: "Workflows, branches, tasks, exceptions",
      dashboardType: "control",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "store-dash",
      name: "Store manager operational dashboard",
      positionKey: "store-mgr",
      experienceProfile: "Daily tasks, stock issues, staff actions",
      dashboardType: "operational",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "associate-mobile",
      name: "Frontline associate mobile UI",
      positionKey: "associate",
      experienceProfile: "Assigned tasks, escalations, POS guidance (no live payments)",
      dashboardType: "mobile",
      complexityLevel: "frontline",
      personaKey: "frontline",
    },
    {
      key: "inventory-dash",
      name: "Inventory controller workspace",
      positionKey: "inv-ctrl",
      experienceProfile: "Receiving, adjustments, replenishment",
      dashboardType: "operational",
      complexityLevel: "specialist",
      personaKey: "specialist",
    },
    {
      key: "analyst-dash",
      name: "Retail analyst insights",
      positionKey: "analyst",
      experienceProfile: "Reports, trends, evidence gaps",
      dashboardType: "analytical",
      complexityLevel: "specialist",
      personaKey: "analyst",
    },
    {
      key: "admin-dash",
      name: "Tenant admin configuration",
      positionKey: "tenant-admin",
      experienceProfile: "Users, roles, access, configuration",
      dashboardType: "admin",
      complexityLevel: "manager",
      personaKey: "manager",
    },
    {
      key: "cc-console",
      name: "CyberCrow security console",
      positionKey: "cc-analyst",
      experienceProfile: "Retail evidence, incidents, access reviews",
      dashboardType: "security",
      complexityLevel: "security",
      personaKey: "security",
    },
  ],
};

export const SECTOR_TEMPLATE_CATALOG: Record<SectorTemplateKey, OrgIntelligenceModel> = {
  logistics: LOGISTICS,
  construction: CONSTRUCTION,
  aviation: AVIATION,
  healthcare: HEALTHCARE,
  retail: RETAIL,
};

export const SECTOR_TEMPLATE_KEYS = Object.keys(SECTOR_TEMPLATE_CATALOG) as SectorTemplateKey[];

export function getSectorTemplateModel(key: SectorTemplateKey): OrgIntelligenceModel {
  return structuredClone(SECTOR_TEMPLATE_CATALOG[key]);
}
