import type { DepartmentArchetypeDefinition } from "../domain-types";

const dept = (key: string, displayName: string, purpose: string): DepartmentArchetypeDefinition => ({
  key,
  displayName,
  description: purpose,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  purpose,
  commonResponsibilities: [],
  recommendedWorkPersonaKeys: [],
  workflowOwnership: [],
  entityOwnership: [],
  typicalKpiKeys: [],
  recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust"],
  scaleBehavior: "May merge at MICRO scale; may split at ENTERPRISE",
  mergeCandidateKeys: [],
  splitCandidateKeys: [],
  grantsPermissions: false,
});

export const DEPARTMENT_ARCHETYPE_CATALOG: readonly DepartmentArchetypeDefinition[] = [
  { ...dept("executive_office", "Executive office", "Strategic direction and executive approvals."), recommendedWorkPersonaKeys: ["outcome_owner"], recommendedSareaPatternKey: "executive_command_center", typicalKpiKeys: ["outcome_completion_rate"] },
  { ...dept("operations", "Operations", "Day-to-day operational delivery."), recommendedWorkPersonaKeys: ["workflow_coordinator", "field_coordinator"], workflowOwnership: ["dispatch_and_delivery", "work_order_execution"], recommendedSareaPatternKey: "operations_control_board", mergeCandidateKeys: ["customer_service", "field_operations"] },
  { ...dept("human_resources", "Human resources", "Workforce lifecycle and policies."), recommendedWorkPersonaKeys: ["compliance_liaison"], entityOwnership: ["employee_record"], recommendedCyberCrowPolicyPackKeys: ["sensitive_hr_data"] },
  { ...dept("finance_operations", "Finance operations", "Operational finance workflows — not regulated audit."), recommendedWorkPersonaKeys: ["risk_reviewer"], workflowOwnership: ["request_and_approval"], typicalKpiKeys: ["approval_bottleneck_index"] },
  { ...dept("sales_and_commercial", "Sales and commercial", "Revenue and client acquisition."), recommendedWorkPersonaKeys: ["relationship_owner"], entityOwnership: ["customer", "contract"] },
  { ...dept("customer_service", "Customer service", "Customer support and case resolution."), recommendedWorkPersonaKeys: ["case_lead", "customer_journey_owner"], workflowOwnership: ["case_resolution"], recommendedSareaPatternKey: "case_inbox", mergeCandidateKeys: ["operations"] },
  { ...dept("procurement", "Procurement", "Purchasing and vendor engagement."), recommendedWorkPersonaKeys: ["supplier_risk_liaison"], workflowOwnership: ["procure_to_receive", "vendor_qualification"] },
  { ...dept("supply_chain", "Supply chain", "Inventory and fulfillment coordination."), recommendedWorkPersonaKeys: ["resource_allocator", "cross_branch_resource_balancer"], entityOwnership: ["inventory_item", "shipment"] },
  { ...dept("projects", "Projects", "Project delivery management."), recommendedWorkPersonaKeys: ["project_controller"], workflowOwnership: ["project_delivery", "project_change_control"], recommendedSareaPatternKey: "project_workspace" },
  { ...dept("engineering", "Engineering", "Technical design and delivery."), recommendedWorkPersonaKeys: ["quality_reviewer"], splitCandidateKeys: ["field_operations"] },
  { ...dept("field_operations", "Field operations", "Mobile and site execution."), recommendedWorkPersonaKeys: ["field_coordinator"], recommendedSareaPatternKey: "field_task_mobile", mergeCandidateKeys: ["operations"] },
  { ...dept("legal", "Legal", "Matter coordination — not legal advice."), recommendedWorkPersonaKeys: ["legal_matter_intake_coordinator"], entityOwnership: ["legal_matter"] },
  { ...dept("compliance", "Compliance", "Operational compliance liaison."), recommendedWorkPersonaKeys: ["compliance_liaison", "evidence_custodian"], recommendedSareaPatternKey: "compliance_cockpit" },
  { ...dept("quality", "Quality", "Quality assurance and inspection."), recommendedWorkPersonaKeys: ["quality_reviewer"], workflowOwnership: ["inspection_and_corrective_action"] },
  { ...dept("health_and_safety", "Health and safety", "Safety programs and incident prevention."), recommendedWorkPersonaKeys: ["incident_commander"], workflowOwnership: ["incident_command"] },
  { ...dept("technology", "Technology", "IT systems and automation."), recommendedWorkPersonaKeys: ["automation_supervisor"], recommendedCyberCrowPolicyPackKeys: ["privileged_access"] },
  { ...dept("cybersecurity", "Cybersecurity", "Tenant security posture."), recommendedWorkPersonaKeys: ["incident_commander"], recommendedSareaPatternKey: "security_posture_console", recommendedCyberCrowPolicyPackKeys: ["privileged_access", "incident_escalation"] },
  { ...dept("data_and_analytics", "Data and analytics", "Reporting and decision support."), recommendedWorkPersonaKeys: ["capacity_planner"], recommendedSareaPatternKey: "analytics_workspace", typicalKpiKeys: ["capacity_utilization"] },
  { ...dept("facilities", "Facilities", "Building and site operations."), recommendedWorkPersonaKeys: ["field_coordinator"], entityOwnership: ["location", "asset"] },
  { ...dept("asset_management", "Asset management", "Asset registry and lifecycle."), recommendedWorkPersonaKeys: ["resource_allocator"], entityOwnership: ["asset"] },
  { ...dept("creative", "Creative", "Creative production."), recommendedWorkPersonaKeys: ["creative_production_asset_coordinator"], recommendedSareaPatternKey: "project_workspace" },
  { ...dept("production", "Production", "Production execution."), recommendedWorkPersonaKeys: ["release_coordinator", "production_rights_clearance_coordinator"], workflowOwnership: ["creative_asset_production", "release_readiness"] },
  { ...dept("publishing", "Publishing", "Content publication."), recommendedWorkPersonaKeys: ["release_coordinator"], workflowOwnership: ["content_review_and_publication"] },
  { ...dept("research_operations", "Research operations", "Research admin — no clinical decisions."), recommendedWorkPersonaKeys: ["research_evidence_custodian"], entityOwnership: ["research_sample_record"] },
  { ...dept("education_and_training", "Education and training", "Programs and cohorts."), recommendedWorkPersonaKeys: ["workflow_coordinator"], entityOwnership: ["training_cohort", "membership"] },
  { ...dept("membership_operations", "Membership operations", "Member enrollment and services."), recommendedWorkPersonaKeys: ["customer_journey_owner"], workflowOwnership: ["member_enrollment"] },
  { ...dept("partner_management", "Partner management", "Partner and vendor relationships."), recommendedWorkPersonaKeys: ["relationship_owner", "supplier_risk_liaison"] },
  { ...dept("shared_services", "Shared services", "Centralized support functions."), recommendedWorkPersonaKeys: ["workflow_coordinator"], mergeCandidateKeys: ["operations", "finance_operations"] },
] as const;
