import type { WorkPersonaDefinition, WorkflowPosition } from "../types";

const persona = (
  key: string,
  displayName: string,
  purpose: string,
  roles: string[],
  positions: WorkflowPosition[] = ["COORDINATOR"],
): WorkPersonaDefinition => ({
  key,
  displayName,
  description: purpose,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  purpose,
  responsibilities: [],
  expectedOutcomes: [],
  workflowParticipation: [],
  workflowPositions: positions,
  decisionRights: [],
  approvalLimits: [],
  dataVisibilityRecommendations: [],
  evidenceObligations: [],
  escalationDuties: [],
  kpiRecommendationKeys: [],
  recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust"],
  organizationalScope: "department",
  sourceRoleArchetypeKeys: roles,
  grantsPermissions: false,
  authoritative: false,
});

export const PERSONA_BUILDING_BLOCKS = [
  "outcome_owner",
  "workflow_coordinator",
  "case_lead",
  "project_controller",
  "resource_allocator",
  "capacity_planner",
  "field_coordinator",
  "evidence_custodian",
  "risk_reviewer",
  "quality_reviewer",
  "relationship_owner",
  "escalation_owner",
  "incident_commander",
  "release_coordinator",
  "rights_clearance_coordinator",
  "compliance_liaison",
  "customer_journey_owner",
  "automation_supervisor",
] as const;

export const WORK_PERSONA_CATALOG: readonly WorkPersonaDefinition[] = [
  {
    ...persona("outcome_owner", "Outcome owner", "Accountable for business outcome delivery.", ["executive", "department_manager"], ["OWNER"]),
    responsibilities: ["Define success metrics", "Remove blockers", "Approve escalations"],
    expectedOutcomes: ["Outcome achieved within SLA"],
    decisionRights: ["escalation_approval"],
    kpiRecommendationKeys: ["outcome_completion_rate"],
    recommendedSareaPatternKey: "executive_command_center",
  },
  {
    ...persona("workflow_coordinator", "Workflow coordinator", "Coordinates cross-functional workflow execution.", ["coordinator"], ["COORDINATOR"]),
    responsibilities: ["Route work", "Monitor queues", "Coordinate handoffs"],
    workflowParticipation: ["request_and_approval", "case_resolution"],
    recommendedSareaPatternKey: "operations_control_board",
  },
  {
    ...persona("case_lead", "Case lead", "Owns case resolution from intake to closure.", ["specialist", "supervisor"], ["OWNER", "COORDINATOR"]),
    responsibilities: ["Triage cases", "Assign contributors", "Close with evidence"],
    workflowParticipation: ["case_resolution"],
    kpiRecommendationKeys: ["case_resolution_time", "first_contact_resolution"],
    recommendedSareaPatternKey: "case_inbox",
  },
  {
    ...persona("project_controller", "Project controller", "Controls project schedule and change gates.", ["department_manager", "specialist"], ["OWNER", "REVIEWER"]),
    responsibilities: ["Track milestones", "Manage change requests", "Report variance"],
    workflowParticipation: ["project_delivery", "project_change_control"],
    recommendedSareaPatternKey: "project_workspace",
  },
  {
    ...persona("resource_allocator", "Resource allocator", "Allocates people, assets, and capacity.", ["coordinator", "dispatcher"], ["COORDINATOR"]),
    responsibilities: ["Balance load", "Assign resources", "Resolve conflicts"],
    workflowParticipation: ["dispatch_and_delivery", "work_order_execution"],
    recommendedSareaPatternKey: "dispatch_console",
  },
  {
    ...persona("capacity_planner", "Capacity planner", "Plans workforce and asset capacity.", ["analyst", "coordinator"], ["CONTRIBUTOR"]),
    responsibilities: ["Forecast demand", "Identify bottlenecks"],
    kpiRecommendationKeys: ["capacity_utilization", "backlog_age"],
    recommendedSareaPatternKey: "analytics_workspace",
  },
  {
    ...persona("field_coordinator", "Field coordinator", "Coordinates mobile field execution.", ["supervisor", "dispatcher"], ["COORDINATOR", "EXECUTOR"]),
    responsibilities: ["Dispatch tasks", "Handle exceptions", "Verify completion"],
    workflowParticipation: ["work_order_execution", "dispatch_and_delivery"],
    recommendedSareaPatternKey: "field_task_mobile",
    recommendedCyberCrowPolicyPackKeys: ["field_device_trust"],
  },
  {
    ...persona("evidence_custodian", "Evidence custodian", "Maintains evidence chain of custody.", ["auditor", "specialist"], ["EVIDENCE_CUSTODIAN"]),
    responsibilities: ["Collect evidence", "Verify completeness", "Support audits"],
    evidenceObligations: ["chain_of_custody", "immutable_attachments"],
    recommendedSareaPatternKey: "compliance_cockpit",
    recommendedCyberCrowPolicyPackKeys: ["audit_and_evidence"],
  },
  {
    ...persona("risk_reviewer", "Risk reviewer", "Reviews risk before high-impact decisions.", ["approver", "auditor"], ["REVIEWER"]),
    responsibilities: ["Assess risk", "Document rationale"],
    decisionRights: ["risk_sign_off"],
    recommendedSareaPatternKey: "compliance_cockpit",
  },
  {
    ...persona("quality_reviewer", "Quality reviewer", "Reviews quality gates and inspections.", ["specialist", "supervisor"], ["INSPECTOR", "REVIEWER"]),
    responsibilities: ["Inspect outputs", "Approve quality release"],
    workflowParticipation: ["inspection_and_corrective_action"],
    recommendedSareaPatternKey: "specialist_workspace",
  },
  {
    ...persona("relationship_owner", "Relationship owner", "Owns client or partner relationships.", ["sales_representative", "coordinator"], ["OWNER"]),
    responsibilities: ["Maintain relationship health", "Coordinate renewals"],
    recommendedSareaPatternKey: "specialist_workspace",
  },
  {
    ...persona("escalation_owner", "Escalation owner", "Owns escalated issues across teams.", ["supervisor", "department_manager"], ["ESCALATION_OWNER"]),
    responsibilities: ["Triage escalations", "Authorize exceptions"],
    escalationDuties: ["cross_team_escalation"],
    recommendedSareaPatternKey: "manager_work_queue",
  },
  {
    ...persona("incident_commander", "Incident commander", "Leads incident command structure.", ["security_administrator", "supervisor"], ["OWNER", "ESCALATION_OWNER"]),
    responsibilities: ["Declare incident severity", "Coordinate response", "Close with postmortem"],
    workflowParticipation: ["incident_command", "incident_to_resolution"],
    recommendedSareaPatternKey: "security_posture_console",
    recommendedCyberCrowPolicyPackKeys: ["incident_escalation"],
  },
  {
    ...persona("release_coordinator", "Release coordinator", "Coordinates release readiness.", ["coordinator", "specialist"], ["COORDINATOR", "FINAL_SIGNATORY"]),
    responsibilities: ["Run release checklist", "Coordinate sign-offs"],
    workflowParticipation: ["release_readiness"],
    recommendedSareaPatternKey: "operations_control_board",
  },
  {
    ...persona("rights_clearance_coordinator", "Rights clearance coordinator", "Coordinates rights and clearance workflows.", ["specialist", "coordinator"], ["COORDINATOR", "REVIEWER"]),
    responsibilities: ["Track clearance status", "Coordinate legal review"],
    workflowParticipation: ["rights_clearance"],
  },
  {
    ...persona("compliance_liaison", "Compliance liaison", "Bridges operations and compliance requirements.", ["auditor", "hr_specialist"], ["REVIEWER", "OBSERVER"]),
    responsibilities: ["Monitor control coverage", "Coordinate attestations"],
    recommendedSareaPatternKey: "compliance_cockpit",
    recommendedCyberCrowPolicyPackKeys: ["audit_and_evidence"],
  },
  {
    ...persona("customer_journey_owner", "Customer journey owner", "Owns end-to-end customer experience.", ["coordinator", "sales_representative"], ["OWNER"]),
    responsibilities: ["Map journey stages", "Resolve friction points"],
    recommendedSareaPatternKey: "customer_portal",
  },
  {
    ...persona("automation_supervisor", "Automation supervisor", "Oversees human-AI workflow boundaries.", ["tenant_administrator", "specialist"], ["REVIEWER", "OBSERVER"]),
    responsibilities: ["Review automation proposals", "Approve AI-assisted steps"],
    recommendedCyberCrowPolicyPackKeys: ["privileged_access", "high_risk_workflow_approval"],
  },
  {
    ...persona("live_game_operations_coordinator", "Live Game Operations Coordinator", "Coordinates live game ops, incidents, and releases.", ["coordinator", "specialist"], ["COORDINATOR", "ESCALATION_OWNER"]),
    provenance: "operator",
    responsibilities: ["Monitor live health", "Coordinate patch releases", "Route player incidents"],
    workflowParticipation: ["release_readiness", "incident_command"],
    recommendedSareaPatternKey: "operations_control_board",
  },
  {
    ...persona("production_rights_clearance_coordinator", "Production Rights and Clearance Coordinator", "Manages production rights clearance.", ["specialist", "coordinator"], ["COORDINATOR", "REVIEWER"]),
    provenance: "operator",
    responsibilities: ["Track asset rights", "Coordinate clearance approvals"],
    workflowParticipation: ["rights_clearance", "creative_asset_production"],
    recommendedSareaPatternKey: "specialist_workspace",
  },
  {
    ...persona("legal_matter_intake_coordinator", "Legal Matter Intake Coordinator", "Intake and conflict screening — not legal advice.", ["coordinator", "hr_specialist"], ["COORDINATOR", "REVIEWER"]),
    provenance: "operator",
    responsibilities: ["Intake matters", "Route conflict checks", "Assign case teams"],
    workflowParticipation: ["matter_intake_and_conflict_check"],
    recommendedSareaPatternKey: "case_inbox",
  },
  {
    ...persona("remote_workforce_mobilization_coordinator", "Remote Workforce Mobilization Coordinator", "Mobilizes distributed field teams.", ["coordinator", "supervisor"], ["COORDINATOR"]),
    provenance: "operator",
    responsibilities: ["Mobilize crews", "Track readiness", "Coordinate logistics"],
    workflowParticipation: ["site_mobilization", "crew_onboarding"],
    recommendedSareaPatternKey: "operations_control_board",
  },
  {
    ...persona("fleet_energy_optimization_lead", "Fleet Energy Optimization Lead", "Optimizes fleet energy and utilization.", ["analyst", "supervisor"], ["OWNER", "CONTRIBUTOR"]),
    provenance: "operator",
    responsibilities: ["Analyze utilization", "Recommend routing changes"],
    kpiRecommendationKeys: ["fleet_utilization", "energy_per_unit"],
    recommendedSareaPatternKey: "analytics_workspace",
  },
  {
    ...persona("event_readiness_controller", "Event Readiness Controller", "Controls event go-live readiness.", ["coordinator", "department_manager"], ["OWNER", "FINAL_SIGNATORY"]),
    provenance: "operator",
    responsibilities: ["Run readiness checklist", "Coordinate vendors"],
    workflowParticipation: ["release_readiness", "booking_to_service_completion"],
    recommendedSareaPatternKey: "project_workspace",
  },
  {
    ...persona("research_evidence_custodian", "Research Evidence Custodian", "Custody of research evidence — no clinical decisions.", ["specialist", "auditor"], ["EVIDENCE_CUSTODIAN"]),
    provenance: "operator",
    responsibilities: ["Maintain sample records", "Support audit trails"],
    evidenceObligations: ["sample_chain_of_custody", "lab_notebook_integrity"],
    workflowParticipation: ["research_review_and_evidence"],
    recommendedSareaPatternKey: "compliance_cockpit",
  },
  {
    ...persona("supplier_risk_liaison", "Supplier Risk Liaison", "Coordinates supplier risk reviews.", ["procurement_specialist", "auditor"], ["REVIEWER", "COORDINATOR"]),
    provenance: "operator",
    responsibilities: ["Qualify suppliers", "Track risk ratings"],
    workflowParticipation: ["vendor_qualification", "high_risk_supplier_onboarding"],
    recommendedCyberCrowPolicyPackKeys: ["vendor_access", "audit_and_evidence"],
  },
  {
    ...persona("cross_branch_resource_balancer", "Cross-Branch Resource Balancer", "Balances resources across branches.", ["coordinator", "analyst"], ["COORDINATOR"]),
    provenance: "operator",
    responsibilities: ["Rebalance capacity", "Resolve branch conflicts"],
    workflowParticipation: ["dispatch_and_delivery", "request_and_approval"],
    recommendedSareaPatternKey: "operations_control_board",
    recommendedCyberCrowPolicyPackKeys: ["branch_access_control"],
  },
  {
    ...persona("creative_production_asset_coordinator", "Creative Production Asset Coordinator", "Coordinates creative asset production.", ["coordinator", "specialist"], ["COORDINATOR", "CONTRIBUTOR"]),
    provenance: "operator",
    responsibilities: ["Track asset versions", "Coordinate reviews"],
    workflowParticipation: ["creative_asset_production", "content_review_and_publication"],
    recommendedSareaPatternKey: "project_workspace",
  },
] as const;
