import type { WorkPersonaDefinition } from "../types";

const persona = (
  key: string,
  displayName: string,
  purpose: string,
  workflows: string[],
): WorkPersonaDefinition => ({
  key,
  displayName,
  description: purpose,
  status: "PLANNED",
  version: "1.0.0",
  provenance: "crow_core",
  purpose,
  responsibilities: ["Coordinate advisory workflow participation", "Maintain evidence recommendations"],
  expectedOutcomes: ["Workflow completed with documented handoffs"],
  workflowParticipation: workflows,
  workflowPositions: ["COORDINATOR"],
  decisionRights: [],
  approvalLimits: [],
  dataVisibilityRecommendations: ["operational_scope_only"],
  evidenceObligations: [],
  escalationDuties: [],
  kpiRecommendationKeys: [],
  recommendedCyberCrowPolicyPackKeys: ["baseline_identity_trust", "audit_and_evidence"],
  recommendedSareaPatternKey: "specialist_workspace",
  organizationalScope: "department",
  sourceRoleArchetypeKeys: ["coordinator", "specialist"],
  grantsPermissions: false,
  authoritative: false,
});

/** MODEL.2 field-specific reference personas — advisory only. */
export const WORK_PERSONA_EXTENDED_CATALOG: readonly WorkPersonaDefinition[] = [
  persona("client_bookkeeping_coordinator", "Client Bookkeeping Coordinator", "Coordinates client bookkeeping cycles — not audit certification.", ["bookkeeping_month_close"]),
  persona("insurance_client_service_coordinator", "Insurance Client Service Coordinator", "Brokerage client onboarding — not underwriting.", ["insurance_client_onboarding"]),
  persona("localization_project_manager", "Localization Project Manager", "Manages translation project delivery.", ["translation_project_delivery"]),
  persona("travel_operations_coordinator", "Travel Operations Coordinator", "Coordinates travel booking cases.", ["travel_booking_case"]),
  persona("studio_production_coordinator", "Studio Production Coordinator", "Coordinates photography and studio delivery.", ["photography_project_delivery"]),
  persona("print_production_controller", "Print Production Controller", "Controls print job production.", ["print_job_production"]),
  persona("casting_and_talent_coordinator", "Casting and Talent Coordinator", "Coordinates casting and talent engagement.", ["talent_casting_and_engagement"]),
  persona("sports_program_operations_lead", "Sports Program Operations Lead", "Leads sports program enrollment operations.", ["sports_program_enrollment"]),
  persona("esports_tournament_operations_coordinator", "Esports Tournament Operations Coordinator", "Coordinates tournament operations.", ["esports_tournament_operations"]),
  persona("consulting_engagement_manager", "Consulting Engagement Manager", "Manages consulting engagement delivery.", ["consulting_engagement_delivery"]),
  persona("enrollment_and_family_coordinator", "Enrollment and Family Coordinator", "Coordinates nursery enrollment.", ["nursery_enrollment"]),
  persona("veterinary_practice_coordinator", "Veterinary Practice Coordinator", "Practice administration — not diagnosis.", ["veterinary_visit_administration"]),
  persona("clinic_operations_coordinator", "Clinic Operations Coordinator", "Clinic scheduling administration.", ["clinic_appointment_administration"]),
  persona("pharmacy_inventory_controller", "Pharmacy Inventory Controller", "Stock control — not prescribing.", ["pharmacy_stock_control"]),
  persona("vehicle_handover_coordinator", "Vehicle Handover Coordinator", "Coordinates vehicle sales handover.", ["vehicle_sales_handover"]),
  persona("rental_fleet_turnaround_controller", "Rental Fleet Turnaround Controller", "Controls rental fleet turnaround.", ["vehicle_rental_turnaround"]),
  persona("home_service_dispatch_coordinator", "Home Service Dispatch Coordinator", "Dispatches home service crews.", ["home_service_dispatch"]),
  persona("pest_control_route_planner", "Pest Control Route Planner", "Plans pest control service routes.", ["pest_control_service"]),
  persona("landscape_maintenance_supervisor", "Landscape Maintenance Supervisor", "Supervises landscaping maintenance cycles.", ["landscaping_maintenance_cycle"]),
  persona("commercial_cleaning_quality_controller", "Commercial Cleaning Quality Controller", "Quality control for cleaning contracts.", ["commercial_cleaning_contract"]),
  persona("catering_fulfillment_coordinator", "Catering Fulfillment Coordinator", "Coordinates catering order delivery.", ["catering_order_delivery"]),
  persona("import_documentation_coordinator", "Import Documentation Coordinator", "Coordinates import/export documents.", ["import_export_document_review"]),
  persona("customs_case_coordinator", "Customs Case Coordinator", "Coordinates customs submissions.", ["customs_submission_coordination"]),
  persona("warehouse_fulfillment_controller", "Warehouse Fulfillment Controller", "Controls warehouse fulfillment cycles.", ["warehouse_fulfillment_cycle"]),
  persona("fit_out_project_coordinator", "Fit-Out Project Coordinator", "Coordinates interior fit-out projects.", ["property_fitout_project"]),
  persona("wedding_production_coordinator", "Wedding Production Coordinator", "Coordinates wedding event delivery.", ["wedding_event_delivery"]),
  persona("nonprofit_program_case_lead", "Nonprofit Program Case Lead", "Leads nonprofit program cases.", ["nonprofit_program_case"]),
] as const;
