/** Client-facing capability groups for the capability builder step. */
export const CLIENT_CAPABILITY_GROUPS = [
  { key: "organization_workforce", label: "People and workforce" },
  { key: "customer_commercial", label: "Sales and customers" },
  { key: "projects_delivery", label: "Projects and services" },
  { key: "supply_chain_logistics", label: "Supply chain and logistics" },
  { key: "assets_facilities", label: "Assets and facilities" },
  { key: "finance_operations", label: "Finance operations" },
  { key: "governance_compliance", label: "Governance and compliance" },
  { key: "knowledge_communication", label: "Knowledge and communication" },
  { key: "automation_intelligence", label: "Automation and intelligence" },
] as const;

export const SPECIALIST_DOMAIN_CATEGORIES = [
  { key: "professional_services", label: "Professional services" },
  { key: "creative_media", label: "Creative and media" },
  { key: "technology_digital", label: "Technology and digital" },
  { key: "construction_field", label: "Construction and field operations" },
  { key: "commerce_distribution", label: "Commerce and distribution" },
  { key: "health_administration", label: "Health administration" },
  { key: "education_training", label: "Education and training" },
  { key: "property_facilities", label: "Property and facilities" },
  { key: "events_hospitality", label: "Events and hospitality" },
  { key: "transport_mobility", label: "Transport and mobility" },
  { key: "local_services", label: "Specialist local services" },
  { key: "membership_nonprofit", label: "Membership and nonprofit" },
] as const;

export const DOMAIN_CATEGORY_MAP: Record<string, string> = {
  legal_services: "professional_services",
  architecture_and_design: "professional_services",
  recruitment_and_staffing: "professional_services",
  marketing_and_creative_agency: "creative_media",
  film_and_video_production: "creative_media",
  music_and_audio_production: "creative_media",
  creator_and_talent_management: "creative_media",
  digital_content_publishing: "creative_media",
  gaming_and_esports: "technology_digital",
  telecom_operations: "technology_digital",
  construction_project_controls: "construction_field",
  equipment_rental: "construction_field",
  maintenance_services: "construction_field",
  agriculture_and_farming: "commerce_distribution",
  automotive_services: "commerce_distribution",
  healthcare_operations: "health_administration",
  research_and_laboratory_operations: "health_administration",
  education_and_training: "education_training",
  property_brokerage: "property_facilities",
  coworking_and_flexible_space: "property_facilities",
  cleaning_and_facility_services: "property_facilities",
  events_and_venues: "events_hospitality",
  membership_and_clubs: "membership_nonprofit",
  public_service_operations: "membership_nonprofit",
};
