/** MEEM Global operational catalog — re-exports logistics pack for backward compatibility. */



export {

  LOGISTICS_AI_EXTRA_KEYS as MEEM_AI_EXTRA_KEYS,

  LOGISTICS_DISCOVERY_WORKFLOWS as MEEM_DISCOVERY_WORKFLOWS,

  LOGISTICS_TENANT_WORKFLOWS as MEEM_TENANT_WORKFLOWS,

  LOGISTICS_DISCOVERY_BRANCHES as MEEM_DISCOVERY_BRANCHES,

  LOGISTICS_HR_SAMPLES as MEEM_HR_SAMPLES,

  LOGISTICS_CRM_SAMPLES as MEEM_CRM_SAMPLES,

  LOGISTICS_SALES_SAMPLES as MEEM_SALES_SAMPLES,

  LOGISTICS_INVENTORY_SAMPLES as MEEM_INVENTORY_SAMPLES,

  LOGISTICS_WAREHOUSE_SAMPLES as MEEM_WAREHOUSE_SAMPLES,

  LOGISTICS_WORKFLOW_META as MEEM_WORKFLOW_META,

  LOGISTICS_OCR_AI_WORKFLOW_NAMES as MEEM_OCR_AI_WORKFLOW_NAMES,

  LOGISTICS_TASK_SAMPLES as MEEM_TASK_SAMPLES,

  LOGISTICS_LOGISTICS_FEATURES as MEEM_LOGISTICS_FEATURES,

} from "@/lib/erp/industry-packs/logistics";



export type { LogisticsTenantWorkflowDef as MeemTenantWorkflowDef } from "@/lib/erp/industry-packs/logistics";


