/** Operator env keys — never store designated email or passwords in the repository. */
export const PLATFORM_OWNER_DESIGNATED_EMAIL_ENV = "PLATFORM_OWNER_DESIGNATED_EMAIL";
export const PLATFORM_OWNER_ACCOUNT_ID_ENV = "PLATFORM_OWNER_ACCOUNT_ID";
export const PLATFORM_OWNER_BOOTSTRAP_EXECUTE_PHRASE_ENV =
  "PLATFORM_OWNER_BOOTSTRAP_EXECUTE_PHRASE";

/** Product-owner authorization phrase for execute (set at runtime only). */
export const PLATFORM_OWNER_BOOTSTRAP_EXECUTE_PHRASE =
  "GRANT PLATFORM OWNER TO DESIGNATED ACCOUNT";

export const PLATFORM_OWNER_FORBIDDEN_CREDENTIAL_ENV_KEYS = [
  "PLATFORM_OWNER_PASSWORD",
  "PLATFORM_OWNER_DESIGNATED_PASSWORD",
  "PLATFORM_ADMIN_PASSWORD",
] as const;

export const PLATFORM_OWNER_DATABASE_FINGERPRINT_ENV =
  "PLATFORM_OWNER_EXPECTED_DATABASE_FINGERPRINT";

export const PLATFORM_OWNER_PLAN_DIGEST_ENV = "PLATFORM_OWNER_PLAN_DIGEST";

export const PLATFORM_OWNER_CONFIRM_DESIGNATION_ENV =
  "PLATFORM_OWNER_CONFIRM_DESIGNATION";
